import test from 'node:test';import assert from 'node:assert/strict';
import {LibraryManagementService,fetchEpisodeIssues} from '../src/library-management.ts';
const scope={serverId:'server',viewerId:JSON.stringify(['local','owner','profile'])},wireScope={serverId:'server',viewerFence:'owner-fence'};
function library(id='one',name='Named library',revision=1):any{return {id,name,kind:'movie',revision,source:{path:'/owner/source/'+id,availability:'unknown',basis:'not_checked'},lastScan:null,actions:['rename','scan']};}
function job(id='job-one',libraryId='one'):any{return {id,libraryId,status:'running',processed:12,createdAt:'2026-09-05T00:00:00Z',updatedAt:null,finishedAt:null,actions:['cancel']};}
function data(path:string):any{const u=new URL(path,'https://x');if(u.pathname==='/v1/admin/libraries')return {scope:wireScope,revision:1,items:[library()],nextCursor:''};if(u.pathname==='/v1/admin/jobs')return {scope:wireScope,revision:1,items:[job('job-one',u.searchParams.get('libraryId')??'one')],nextCursor:''};return {scope:wireScope,library:library(decodeURIComponent(u.pathname.split('/').at(-1)!))};}
function service(fn:(path:string,method:string,body:unknown,signal?:AbortSignal)=>Promise<unknown>,timeoutMs=1000){return new LibraryManagementService({scope,timeoutMs,api:{request:<T>(p:string,m='GET',b?:unknown,s?:AbortSignal)=>fn(p,m,b,s) as Promise<T>}});}
function deferred(){let resolve!:(v:unknown)=>void;const promise=new Promise<unknown>(r=>resolve=r);return {promise,resolve};}
test('owner directory and selected source/jobs are bounded independent server projections',async()=>{const paths:string[]=[];const s=service(async p=>{paths.push(p);return data(p);});await s.loadLibraries();await s.selectLibrary('one');assert.equal(s.getSnapshot().directory.phase,'ready');assert.equal(s.getSnapshot().selected.data!.library.source.availability,'unknown');assert.equal(s.getSnapshot().jobs.data!.items[0].processed,12);assert(paths.some(p=>p==='/v1/admin/jobs?limit=40&libraryId=one'));assert.throws(()=>{(s.getSnapshot().directory.data!.items as any).push(library("other"));});s.dispose();});
test('late selected resource and jobs cannot overwrite rapid library switch',async()=>{const d=deferred();let signal:AbortSignal|undefined;const s=service(async(p,_m,_b,a)=>{if(p==='/v1/admin/libraries/one'){signal=a;return d.promise;}return data(p);});const pending=s.selectLibrary('one');await s.selectLibrary('two');await pending;assert(signal?.aborted);d.resolve(data('/v1/admin/libraries/one'));await Promise.resolve();assert.equal(s.getSnapshot().selected.data!.library.id,'two');assert.equal(s.getSnapshot().jobs.data!.items[0].libraryId,'two');s.dispose();});
test('directory continuation revision changes require refresh and retain no stale source paths',async()=>{const s=service(async p=>({...data(p),revision:p.includes('cursor=')?2:1,nextCursor:'next'}));await s.loadLibraries();await s.nextLibraries();assert.equal(s.getSnapshot().directory.phase,'refresh-required');assert.equal(s.getSnapshot().directory.data,null);await s.loadLibraries();assert.equal(s.getSnapshot().directory.phase,'ready');s.dispose();});
test('paging uses opaque server cursor and Previous exact page',async()=>{const paths:string[]=[];const s=service(async p=>{paths.push(p);return {...data(p),nextCursor:p.includes('cursor=')?'':'opaque&two'};});await s.loadLibraries();await s.nextLibraries();assert.equal(s.getSnapshot().directory.cursor,'opaque&two');await s.previousLibraries();assert.equal(s.getSnapshot().directory.cursor,null);assert(new URL(paths[1],'https://x').searchParams.get('cursor')==='opaque&two');s.dispose();});
test('rename uses exact CAS and refreshes authoritative reads without automatic replay',async()=>{let name='Named library',revision=1;const writes:unknown[]=[];const s=service(async(p,m,b)=>{if(m==='PATCH'){writes.push(b);name=(b as any).name;revision++;return {scope:wireScope,library:library('one',name,revision)};}const raw=data(p);if(raw.library)raw.library=library('one',name,revision);return raw;});await s.selectLibrary('one');await s.rename('Renamed',1);assert.deepEqual(writes,[{name:'Renamed',expectedRevision:1}]);assert.equal(s.getSnapshot().selected.data!.library.name,'Renamed');assert.equal(s.getSnapshot().mutation.phase,'complete');assert.throws(()=>s.rename('Again',1));s.dispose();});
test('lost scan response stays ambiguous; reconciliation issues GETs only',async()=>{let writes=0;const s=service(async(p,m)=>{if(m==='POST'){writes++;throw new TypeError('Network response lost');}return data(p);});await s.selectLibrary('one');await s.scan();assert.equal(s.getSnapshot().mutation.phase,'ambiguous');await s.reconcile();assert.equal(writes,1);assert.equal(s.getSnapshot().mutation.phase,'ambiguous');s.dispose();});
test('duplicate scan is singleflight and different concurrent command is rejected',async()=>{const d=deferred();let writes=0;const s=service(async(p,m)=>{if(m==='POST'){writes++;return d.promise;}return data(p);});await s.selectLibrary('one');const a=s.scan(),b=s.scan();assert.equal(a,b);assert.equal(writes,1);assert.throws(()=>s.rename('New',1));d.resolve({id:'new-job',status:'queued',processed:0});await a;assert.equal(s.getSnapshot().mutation.phase,'complete');s.dispose();});
test('CAS conflict remains an error until owner reads current state, no auto rename',async()=>{let writes=0;const s=service(async(p,m)=>{if(m==='PATCH'){writes++;throw Object.assign(new Error('Changed'),{code:'library_configuration_conflict'});}return data(p);});await s.selectLibrary('one');await s.rename('New',1);assert.equal(s.getSnapshot().mutation.phase,'error');await s.reconcile();assert.equal(writes,1);s.dispose();});
test('job cancellation requires server action and only refreshes after acknowledgement',async()=>{const writes:string[]=[];const s=service(async(p,m)=>{if(m==='DELETE'){writes.push(p);return undefined;}return data(p);});await s.selectLibrary('one');assert.throws(()=>s.cancelJob('foreign'));await s.cancelJob('job-one');assert.deepEqual(writes,['/v1/admin/ingestion/jobs/job-one']);assert.equal(s.getSnapshot().mutation.phase,'complete');s.dispose();});
test('scope change during mutation fences late response and clears source paths',async()=>{const d=deferred();const s=service(async(p,m)=>m==='PATCH'?d.promise:data(p));await s.selectLibrary('one');const pending=s.rename('New',1);s.setScope({...scope,viewerId:'another'},{request:async<T>()=>{throw new Error('unused');}});await pending;d.resolve({scope:wireScope,library:library('one','New',2)});await Promise.resolve();assert.equal(s.getSnapshot().selected.data,null);assert.equal(s.getSnapshot().directory.data,null);assert.equal(s.getSnapshot().mutation.phase,'idle');s.dispose();});
test('owner denial on any lane clears every privileged cached projection',async()=>{let denied=false;const s=service(async p=>{if(denied)throw Object.assign(new Error('Denied'),{status:403,code:'forbidden'});return data(p);});await s.loadLibraries();await s.selectLibrary('one');denied=true;await s.loadJobs();assert.equal(s.getSnapshot().directory.data,null);assert.equal(s.getSnapshot().selected.data,null);assert.equal(s.getSnapshot().jobs.phase,'error');s.dispose();});
test('malformed source/job tuple, oversized pages and changed owner fence fail closed',async()=>{for(const bad of ['job','size','fence']){const s=service(async p=>{const raw=data(p);if(p.includes('/jobs')){if(bad==='job')raw.items[0].libraryId='foreign';if(bad==='size')raw.items=Array(41).fill(job());if(bad==='fence')raw.scope={...wireScope,viewerFence:'changed'};}return raw;});await s.loadLibraries();await s.selectLibrary('one');assert.equal(s.getSnapshot().jobs.phase,'error');assert.equal(s.getSnapshot().jobs.data,null);s.dispose();}});
test('create selects acknowledged library and never automatically scans',async()=>{const writes:string[]=[];const s=service(async(p,m,b)=>{if(m==='POST'){writes.push(p);return {id:'created',name:(b as any).name,kind:'movie',defaultView:'discover'};}return data(p);});await s.loadLibraries();await s.createLibrary({name:'Created',kind:'movie',path:'/server/source'});assert.deepEqual(writes,['/v1/libraries']);assert.equal(s.getSnapshot().selectedLibraryId,'created');assert.equal(s.getSnapshot().selected.data!.library.id,'created');assert.equal(s.getSnapshot().mutation.phase,'complete');s.dispose();});
test('lost create and command timeout never trigger automatic duplicate creation',async()=>{let writes=0;const s=service(async(p,m)=>{if(m==='POST'){writes++;return new Promise(()=>{});}return data(p);},5);await s.loadLibraries();await s.createLibrary({name:'Created',kind:'movie',path:'/server/source'});assert.equal(s.getSnapshot().mutation.phase,'ambiguous');assert.equal(s.getSnapshot().mutation.error?.code,'timeout');await s.reconcile();assert.equal(writes,1);assert.equal(s.getSnapshot().selectedLibraryId,null);s.dispose();});
test('slow isolated source inspection cannot block directory or filtered job reads',async()=>{const s=service(async p=>p==='/v1/admin/libraries/one'?new Promise(()=>{}):data(p),5);await s.loadLibraries();await s.selectLibrary('one');assert.equal(s.getSnapshot().directory.phase,'ready');assert.equal(s.getSnapshot().jobs.phase,'ready');assert.equal(s.getSnapshot().selected.error?.code,'timeout');s.dispose();});
test('same-library reselection fences the canceled command even if its response is late',async()=>{const d=deferred();const s=service(async(p,m)=>m==='PATCH'?d.promise:data(p));await s.selectLibrary('one');const old=s.rename('Old command',1);await s.selectLibrary('one');await old;d.resolve({scope:wireScope,library:library('one','Old command',2)});await Promise.resolve();assert.equal(s.getSnapshot().selected.data!.library.name,'Named library');assert.equal(s.getSnapshot().mutation.phase,'idle');s.dispose();});
test('directory paging history remains bounded and selected response identity cannot be relabelled',async()=>{const s=service(async p=>{const u=new URL(p,'https://x'),index=Number(u.searchParams.get('cursor')??0);return {...data(p),nextCursor:String(index+1)};});await s.loadLibraries();for(let i=0;i<70;i++)await s.nextLibraries();for(let i=0;i<64;i++)await s.previousLibraries();assert.equal(s.getSnapshot().directory.canPrevious,false);assert.equal(s.getSnapshot().directory.cursor,'6');s.dispose();const bad=service(async p=>p==='/v1/admin/libraries/one'?{scope:wireScope,library:library('foreign')}:data(p));await bad.selectLibrary('one');assert.equal(bad.getSnapshot().selected.phase,'error');assert.equal(bad.getSnapshot().selected.data,null);bad.dispose();});
test('source already configured is a definite409 rejection, never ambiguous or automatically recreated',async()=>{let creates=0;const s=service(async(p,m)=>{if(m==='POST'){creates++;throw Object.assign(new Error('This source is already configured as a library. Open that library to manage or scan it.'),{status:409,code:'source_already_configured'});}return data(p);});await s.loadLibraries();await s.createLibrary({name:'Another name',kind:'movie',path:'/already/configured'});assert.equal(s.getSnapshot().mutation.phase,'error');assert.equal(s.getSnapshot().mutation.error?.code,'source_already_configured');assert.equal(s.getSnapshot().selectedLibraryId,null);await s.reconcile();assert.equal(creates,1);s.dispose();});

test('scan source recovery reason survives failed history only and unknown reasons fail closed',async()=>{for(const code of ['source_unavailable','private_internal_reason']){const s=service(async p=>{const raw=data(p);if(p.includes('/jobs'))raw.items=[{...job(),status:'failed',errorCode:code,error:'Source unavailable',finishedAt:'2026-09-05T01:00:00Z',actions:['retry']}];return raw;});await s.selectLibrary('one');assert.equal(s.getSnapshot().jobs.phase,code==='source_unavailable'?'ready':'error');if(code==='source_unavailable'){assert.equal(s.getSnapshot().jobs.data!.items[0].errorCode,code);assert.equal(s.getSnapshot().jobs.data!.items[0].processed,12);}s.dispose();}const s=service(async p=>{const raw=data(p);if(p.includes('/jobs'))raw.items[0].errorCode='source_unavailable';return raw;});await s.selectLibrary('one');assert.equal(s.getSnapshot().jobs.phase,'error');s.dispose();});
test('create sends the chosen metadata source, and omits it for the server default',async()=>{const bodies:unknown[]=[];const s=service(async(p,m,b)=>{if(m==='POST'){bodies.push(b);return {id:'created'+bodies.length,name:(b as any).name,kind:'movie',defaultView:'discover'};}return data(p);});await s.loadLibraries();await s.createLibrary({name:'Home videos',kind:'movie',path:'/server/home',metadataAgent:'local'});await s.createLibrary({name:'Movies',kind:'movie',path:'/server/movies'});assert.deepEqual(bodies,[{name:'Home videos',kind:'movie',path:'/server/home',metadataAgent:'local'},{name:'Movies',kind:'movie',path:'/server/movies'}]);assert.throws(()=>s.createLibrary({name:'Bad',kind:'movie',path:'/x',metadataAgent:'elsewhere' as never}));s.dispose();});

test('a 503 on the library read is retried with backoff, then shows the error; a success in between loads the library',async()=>{
 const busy=()=>Object.assign(new Error('Busy'),{status:503,code:'unavailable',retryable:true});
 let calls=0;const quick=(fn:(p:string)=>Promise<unknown>)=>new LibraryManagementService({scope,timeoutMs:1000,retryBaseMs:1,api:{request:<T>(p:string)=>fn(p) as Promise<T>}});
 const failing=quick(async p=>{if(p==='/v1/admin/libraries/one'){calls++;throw busy();}return data(p);});
 await failing.selectLibrary('one');
 assert.equal(calls,4);assert.equal(failing.getSnapshot().selected.phase,'error');assert.equal(failing.getSnapshot().selected.error?.code,'unavailable');
 let second=0;const recovering=quick(async p=>{if(p==='/v1/admin/libraries/one'&&++second<3)throw busy();return data(p);});
 await recovering.selectLibrary('one');
 assert.equal(recovering.getSnapshot().selected.phase,'ready');assert.equal(recovering.getSnapshot().selected.data?.library.id,'one');
 let refused=0;const never=quick(async p=>{if(p==='/v1/admin/libraries/one'){refused++;throw Object.assign(new Error('Nope'),{status:500,code:'internal',retry:'never'});}return data(p);});
 await never.selectLibrary('one');
 assert.equal(refused,1);assert.equal(never.getSnapshot().selected.phase,'error');
 failing.dispose();recovering.dispose();never.dispose();
});

test('files needing attention are read from the library, a full scan names its mode, and issues page with unreadable rows skipped',async()=>{
 const posts:string[]=[];const s=service(async(p,m)=>{if(m==='POST'){posts.push(p);return {id:'job',libraryId:'one',status:'queued',processed:0,createdAt:'2026-09-05T00:00:00Z',updatedAt:null,finishedAt:null,actions:[]};}const raw=data(p);if(p==='/v1/admin/libraries/one')raw.library.attention={files:1000,atLeast:true};return raw;});
 await s.selectLibrary('one');
 assert.deepEqual(s.getSnapshot().selected.data?.library.attention,{files:1000,atLeast:true});
 await s.scan('full');
 assert.equal(posts[0],'/v1/libraries/one/scans?mode=full');
 const bare=service(async p=>{const raw=data(p);if(p==='/v1/admin/libraries/one')raw.library.attention={files:'many'};return raw;});
 await bare.selectLibrary('one');
 assert.equal(bare.getSnapshot().selected.phase,'ready');assert.equal(bare.getSnapshot().selected.data?.library.attention,undefined);
 let asked='';const page=await fetchEpisodeIssues({request:async<T>(p:string)=>{asked=p;return {issues:[{assetId:'a1',sourceName:'Show.S01.mkv',code:'no_episode_number'},{assetId:'',sourceName:'bad',code:'x'}],nextCursor:'a1'} as T;}},'one','a0');
 assert.equal(asked,'/v1/libraries/one/episode-issues?limit=40&cursor=a0');
 assert.deepEqual(page.issues.map(x=>x.assetId),['a1']);assert.equal(page.nextCursor,'a1');
 s.dispose();bare.dispose();
});
test('create carries the metadata language only when shown, and an unoffered language is a definite refusal',async()=>{const bodies:unknown[]=[];const s=service(async(p,m,b)=>{if(m==='POST'){bodies.push(b);return {id:'created'+bodies.length,name:(b as any).name,kind:(b as any).kind,defaultView:'discover'};}return data(p);});await s.loadLibraries();await s.createLibrary({name:'Movies',kind:'movie',path:'/server/movies',metadataAgent:'online',metadataLanguage:'ja'});await s.createLibrary({name:'Home videos',kind:'movie',path:'/server/home'});assert.deepEqual(bodies,[{name:'Movies',kind:'movie',path:'/server/movies',metadataAgent:'online',metadataLanguage:'ja'},{name:'Home videos',kind:'movie',path:'/server/home'}]);for(const bad of ['en-US','EN','e','eng',''])assert.throws(()=>s.createLibrary({name:'Bad',kind:'movie',path:'/x',metadataLanguage:bad}));s.dispose();const refused=service(async(p,m)=>{if(m==='POST')throw Object.assign(new Error('Choose a metadata language offered for this library.'),{status:400,code:'invalid_metadata_language'});return data(p);});await refused.loadLibraries();await refused.createLibrary({name:'Movies',kind:'movie',path:'/server/movies',metadataLanguage:'xx'});assert.equal(refused.getSnapshot().mutation.phase,'error');assert.equal(refused.getSnapshot().mutation.error?.code,'invalid_metadata_language');refused.dispose();});
