import test from 'node:test';
import assert from 'node:assert/strict';
import {LibraryInventoryService,fetchInventoryStatus,inventoryStatusMessage,scanProgress} from '../src/library-inventory.ts';
const scope={serverId:'server',viewerId:'owner'};
const wire={serverId:'server',viewerFence:'fence'};
function config(){return {scope:wire,libraryId:'library',revision:1,sources:[{id:'source',libraryId:'library',kind:'local',name:'Mounted folder',path:'/media',resolvedPath:'/media',classification:'network',generation:1,health:'healthy',enabled:true,identityConfirmed:true,followSymlinks:false,missingGraceSeconds:86400,intervalSeconds:3600,nextScanAt:'',lastCompleteAt:'',lastProgressAt:''}],policy:{tier:'file_list_only',revision:1,operations:[]}};}
function page(){return {scope:wire,libraryId:'library',sourceId:'',revision:1,items:[],nextCursor:''};}
function service(handler:(path:string,method:string,body:unknown,signal?:AbortSignal)=>Promise<unknown>){return new LibraryInventoryService({scope,libraryId:'library',api:{request:<T>(p:string,m='GET',b?:unknown,a?:AbortSignal)=>handler(p,m,b,a) as Promise<T>}});}
function read(path:string){return path.endsWith('inventory-config')?config():page();}
test('inventory config and pages are server-scoped immutable projections',async()=>{const s=service(async p=>read(p));await s.refresh();assert.equal(s.getSnapshot().config?.sources[0].classification,'network');assert.equal(s.getSnapshot().objects?.revision,1);assert(Object.isFrozen(s.getSnapshot().config?.sources));s.dispose();});
test('mixed configuration revisions are rejected rather than merged',async()=>{const s=service(async p=>p.endsWith('inventory-config')?config():{...page(),revision:2});await s.refresh();assert(s.getSnapshot().error);assert.equal(s.getSnapshot().config,null);s.dispose();});
test('source commands include exact CAS and do not automatically start scans',async()=>{const writes:unknown[]=[];const s=service(async(p,m,b)=>{if(m!=='GET'){writes.push({p,m,b});return {};}return read(p);});await s.refresh();assert(await s.saveSource('source',{name:'Folder',path:'/media',classification:'network',followSymlinks:false,missingGraceSeconds:86400,intervalSeconds:3600,expectedRevision:1,acceptReplacement:false}));assert.equal(writes.length,1);assert.equal((writes[0] as any).m,'PATCH');assert.equal((writes[0] as any).b.expectedRevision,1);s.dispose();});
test('lost command responses require reconciliation and never replay writes',async()=>{let writes=0;const s=service(async(p,m)=>{if(m!=='GET'){writes++;throw new TypeError('Lost response');}return read(p);});await s.refresh();assert.equal(await s.scanSource('source'),false);assert.equal(s.getSnapshot().mutation,'ambiguous');await assert.rejects(s.scanSource('source'));await s.reconcile();assert.equal(writes,1);assert.equal(s.getSnapshot().mutation,'idle');s.dispose();});
test('privileged data is erased on owner denial',async()=>{let denied=false;const s=service(async p=>{if(denied)throw Object.assign(new Error('Denied'),{code:'forbidden'});return read(p);});await s.refresh();denied=true;await s.refresh();assert.equal(s.getSnapshot().config,null);assert.equal(s.getSnapshot().objects,null);s.dispose();});
test('disposal fences a late source response and aborts its request',async()=>{let release!:(v:unknown)=>void;let signal:AbortSignal|undefined;const held=new Promise<unknown>(r=>release=r);const s=service(async(p,_m,_b,a)=>{signal=a;return p.endsWith('inventory-config')?held:page();});const pending=s.refresh();s.dispose();assert(signal?.aborted);release(config());await pending;assert.equal(s.getSnapshot().config,null);});
test('repeated page cursors do not create an infinite inventory loop',async()=>{const s=service(async p=>p.endsWith('inventory-config')?config():{...page(),nextCursor:'same'});await s.refresh();await s.next();assert(s.getSnapshot().error);s.dispose();});
test('viewer status drops locators and refuses the wrong server',async()=>{const inventory={libraryId:'library',revision:2,sources:[{id:'source',health:'offline',lastCompleteAt:'',jobId:'job',status:'failed',phase:'inventory',discovered:3,analyzed:0,warnings:0,pauseReason:'',path:'/private'}]};const api={request:async<T>()=>({serverId:'server',inventory}) as T};const value=await fetchInventoryStatus(api,'server','library',new AbortController().signal);assert(!('path' in value.sources[0]));assert.match(inventoryStatusMessage(value),/Available versions can still play/);await assert.rejects(fetchInventoryStatus(api,'another','library',new AbortController().signal));});
test('scan progress is active only while sources queue or run, summing discovered files',()=>{const source=(status:string,discovered:number)=>({id:'s-'+status+'-'+discovered,health:'healthy',lastCompleteAt:'',jobId:'job',status,phase:'inventory',discovered,analyzed:0,warnings:0,pauseReason:''});assert.deepEqual(scanProgress(null),{scanning:false,found:0});assert.deepEqual(scanProgress({libraryId:'library',revision:1,sources:[]}),{scanning:false,found:0});assert.deepEqual(scanProgress({libraryId:'library',revision:1,sources:[source('complete',40)]}),{scanning:false,found:0});assert.deepEqual(scanProgress({libraryId:'library',revision:1,sources:[source('queued',3),source('running',7),source('complete',40)]}),{scanning:true,found:10});});
