import test from 'node:test';
import assert from 'node:assert/strict';
import {MediaAnalysisService,parseAnalysis,analysisInputUS,analysisInputSeconds,analysisMicroseconds,analysisSeekPosition,markerSkipPosition} from '../src/media-analysis.ts';
import type {PlaybackSnapshot} from '../src/index.ts';
const scope={serverId:'server',viewerId:'owner-profile'},target={libraryId:'library',itemId:'item',sessionId:'session',generation:2};
const id='a'.repeat(64),mapping='b'.repeat(64),preview='c'.repeat(64),wave='d'.repeat(64);
function data():any{return {scope:{serverId:'server',libraryId:'library',itemId:'item',viewerFence:'viewer-fence',sessionId:'session',sessionGeneration:2},sources:[{id:'asset',label:'Source 1'}],source:{id:'asset',revision:'revision',mappingRevision:mapping,durationUS:'60000000',needsProbe:false},canManage:true,policy:{tier:'complete',revision:1,operations:['probe','checksum','trickplay','waveform','segment_detection']},budgets:null,results:[{stage:'waveform',algorithm:'wave-1',originAssurance:'observed_acquisition',createdMS:10,summary:{},artifactId:wave}],markers:[{id,kind:'intro',title:'Intro candidate',startUS:'0',endUS:'10000000',confidence:0.3,provenance:'luminance_opening_boundary:v1',approved:false,edited:false}],markerRevision:1,previews:[{id:preview,kind:'trickplay',startUS:'0',endUS:'10000000',width:320,height:180}],jobs:[{jobId:'job',jobStatus:'running',stage:'trickplay',state:'running',attempt:1,processedBytes:'1000',errorCode:'',updatedMS:100}]};}
function player():PlaybackSnapshot{return {revision:1,intentId:1,seekRevision:0,phase:'ready',intent:'playing',itemId:'item',session:{id:'session',generation:2,duration:60,resumeSeconds:0,streamUrl:'private',mode:'direct'},positionSeconds:5,duration:60,cleanupPending:0,audio:{} as PlaybackSnapshot['audio']};}
function service(fn:(path:string,method?:string,body?:any,signal?:AbortSignal)=>Promise<unknown>,timeout=1000){return new MediaAnalysisService({request:<T>(p:string,m?:string,b?:unknown,s?:AbortSignal)=>fn(p,m,b,s) as Promise<T>},scope,target,timeout);}
function deferred(){let resolve!:(x:any)=>void;const promise=new Promise<any>(r=>resolve=r);return {promise,resolve};}
function artifact(kind='trickplay'):any{return {scope:data().scope,source:data().source,id:kind==='waveform'?wave:preview,kind,mime:kind==='waveform'?'application/json':'image/jpeg',data:'YWJj',document:{points:[{startUS:'0',endUS:'1000000',peak:.5,rms:.2}]}};}

test('strict immutable source and scope projection retains confidence but never approves it',()=>{const raw=data(),v=parseAnalysis(raw,scope,target);assert(Object.isFrozen(v));assert(Object.isFrozen(v.markers[0]));assert.equal(v.markers[0].approved,false);raw.source.revision='different';assert.equal(v.source.revision,'revision');});
test('rejects wrong server, library, item, session, generation, source and invalid time',()=>{for(const change of [(d:any)=>d.scope.serverId='other',(d:any)=>d.scope.libraryId='other',(d:any)=>d.scope.itemId='other',(d:any)=>d.scope.sessionId='other',(d:any)=>d.scope.sessionGeneration=3,(d:any)=>d.source.id='wrong',(d:any)=>d.source.durationUS='9007199254740992',(d:any)=>d.markers[0].endUS='70000000',(d:any)=>d.markers[0].confidence=NaN]){const d=data();change(d);assert.throws(()=>parseAnalysis(d,scope,{...target,sourceId:'asset'}));}});
test('rejects duplicate markers, unbounded previews and results on a target awaiting probe',()=>{for(const change of [(d:any)=>d.markers.push({...d.markers[0]}),(d:any)=>d.previews=Array(13).fill(d.previews[0]),(d:any)=>d.source.needsProbe=true]){const d=data();change(d);assert.throws(()=>parseAnalysis(d,scope,target));}});
test('decimal inputs round-trip exact microseconds and reject coercion',()=>{for(const [seconds,us]of [['0','0'],['0.000001','1'],['61.25','61250000'],['9007199254.740991','9007199254740991']]){assert.equal(analysisInputUS(seconds),us);assert.equal(analysisInputUS(analysisInputSeconds(us)),us);}for(const bad of ['-1','1e3','0.0000001','1.','NaN','01','Infinity','9007199254.740992'])assert.throws(()=>analysisInputUS(bad));assert(!analysisMicroseconds('01'));});
test('candidate and high confidence never authorize skip; explicit owner approval does',()=>{const raw=data();raw.markers[0].confidence=1;let v=parseAnalysis(raw,scope,target);assert.equal(markerSkipPosition(v,v.markers[0],player()),null);raw.markers[0].approved=true;v=parseAnalysis(raw,scope,target);assert.equal(markerSkipPosition(v,v.markers[0],player()),10);assert.equal(markerSkipPosition(v,v.markers[0],{...player(),positionSeconds:11}),null);assert.equal(markerSkipPosition(v,{...v.markers[0]},player()),null);});
test('seek is rejected for an inactive, changed or pending-seek playback session',()=>{const v=parseAnalysis(data(),scope,target);assert.equal(analysisSeekPosition(v,'1000000',player()),1);for(const p of [{...player(),phase:'starting'}, {...player(),itemId:'other'}, {...player(),session:{...player().session!,generation:3}}, {...player(),pendingSeek:{revision:2,positionSeconds:7}}])assert.equal(analysisSeekPosition(v,'1000000',p as PlaybackSnapshot),null);assert.equal(analysisSeekPosition(v,'60000001',player()),null);});
test('late ignored-abort refresh cannot replace newer data',async()=>{const a=deferred();let n=0;const s=service(async()=>++n===1?a.promise:{...data(),markerRevision:2});const old=s.refresh();await s.refresh();a.resolve(data());await old;assert.equal(s.getSnapshot().data!.markerRevision,2);s.dispose();});
test('dispose cancels and suppresses a late refresh',async()=>{const a=deferred();const s=service(()=>a.promise),pending=s.refresh();s.dispose();a.resolve(data());await pending;assert.equal(s.getSnapshot().data,null);});
test('bounded timeout settles even when an API ignores abort',async()=>{const s=service(()=>new Promise(()=>{}),5);await s.refresh();assert.equal(s.getSnapshot().busy,false);assert.match(s.getSnapshot().error,/timed out/);s.dispose();});
test('refresh pins the chosen variant instead of silently falling back',async()=>{const paths:string[]=[];let d=data();const s=service(async p=>{paths.push(p);return d;});await s.refresh();d={...data(),source:{...data().source,id:'replacement'},sources:[{id:'replacement',label:'Other'}]};await s.refresh();assert(paths[1].includes('sourceId=asset'));assert.equal(s.getSnapshot().data,null);s.dispose();});
test('changed viewer fence clears all displayed source data',async()=>{let d=data();const s=service(async()=>d);await s.refresh();d.scope.viewerFence='new';await s.refresh();assert.equal(s.getSnapshot().data,null);assert.match(s.getSnapshot().error,/permissions changed/);s.dispose();});
test('authenticated image requests include revisions and never receive a bearer URL',async()=>{let path='';const s=service(async p=>{path=p;return p.includes('/artifacts/')?artifact():data();});await s.refresh();await s.image(preview);assert(path.includes('sourceRevision=revision'));assert(path.includes('mappingRevision='+mapping));assert.equal(s.getSnapshot().image!.uri,'data:image/jpeg;base64,YWJj');assert(!path.includes('token='));s.dispose();});
test('cross-source artifact and non-image payload are rejected',async()=>{for(const change of [(a:any)=>a.source.revision='other',(a:any)=>a.scope.viewerFence='other',(a:any)=>a.mime='text/html']){const a=artifact();change(a);const s=service(async p=>p.includes('/artifacts/')?a:data());await s.refresh();await s.image(preview);assert.equal(s.getSnapshot().image,null);assert(s.getSnapshot().error);s.dispose();}});
test('stale image is discarded when a refresh changes the mapping',async()=>{const a=deferred();let d=data();const s=service(async p=>p.includes('/artifacts/')?a.promise:d);await s.refresh();const pending=s.image(preview);d.source.mappingRevision='e'.repeat(64);await s.refresh();a.resolve(artifact());await pending;assert.equal(s.getSnapshot().image,null);s.dispose();});
test('waveform validates bounded amplitudes and item-relative timestamps',async()=>{for(const bad of [false,true]){const a=artifact('waveform');if(bad)a.document.points[0].endUS='999999999';const s=service(async p=>p.includes('/artifacts/')?a:data());await s.refresh();await s.waveform();assert.equal(s.getSnapshot().waveform?.length??0,bad?0:1);s.dispose();}});
test('owner mutation carries CAS and ambiguous retry keeps the same receipt and payload',async()=>{const bodies:any[]=[];let fail=true;const s=service(async(_p,m,b)=>{if(m==='POST'){bodies.push(b);if(fail)throw new Error('Connection interrupted');return {markerRevision:2,markerId:id};}return data();});await s.refresh();await s.mutate({action:'approve',markerId:id});assert(s.getSnapshot().ambiguous);assert.equal(bodies[0].expectedRevision,1);assert.equal(bodies[0].mappingRevision,mapping);fail=false;await s.retryMarker();assert.deepEqual(bodies[0],bodies[1]);assert(!s.getSnapshot().ambiguous);s.dispose();});
test('definite conflict drops the receipt and requires refresh, never blindly retries',async()=>{let calls=0;const s=service(async(_p,m)=>{if(m==='POST'){calls++;throw Object.assign(new Error('Refresh'),{code:'analysis_conflict'});}return data();});await s.refresh();await s.mutate({action:'approve',markerId:id});assert(!s.getSnapshot().ambiguous);assert.equal(s.getSnapshot().data,null);await s.retryMarker();assert.equal(calls,1);s.dispose();});
test('read-only viewers cannot mutate, queue or control source jobs',async()=>{const s=service(async()=>({...data(),canManage:false}));await s.refresh();assert.throws(()=>s.queue());assert.throws(()=>s.mutate({action:'approve',markerId:id}));assert.throws(()=>s.control('job','cancel'));s.dispose();});
test('queue, job control and policy edits preserve saved source and policy revisions',async()=>{const bodies:any[]=[];const s=service(async(p,m,b)=>{if(m!=='GET'){bodies.push({p,m,b});return {};}return data();});await s.refresh();await s.queue();await s.control('job','pause');await s.policy('custom',['probe','waveform']);assert(bodies[0].p.endsWith('/jobs'));assert.equal(bodies[1].b.action,'pause');assert.equal(bodies[2].b.expectedRevision,1);for(const {b}of bodies)assert.equal(b.sourceRevision,'revision');s.dispose();});

test('equal duration is not permission to seek an original marker in prepared media',()=>{
 const raw=data();raw.markers[0].approved=true;
 const v=parseAnalysis(raw,scope,target),p=player();
 p.session={...p.session!,preparedVersionId:'prepared-version'};
 assert.equal(analysisSeekPosition(v,'1000000',p),null);
 assert.equal(markerSkipPosition(v,v.markers[0],p),null);
});
