import test from 'node:test';
import assert from 'node:assert/strict';
import {MetadataReviewService,type MetadataReviewTarget,type MetadataReviewApi} from '../src/metadata-review.ts';
const scope={serverId:'server',viewerId:'local/account/profile'};
const target:MetadataReviewTarget={kind:'show',libraryId:'library',entityId:'show'};
const mb='12345678-1234-1234-1234-123456789abc';
function tv(revision=1):any{return {serverId:'server',viewerFence:'fence',libraryId:'library',showId:'show',revision,status:'needs_order',providerId:2,order:'',page:0,attempts:0,nextAttempt:'',error:'',attribution:'TheTVDB',candidates:[{id:2,name:'Second',year:2020,overview:'Two\nlines',observedAt:'2026-09-05'},{id:1,name:'First',year:0,overview:'',observedAt:'2026-09-05'}],orders:['dvd','official'],actions:['select']};}
function music(kind='album'):any{return {serverId:'server',viewerFence:'fence',libraryId:'library',kind,entityId:kind,revision:1,status:'needs_selection',selectedId:'',manual:false,attempts:0,nextAttempt:'',error:'',attribution:'MusicBrainz',candidates:[{id:mb,title:'Album',artist:'Artist',edition:'Edition',confidence:0.5,reasons:['provider_name_search','owner_review_required','exact_title','exact_artist'],decision:'candidate',observedAt:'2026-09-05'}],actions:['select','retry','search']};}
function setup(fn:(p:string,m?:string,b?:any,s?:AbortSignal)=>Promise<any>,timeoutMs=1000){const api:MetadataReviewApi={request:<T>(p:string,m?:string,b?:unknown,s?:AbortSignal)=>fn(p,m,b,s) as Promise<T>};return new MetadataReviewService({api,scope,timeoutMs});}
function deferred(){let resolve!:(v:any)=>void;const promise=new Promise<any>(r=>{resolve=r;});return {promise,resolve};}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('TV evidence keeps server order, provenance and explicit choices immutable',async()=>{const s=setup(async()=>tv());await s.select(target);const d=s.getSnapshot().data!;assert.deepEqual(d.candidates.map(c=>c.id),['2','1']);assert.deepEqual(d.orders,['dvd','official']);assert.equal(d.candidates[0].overview,'Two\nlines');assert.equal(d.candidates[0].provenance.year,2020);assert.throws(()=>{(d.actions as any).push('search');});assert.throws(()=>s.choose('2'));assert.throws(()=>s.choose('999','dvd'));assert.throws(()=>s.searchAlternatives());});
test('selection uses captured exact CAS, numeric TV ID and authoritative subsequent read',async()=>{let state=tv();const writes:any[]=[];const s=setup(async(_p,m,b)=>{if(m==='GET')return state;writes.push(b);state={...state,revision:2,order:'dvd',status:'pending_episodes'};return {showId:'show',status:'pending_episodes'};});await s.select(target);await s.choose('2','dvd');assert.deepEqual(writes,[{expectedRevision:1,providerId:2,order:'dvd'}]);assert.equal(s.getSnapshot().data!.revision,2);assert.equal(s.getSnapshot().pending,null);});
test('duplicate pending command shares promise and competing choice is blocked',async()=>{const d=deferred();let writes=0;const s=setup(async(_p,m)=>m==='GET'?tv():(writes++,d.promise));await s.select(target);const a=s.choose('2','dvd');assert.equal(a,s.choose('2','dvd'));assert.throws(()=>s.choose('1','dvd'));d.resolve({showId:'show',status:'pending_episodes'});await a;assert.equal(writes,1);});
test('ambiguous write reconciles concurrent owner state without replay or silent overwrite',async()=>{let state=tv(),writes=0;const s=setup(async(_p,m)=>{if(m==='GET')return state;writes++;state={...tv(4),providerId:1,order:'official'};throw new Error('connection lost');});await s.select(target);await s.choose('2','dvd');assert.equal(s.getSnapshot().data!.selectedId,'1');assert.equal(s.getSnapshot().mutationError!.code,'request_failed');await s.reconcile();assert.equal(writes,1);assert.equal(s.getSnapshot().mutationError,null);assert.equal(s.getSnapshot().data!.selectedId,'1');});
test('CAS conflict refreshes current revision; only new explicit choice uses it',async()=>{let state=tv();const revisions:number[]=[];const s=setup(async(_p,m,b)=>{if(m==='GET')return state;revisions.push(b.expectedRevision);if(revisions.length===1){state=tv(3);throw Object.assign(new Error('changed'),{code:'metadata_conflict'});}return {showId:'show',status:'pending_episodes'};});await s.select(target);await s.choose('2','dvd');assert.equal(s.getSnapshot().mutationError!.code,'metadata_conflict');await s.choose('1','dvd');assert.deepEqual(revisions,[1,3]);});
test('denied mutation clears old evidence and does not fetch it again',async()=>{let reads=0;const s=setup(async(_p,m)=>{if(m==='GET'){reads++;return tv();}throw Object.assign(new Error('denied'),{code:'unauthorized'});});await s.select(target);await s.choose('2','dvd');assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,'error');assert.equal(reads,1);});
test('target and scope switches abort and ignore late reads',async()=>{const d=deferred();let signal:AbortSignal|undefined;const s=setup(async(p,_m,_b,a)=>{if(p.includes('/shows/')){signal=a;return d.promise;}return music();});const old=s.select(target);await s.select({kind:'album',libraryId:'library',entityId:'album'});await old;assert.equal(signal!.aborted,true);d.resolve(tv());await tick();assert.equal(s.getSnapshot().data!.provider,'musicbrainz');s.setScope({...scope,viewerId:'other'},{request:async<T>()=>music() as T});assert.equal(s.getSnapshot().data,null);});
test('late mutation cannot start a read for the new item',async()=>{const d=deferred();const paths:string[]=[];const s=setup(async(p,m)=>{paths.push(p);if(m!=='GET')return d.promise;return p.includes('/shows/')?tv():music();});await s.select(target);const old=s.choose('2','dvd');await s.select({kind:'album',entityId:'album',libraryId:'library'});await old;d.resolve({showId:'show',status:'pending_episodes'});await tick();assert.equal(paths.length,3);assert.equal(s.getSnapshot().data!.provider,'musicbrainz');});
test('bounded timeout works even when transport ignores abort',async()=>{const s=setup(async()=>new Promise(()=>{}),5);await s.select(target);assert.equal(s.getSnapshot().error!.code,'timeout');s.dispose();});
test('MB album and song routes preserve edition, selected provenance and explicit search/retry',async()=>{for(const kind of ['album','song'] as const){let state=music(kind);const calls:any[]=[];const s=setup(async(p,m,b)=>{calls.push([p,m,b]);if(m==='GET')return state;state={...state,revision:state.revision+1,status:'pending',selectedId:mb,manual:true};return {entityId:kind,status:'pending'};});await s.select({kind,entityId:kind,libraryId:'library'});assert.equal(s.getSnapshot().data!.candidates[0].provenance.edition,'Edition');await s.choose(mb);await s.searchAlternatives();await s.retryProvider();assert.equal(calls[0][0],`/v1/${kind==='album'?'albums':'items'}/${kind}/metadata/musicbrainz`);assert.deepEqual(calls.filter(c=>c[1]!=='GET').map(c=>c[2]),[{expectedRevision:1,providerId:mb},{expectedRevision:2},{expectedRevision:3}]);}});
test('malformed, oversized, wrong-scope and unknown status/action responses clear evidence',async()=>{for(const patch of [{serverId:'other'},{libraryId:'other'},{showId:'other'},{revision:1.5},{status:'invented'},{actions:['select','search']},{orders:['invented']},{candidates:Array(26).fill(tv().candidates[0])},{candidates:[tv().candidates[0],tv().candidates[0]]}]){const s=setup(async()=>({...tv(),...patch}));await s.select(target);assert.equal(s.getSnapshot().error!.code,'invalid_metadata_review');assert.equal(s.getSnapshot().data,null);}});
test('same-target older revision and changed fence cannot authorize another selection',async()=>{let state=tv(3);const s=setup(async()=>state);await s.select(target);state=tv(2);await s.refresh();assert.equal(s.getSnapshot().error!.code,'metadata_scope_changed');await s.select(target);state={...tv(4),viewerFence:'different'};await s.refresh();assert.equal(s.getSnapshot().data,null);assert.throws(()=>s.choose('2','dvd'));});

test('published music evidence remains distinct from candidates and rejects inconsistent track totals',async()=>{
 const published={releaseId:mb,releaseGroupId:mb,recordingId:'',trackId:'',title:'Selected edition',artist:'Provider artist',date:'2026',country:'CA',observedAt:'2026-09-05T00:00:00Z',trackTitle:'',trackStatus:'',reconciliationPending:true,totalTracks:3,matchedTracks:1,pendingTracks:1,reviewTracks:1};
 const s=setup(async()=>({...music(),published}));await s.select({kind:'album',entityId:'album',libraryId:'library'});
 assert.equal(s.getSnapshot().data!.published!.title,'Selected edition');assert.equal(s.getSnapshot().data!.candidates[0].title,'Album');assert.ok(Object.isFrozen(s.getSnapshot().data!.published));
 for(const patch of [{matchedTracks:3},{recordingId:'bad'},{pendingTracks:-1},{releaseId:''}]){const broken=setup(async()=>({...music(),published:{...published,...patch}}));await broken.select({kind:'album',entityId:'album',libraryId:'library'});assert.equal(broken.getSnapshot().error!.code,'invalid_metadata_review');}
});


test('MB current evidence is required, bounded and detached from caller mutation',async()=>{
 const value=music();const s=setup(async()=>value);await s.select({kind:'album',entityId:'album',libraryId:'library'});
 const c=s.getSnapshot().data!.candidates[0];assert.equal(c.confidence,0.5);assert.equal(c.decision,'candidate');assert.ok(Object.isFrozen(c.reasons));value.candidates[0].reasons.push('later');assert.equal(c.reasons!.length,4);
 for(const patch of [{confidence:undefined},{confidence:NaN},{confidence:1.1},{reasons:[]},{reasons:['duplicate','duplicate']},{reasons:Array(17).fill('reason')},{decision:'automatic'}]){
  const raw=music();Object.assign(raw.candidates[0],patch);const broken=setup(async()=>raw);await broken.select({kind:'album',entityId:'album',libraryId:'library'});assert.equal(broken.getSnapshot().error!.code,'invalid_metadata_review');
 }
});
test('MB continuation flag requires current payload and survives zero pending track counts',async()=>{
 const published={releaseId:mb,releaseGroupId:mb,recordingId:'',trackId:'',title:'Edition',artist:'Artist',date:'',country:'',observedAt:'2026-09-05',trackTitle:'',trackStatus:'',totalTracks:0,matchedTracks:0,pendingTracks:0,reviewTracks:0,reconciliationPending:true};
 const s=setup(async()=>({...music(),published}));await s.select({kind:'album',entityId:'album',libraryId:'library'});assert.equal(s.getSnapshot().data!.published!.reconciliationPending,true);
 for(const flag of [undefined,'true',0]){const broken=setup(async()=>({...music(),published:{...published,reconciliationPending:flag}}));await broken.select({kind:'album',entityId:'album',libraryId:'library'});assert.equal(broken.getSnapshot().error!.code,'invalid_metadata_review');}
});
