import test from 'node:test';import assert from 'node:assert/strict';import {PlayerChaptersService} from '../src/player-chapters.ts';
const scope={serverId:'server',viewerId:'local-owner-profile'},target={libraryId:'library',itemId:'item',sessionId:'session',sessionGeneration:2};
function data(page=0):any{return {scope:{serverId:'server',libraryId:'library',itemId:'item',sessionId:'session',generation:2,sourceId:'source',viewerFence:'fence'},revision:'revision',status:'available',reason:null,duration:60,chapters:[{id:'source:'+(page+1),index:page+1,title:'Chapter '+(page+1),startSeconds:page*30,endSeconds:(page+1)*30,action:{id:'seek',positionSeconds:page*30}}],totalCount:2,nextCursor:page===0?'cursor2':''};}
function service(fn:(p:string)=>Promise<unknown>,timeoutMs=1000){return new PlayerChaptersService({scope,pageSize:1,timeoutMs,api:{request:<T>(p:string,m?:string,b?:unknown)=>{assert.equal(m,'GET');assert.equal(b,undefined);return fn(p) as Promise<T>;}}});}
function deferred(){let resolve!:(v:unknown)=>void;const promise=new Promise<unknown>(r=>resolve=r);return {resolve:(v:unknown)=>resolve(v),promise};}
test('one bounded source-local page with exact seek positions and fenced Next/Previous',async()=>{const requests:string[]=[],s=service(async p=>{requests.push(p);return data(new URL('http://local'+p).searchParams.has('cursor')?1:0);});await s.select(target);assert.equal(s.getSnapshot().target!.sourceId,'source');await s.next();assert.equal(s.getSnapshot().data!.chapters[0].action.positionSeconds,30);assert(requests[1].includes('revision=revision'));assert.equal(s.getSnapshot().data!.chapters.length,1);await s.previous();assert.equal(s.getSnapshot().data!.chapters[0].index,1);assert.equal(s.getSnapshot().pagination.canPrevious,false);s.dispose();});
test('legacy unavailable and no chapters never offer seek rows',async()=>{for(const [status,reason] of [['unavailable','session_source_unverified'],['unavailable','session_inactive'],['unavailable','prepared_chapter_mapping_unavailable'],['none',null]]){const d={...data(),status,reason,chapters:[],totalCount:0,nextCursor:''};const s=service(async()=>d);await s.select(target);assert.equal(s.getSnapshot().phase,'ready');assert.equal(s.getSnapshot().data!.chapters.length,0);s.dispose();}});
test('reject wrong session/source/generation, duplicate IDs, overlapping or invalid timestamps and action mismatch',async()=>{for(const mutate of [(d:any)=>d.scope.sessionId='wrong',(d:any)=>d.scope.generation=3,(d:any)=>d.scope.libraryId='wrong',(d:any)=>d.chapters[0].startSeconds=-1,(d:any)=>d.chapters[0].endSeconds=61,(d:any)=>d.chapters[0].action.positionSeconds=10,(d:any)=>d.chapters[0].startSeconds=Infinity,(d:any)=>d.status='none']){const d=data();mutate(d);const s=service(async()=>d);await s.select(target);assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,'error');s.dispose();}const s=new PlayerChaptersService({scope,api:{request:async<T>()=>({...data(),chapters:[data().chapters[0],{...data().chapters[0],index:2}],nextCursor:''}) as T}});await s.select(target);assert.equal(s.getSnapshot().data,null);s.dispose();});
test('continuation revision/total/source changes and cursor loops offer no stale choices',async()=>{for(const mutate of [(d:any)=>d.revision='new',(d:any)=>d.scope.sourceId='new',(d:any)=>d.totalCount=3,(d:any)=>d.nextCursor='cursor2']){let d=data();const s=service(async()=>d);await s.select(target);d=data(1);mutate(d);await s.next();assert.equal(s.getSnapshot().data,null);assert(['error','refresh-required'].includes(s.getSnapshot().phase));s.dispose();}});
test('server stale error retains retry revision, refresh restarts without cursor while keeping source pin',async()=>{const requests:string[]=[];let fail=false;const s=service(async p=>{requests.push(p);if(fail)throw Object.assign(new Error('Stale'),{code:'stale_chapter_projection'});return data();});await s.select(target);fail=true;await s.next();assert.equal(s.getSnapshot().phase,'refresh-required');await s.retry();assert(requests[2].includes('cursor=cursor2'));fail=false;await s.refresh();assert(!requests[3].includes('cursor='));assert.equal(s.getSnapshot().target!.sourceId,'source');s.dispose();});
test('same query singleflight and newer session wins ignored abort response',async()=>{const old=deferred();let calls=0;const s=service(async p=>{calls++;if(p.includes('/session/'))return old.promise;const d=data();d.scope.sessionId='new';return d;});const a=s.select(target);assert.equal(a,s.select(target));await s.select({...target,sessionId:'new'});old.resolve(data());await a;assert.equal(calls,2);assert.equal(s.getSnapshot().data!.scope.sessionId,'new');s.dispose();});
test('cancel, changed scope, permission denial and bounded timeout clear chapter choices',async()=>{for(const action of ['cancel','scope']){const d=deferred(),s=service(()=>d.promise);const p=s.select(target);if(action==='cancel')s.cancel();else s.setScope({...scope,viewerId:'new'},{request:async<T>()=>data() as T});d.resolve(data());await p;assert.equal(s.getSnapshot().phase,'idle');s.dispose();}let deny=false;const s=service(async()=>{if(deny)throw Object.assign(new Error('sensitive'),{status:403});return data();});await s.select(target);deny=true;await s.refresh();assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().error!.code,'forbidden');assert(!JSON.stringify(s.getSnapshot()).includes('sensitive'));s.dispose();const timed=service(()=>new Promise(()=>{}),5);await timed.select(target);assert.equal(timed.getSnapshot().error!.code,'timeout');timed.dispose();});
test('history is capped at64 while rendering only one page; distinct overlapping chapters rejected',async()=>{const s=service(async path=>{const cursor=new URL('http://local'+path).searchParams.get('cursor'),i=cursor?Number(cursor.slice(1)):0;return {...data(),duration:70,totalCount:70,nextCursor:i<69?'c'+(i+1):'',chapters:[{id:'source:'+(i+1),index:i+1,title:'Chapter '+(i+1),startSeconds:i,endSeconds:i+1,action:{id:'seek',positionSeconds:i}}]};});await s.select(target);for(let i=0;i<66;i++)await s.next();let back=0;while(s.getSnapshot().pagination.canPrevious){await s.previous();back++;}assert.equal(back,64);assert.equal(s.getSnapshot().data!.chapters[0].index,3);s.dispose();const d=data();d.nextCursor='';d.chapters.push({...d.chapters[0],id:'source:2',index:2,startSeconds:20,endSeconds:60,action:{id:'seek',positionSeconds:20}});const bad=new PlayerChaptersService({scope,api:{request:async<T>()=>d as T}});await bad.select(target);assert.equal(bad.getSnapshot().data,null);bad.dispose();});

test('chapter thumbnails are optional and must be this item\'s own image path',async()=>{
 const withThumb=data();withThumb.nextCursor='';withThumb.totalCount=1;withThumb.chapters[0].thumbnailUrl='/v1/items/item/chapters/source:1/image';
 const s=service(async()=>withThumb);await s.select(target);
 assert.equal(s.getSnapshot().data!.chapters[0].thumbnailUrl,'/v1/items/item/chapters/source:1/image');
 s.dispose();
 const without=data();without.nextCursor='';without.totalCount=1;
 const plain=service(async()=>without);await plain.select(target);
 assert.equal(plain.getSnapshot().data!.chapters[0].thumbnailUrl,undefined);
 plain.dispose();
 for(const url of ['https://elsewhere.example/a.jpg','/v1/items/other/chapters/source:1/image','/v1/items/item/chapters/source:2/image','/v1/items/item/art/poster','',1]){
  const d=data();d.nextCursor='';d.totalCount=1;d.chapters[0].thumbnailUrl=url;
  const bad=service(async()=>d);await bad.select(target);
  assert.equal(bad.getSnapshot().data,null,String(url));
  assert.equal(bad.getSnapshot().phase,'error');
  bad.dispose();
 }
});
