import test from 'node:test';import assert from 'node:assert/strict';import {validateRelatedMovies} from '../src/related-movies.ts';import {DetailService} from '../src/detail.ts';
const target={libraryId:'lib',itemId:'source',kind:'movie'};
const row=()=>({id:'genre:tmdb:16',relation:'genre',provider:'tmdb',evidenceId:'16',heading:'More Animation movies',entries:[{id:'related',libraryId:'lib',kind:'movie',title:'Related',available:true,navigation:{view:'item',entityId:'related'}}]});
const related=()=>({version:1,libraryId:'lib',libraryName:'Movies',rows:[row()]});
const detail=(id='source')=>({scope:{serverId:'server',libraryId:'lib',itemId:id,viewerFence:'fence'},revision:{catalog:2,viewer:0},item:{id,libraryId:'lib',kind:'movie',title:id,available:true,duration:10,progressSeconds:0},personal:{revision:0,watchlisted:false,favorite:false,rating:null},metadata:{status:'available',ratings:[],genres:[],credits:[]},actions:[],related:related()});
test('related movie service preserves server labels/order as immutable navigation targets',()=>{const p=validateRelatedMovies(related(),target);assert.equal(p.rows[0].heading,'More Animation movies');assert.ok(Object.isFrozen(p.rows[0].entries));assert.throws(()=>validateRelatedMovies({...related(),libraryId:'denied'},target));for(const patch of [{id:'source'},{libraryId:'other'},{kind:'song'},{available:false},{navigation:{view:'item',entityId:'other'}},{playback:{itemId:'related'}}])assert.throws(()=>validateRelatedMovies({...related(),rows:[{...row(),entries:[{...row().entries[0],...patch}]}]},target));assert.throws(()=>validateRelatedMovies({...related(),rows:Array(4).fill(row())},target));assert.throws(()=>validateRelatedMovies({...related(),rows:[{...row(),entries:Array(13).fill(row().entries[0])}]},target));});
test('older catalog or new viewer fence clears related targets on refresh; denial cannot retain cards',async()=>{for(const patch of [{revision:{catalog:1,viewer:0}},{scope:{serverId:'server',libraryId:'lib',itemId:'source',viewerFence:'changed'}},null]){let current:any=detail();const api={request:async<T>()=>{if(current===null)throw Object.assign(new Error('Access denied'),{code:'unauthorized'});return current as T}};const s=new DetailService({api,scope:{serverId:'server',viewerId:'viewer'},requestId:async()=>''});await s.select(target);current=patch===null?null:{...detail(),...patch};await s.refresh();assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,'error');s.dispose();}});
test('late related detail cannot replace another selected movie',async()=>{let resolve!:(v:any)=>void;const old=new Promise<any>(r=>resolve=r);const api={request:async<T>(path:string)=>path.includes('/source/')?old as Promise<T>:detail('new') as T};const s=new DetailService({api,scope:{serverId:'server',viewerId:'viewer'},requestId:async()=>''});const pending=s.select(target);await s.select({libraryId:'lib',itemId:'new'});resolve(detail());await pending;assert.equal(s.getSnapshot().data!.item.id,'new');s.dispose();});

test('related music and book rows preserve real entity navigation with strict family boundaries',()=>{
 for(const [kind,relation,entryKind,view] of [['song','album','album','album'],['song','artist','album','album'],['audiobook_file','book','book','book'],['audiobook_file','author','book','book']]){
  const projection={version:1,libraryId:'lib',libraryName:'Listening',rows:[{id:`${relation}:local:identity`,relation,provider:'local',evidenceId:'identity',heading:'More from this library',entries:[{id:'other',kind:entryKind,libraryId:'lib',title:'Related',available:true,navigation:{view,entityId:'other'}}]}]};
  assert.equal(validateRelatedMovies(projection,{...target,kind}).rows[0].entries[0].kind,entryKind);
  assert.throws(()=>validateRelatedMovies(projection,target));
  assert.throws(()=>validateRelatedMovies({...projection,rows:[{...projection.rows[0],entries:[{...projection.rows[0].entries[0],libraryId:'private'}]}]},{...target,kind}));
  assert.throws(()=>validateRelatedMovies({...projection,rows:[{...projection.rows[0],entries:[{...projection.rows[0].entries[0],navigation:{view:'item',entityId:'wrong'}}]}]},{...target,kind}));
 }
});

test('related discovery rejects playable child cards and accepts whole shows',()=>{
 const projection={version:1,libraryId:'lib',libraryName:'TV',rows:[{id:'show:local:seed',relation:'show',provider:'local',evidenceId:'seed',heading:'More shows',entries:[{id:'other',kind:'show',libraryId:'lib',title:'Related',available:true,navigation:{view:'show',entityId:'other'}}]}]};
 assert.equal(validateRelatedMovies(projection,{...target,kind:'episode'}).rows[0].entries[0].kind,'show');
 for(const [kind,relation,child] of [['episode','show','episode'],['song','album','song'],['audiobook_file','book','audiobook_file']]){const r={...projection.rows[0],id:`${relation}:local:seed`,relation,entries:[{...projection.rows[0].entries[0],kind:child,navigation:{view:'item',entityId:'other'}}]};assert.throws(()=>validateRelatedMovies({...projection,rows:[r]},{...target,kind}));}
});
