import test from 'node:test';
import assert from 'node:assert/strict';
import {MetadataReviewService,type MetadataReviewApi,type MetadataReviewTarget} from '../src/metadata-review.ts';
const scope={serverId:'server',viewerId:'account/profile'};
const target:MetadataReviewTarget={kind:'movie',libraryId:'lib',entityId:'movie'};
const key='a'.repeat(64);
function state(revision=1):any{return {serverId:'server',viewerFence:'fence',libraryId:'lib',entityId:'movie',kind:'item',revision,selectionRevision:1,status:'needs_selection',explanation:'Review candidates',selected:{provider:'',type:'',id:''},selectionMode:'none',order:'',acceptedAt:'',acceptedConfidence:0,candidates:[{key,provider:'tmdb',type:'movie',providerId:'42',title:'Fixture',year:2020,overview:'Overview',format:'',confidence:.92,strongSignals:2,contradiction:false,reasons:['exact_title_or_alias','release_year_agrees'],observedAt:'2026-09-06T00:00:00Z',sourceKind:'search',sourceUrl:'https://www.themoviedb.org/movie/42',attribution:'TMDB',orders:[]}],actions:['select','search','retry','policy'],attempts:0,nextAttempt:'',error:'',attribution:'TMDB',policy:{libraryId:'lib',libraryKind:'movie',revision:2,consentRevision:3,confirmed:true,enabled:true,providers:['tmdb','tvdb'],availableProviders:['tmdb','tvdb'],language:'en-US',region:'CA',refreshMode:'replace_unlocked',disclosure:'Titles and IDs are sent to selected providers.',disclosureVersion:'screen-metadata-v1'},fields:[],localIssues:[],seasons:[],parentId:'',episodeStatus:''};}
function service(fn:(path:string,method:string,body:any)=>Promise<any>):MetadataReviewService{return new MetadataReviewService({scope,api:{request:<T>(p:string,m='GET',b?:unknown)=>fn(p,m,b) as Promise<T>} as MetadataReviewApi});}
test('movie review uses typed observed key and current revision, not numeric legacy selection',async()=>{const calls:any[]=[];let revision=1;const s=service(async(p,m,b)=>{calls.push([p,m,b]);if(m==='GET')return state(revision);revision++;return {entityId:'movie',status:'pending'};});await s.select(target);await s.choose(key);assert.deepEqual(calls[1],['/v1/items/movie/metadata/screen','PUT',{expectedRevision:1,candidateKey:key,order:''}]);assert.equal(s.getSnapshot().data?.revision,2);s.dispose();});
test('provider-specific searches and disclosure settings send independent CAS revisions',async()=>{const calls:any[]=[];const s=service(async(p,m,b)=>{calls.push([p,m,b]);return m==='GET'?state():p.includes('/libraries/')?{libraryId:'lib',status:'pending'}:{entityId:'movie',status:'pending'};});await s.select(target);await s.searchScreen('tvdb','Alternate title');await s.updateScreenPolicy({enabled:true,providers:['tvdb','tmdb'],language:'fr-CA',region:'CA',refreshMode:'fill_missing',confirmRemote:true,disclosureVersion:'screen-metadata-v1'});assert.deepEqual(calls[1][2],{provider:'tvdb',query:'Alternate title',expectedRevision:1});const policy=calls.find(c=>c[0].includes('/libraries/'));assert.equal(policy[1],'PUT');assert.equal(policy[2].expectedRevision,2);assert.equal(policy[2].expectedConsentRevision,3);assert.equal(policy[2].confirmRemote,true);s.dispose();});
test('bad scope, untyped AniList episode, hostile attribution and malformed evidence are rejected',async()=>{for(const patch of [(v:any)=>{v.serverId='other';},(v:any)=>{v.candidates[0].provider='anilist';v.candidates[0].type='episode';},(v:any)=>{v.candidates[0].sourceUrl='https://evil.example/';},(v:any)=>{v.candidates[0].confidence=1.1;},(v:any)=>{v.candidates[0].providerId='0042';},(v:any)=>{v.policy.providers=['tmdb','tmdb'];}]){const raw=state();patch(raw);const s=service(async()=>raw);await s.select(target);assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,'error');s.dispose();}});
test('lost screen selection response reconciles once without replaying a mutation',async()=>{let writes=0,reads=0;const s=service(async(_p,m)=>{if(m==='GET'){reads++;return state(reads);}writes++;throw new Error('Connection lost');});await s.select(target);await s.choose(key);assert.equal(writes,1);assert.equal(reads,2);assert.equal(s.getSnapshot().data?.revision,2);assert.ok(s.getSnapshot().mutationError);s.dispose();});
test('accepted anime work remains separate from alternative candidates and season mapping',async()=>{const raw=state();Object.assign(raw,{entityId:'show',kind:'show',order:'seasonal',selected:{provider:'anilist',type:'anime',id:'1'},accepted:{identity:{provider:'anilist',type:'anime',id:'1'},title:'Accepted season',relations:[{kind:'sequel',target:{provider:'anilist',type:'anime',id:'2'},name:'Next'}],orders:[{id:'seasonal',name:'Seasonal'}]},acceptedAt:'2026-09-06T01:00:00Z',actions:['retry','search','policy','map_season'],seasons:[{number:2,anilistId:'',revision:0}]});raw.policy.libraryKind='anime';raw.policy.providers=['anilist'];raw.policy.availableProviders=['anilist','tmdb','tvdb'];let command:any;const s=service(async(p,m,b)=>{if(m==='GET')return raw;command=[p,m,b];return {entityId:'show',status:'pending'};});await s.select({kind:'show',provider:'screen',libraryId:'lib',entityId:'show'});assert.equal(s.getSnapshot().data?.screen?.accepted?.identity.id,'1');assert.equal(s.getSnapshot().data?.candidates[0].screen?.identity.id,'42');await s.mapAnimeSeason(2,'2');assert.deepEqual(command,['/v1/shows/show/metadata/screen/season','PUT',{season:2,anilistId:'2',expectedRevision:1}]);s.dispose();});
