import test from 'node:test';import assert from 'node:assert/strict';import {PlaybackService,type PlaybackApi} from '../src/index.ts';
const tick=()=>new Promise(r=>setImmediate(r));
function setup(resume=12,seekTimeoutMs=1000){let created=0;const progress:any[]=[];const api:PlaybackApi={createPlayback:async()=>({id:'s'+(++created),generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:resume}),stopPlayback:async()=>{},progressPlayback:async(id,p)=>{progress.push({id,...p});}};const service=new PlaybackService(api,()=>String(created),{seekTimeoutMs});return {service,progress,created:()=>created};}
async function started(){const x=setup();await x.service.play('movie');const s=x.service.getSnapshot();x.service.ready(s.intentId);assert(x.service.seekApplied(s.intentId,s.pendingSeek!.revision,12,'playing'));await tick();x.progress.length=0;return x;}
test('startup resume is pending, never observed or checkpointed until explicit correlated ack',async()=>{const {service:s,progress}=setup(90);await s.play('book');assert.equal(s.getSnapshot().positionSeconds,0);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,90);s.ready(s.getSnapshot().intentId);s.fact(s.getSnapshot().intentId,0,'paused');assert(s.getSnapshot().pendingSeek);s.pause();s.leave();await tick();assert.equal(progress.length,0);});
test('requested seek90 then pause/leave persists only observed12 and preserves pause intent',async()=>{const {service:s,progress}=await started();s.seek(90);assert.equal(s.getSnapshot().positionSeconds,12);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,90);s.pause();s.leave();await tick();assert(progress.length>0);assert(progress.every(p=>p.positionSeconds===12));assert.equal(s.getSnapshot().pendingSeek,undefined);});
test('newer seek supersedes old ack/failure, invalid/clamped ack cannot succeed',async()=>{const {service:s}=await started();s.pause();s.seek(20);const old=s.getSnapshot();s.seek(70);const latest=s.getSnapshot();assert.equal(s.seekApplied(old.intentId,old.pendingSeek!.revision,20,'paused'),false);s.seekFailed(old.intentId,old.pendingSeek!.revision,'old');for(const value of [NaN,Infinity,-1,65,121])assert.equal(s.seekApplied(latest.intentId,latest.pendingSeek!.revision,value,'paused'),false);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,70);assert.equal(s.seekApplied(latest.intentId,latest.pendingSeek!.revision,70.1,'paused'),true);assert.equal(s.getSnapshot().positionSeconds,70.1);assert.equal(s.getSnapshot().intent,'paused');assert.equal(s.getSnapshot().pendingSeek,undefined);assert.equal(s.seekApplied(latest.intentId,latest.pendingSeek!.revision,70,'paused'),false);s.leave();});
test('ordinary fact during pending seek cannot alter settled position or acknowledge request',async()=>{const {service:s}=await started();s.seek(50);s.fact(s.getSnapshot().intentId,13,'playing');assert.equal(s.getSnapshot().positionSeconds,12);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,50);s.seekFailed(s.getSnapshot().intentId,s.getSnapshot().pendingSeek!.revision,'Unavailable target');assert.equal(s.getSnapshot().phase,'ready');assert.equal(s.getSnapshot().intent,'paused');assert.equal(s.getSnapshot().positionSeconds,12);s.leave();});
test('initial resume failure pauses without overwriting bookmark; explicit retry acknowledgment unlocks progress',async()=>{const {service:s,progress}=setup(90);await s.play('book');s.ready(s.getSnapshot().intentId);const first=s.getSnapshot();s.seekFailed(first.intentId,first.pendingSeek!.revision,'Target unavailable');assert.equal(s.getSnapshot().intent,'paused');s.fact(first.intentId,0,'paused');s.pause();await tick();assert.equal(progress.length,0);s.seek(90);const second=s.getSnapshot();assert(s.seekApplied(second.intentId,second.pendingSeek!.revision,90,'paused'));await tick();assert.equal(progress.at(-1).positionSeconds,90);assert.equal(s.getSnapshot().seekError,undefined);s.leave();});
test('bounded timeout is nonfatal and late callbacks cannot alter replacement intent',async()=>{const {service:s,progress}=setup(80,5);await s.play('book');s.ready(s.getSnapshot().intentId);const old=s.getSnapshot();await new Promise(r=>setTimeout(r,12));assert.equal(s.getSnapshot().phase,'ready');assert.equal(s.getSnapshot().pendingSeek,undefined);assert(s.getSnapshot().seekError);assert.equal(s.getSnapshot().intent,'paused');s.leave();await s.play('new',0);const fresh=s.getSnapshot();assert.equal(s.seekApplied(old.intentId,old.pendingSeek!.revision,80,'paused'),false);s.seekFailed(old.intentId,old.pendingSeek!.revision,'Stale');assert.equal(s.getSnapshot().pendingSeek!.revision,fresh.pendingSeek!.revision);s.leave();await tick();assert.equal(progress.length,0);});
test('same-position seek is explicitly acknowledged; invalid commands and terminal failure do not create seeks',async()=>{const {service:s}=await started();const before=s.getSnapshot().seekRevision;s.seek(NaN);assert.equal(s.getSnapshot().seekRevision,before);s.seek(12);const next=s.getSnapshot();assert(s.seekApplied(next.intentId,next.pendingSeek!.revision,12,'playing'));s.seek(30);s.fail(next.intentId,'Media failed');assert.equal(s.getSnapshot().pendingSeek,undefined);s.seek(50);assert.equal(s.getSnapshot().pendingSeek,undefined);s.leave();});

test('synchronous adapter failure retains the exact failed target, independent of renderer timing',async()=>{const {service:s}=await started();s.seek(10);let snap=s.getSnapshot();assert(s.seekApplied(snap.intentId,snap.pendingSeek!.revision,10,'paused'));const detach=s.attachAdapter({apply(next){if(next.pendingSeek?.positionSeconds===20){try{throw new Error('Setter rejected');}catch{s.seekFailed(next.intentId,next.pendingSeek.revision,'Try again.');}}}});s.seek(20);assert.equal(s.getSnapshot().positionSeconds,10);assert.equal(s.getSnapshot().failedSeek!.positionSeconds,20);assert.equal(s.getSnapshot().pendingSeek,undefined);detach();s.seek(s.getSnapshot().failedSeek!.positionSeconds);snap=s.getSnapshot();assert.equal(snap.failedSeek,undefined);assert(s.seekApplied(snap.intentId,snap.pendingSeek!.revision,20,'paused'));assert.equal(s.getSnapshot().failedSeek,undefined);s.leave();});

test('Play after protected startup failure retries original target before progress is unlocked',async()=>{const {service:s,progress}=setup(90);await s.play('book');s.ready(s.getSnapshot().intentId);const first=s.getSnapshot();s.seekFailed(first.intentId,first.pendingSeek!.revision,'Not available');s.resume();const retry=s.getSnapshot();assert.equal(retry.intent,'playing');assert.equal(retry.pendingSeek!.positionSeconds,90);assert.equal(retry.positionSeconds,0);s.fact(retry.intentId,1,'playing');await tick();assert.equal(progress.length,0);assert(s.seekApplied(retry.intentId,retry.pendingSeek!.revision,90,'paused'));s.fact(retry.intentId,94,'playing');await tick();assert.equal(progress.at(-1).positionSeconds,94);s.leave();});


test('engine loss restores settled observation rather than interrupted target and repeated loss stays safe',async()=>{const {service:s,progress}=await started();s.fact(s.getSnapshot().intentId,30,'playing');s.seek(90);s.fact(s.getSnapshot().intentId,96,'ended');s.engineLost(s.getSnapshot().intentId);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,30);s.engineLost(s.getSnapshot().intentId);assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,30);const restore=s.getSnapshot();s.fact(restore.intentId,0,'paused');assert.equal(s.getSnapshot().positionSeconds,30);assert(s.seekApplied(restore.intentId,restore.pendingSeek!.revision,30,'paused'));s.leave();await tick();assert(!progress.some(p=>p.positionSeconds===0||p.positionSeconds===96));});
test('ordinary clamped failure pauses, blocks observations and Play explicitly retries target',async()=>{const {service:s,progress}=await started();s.seek(60);const request=s.getSnapshot();s.seekFailed(request.intentId,request.pendingSeek!.revision,'Unavailable');s.fact(request.intentId,96,'ended');assert.equal(s.getSnapshot().intent,'paused');assert.equal(s.getSnapshot().positionSeconds,12);assert.equal(s.getSnapshot().phase,'ready');s.resume();assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,60);s.leave();await tick();assert(!progress.some(p=>p.positionSeconds===96));});

test('deferred recovery is inert until committed and starts only once',async()=>{let loads=0;const s=new PlaybackService({createPlayback:async()=>{throw Error('not used');},stopPlayback:async()=>{},progressPlayback:async()=>{}} as any,()=> 'id',{deferRecovery:true,journal:{load:async()=>{loads++;return[];},save:async()=>{}}});assert.equal(loads,0);await Promise.all([s.startRecovery(),s.startRecovery()]);assert.equal(loads,1);s.leave();});
test('Close during request journal save prevents obsolete server creation',async()=>{let release!:()=>void,creates=0;const s=new PlaybackService({createPlayback:async()=>{creates++;throw Error('must not create');},stopPlayback:async()=>{},progressPlayback:async()=>{}} as any,()=> 'id',{journal:{load:async()=>[],save:async()=>{await new Promise<void>(r=>release=r);}}});const pending=s.play('movie');await tick();s.leave();release();await pending;assert.equal(creates,0);});


test('fatal retry retains timed-out target and paused intent without checkpointing it before acknowledgement',async()=>{
 const {service:s,progress,created}=await started();s.pause();s.seek(84);const old=s.getSnapshot();s.seekFailed(old.intentId,old.pendingSeek!.revision,'Unavailable');s.fail(old.intentId,'Network budget exhausted');s.fail(old.intentId,'Repeated network error');await s.retry();const next=s.getSnapshot();assert.equal(created(),2);assert.notEqual(next.session!.id,old.session!.id);assert.equal(next.intent,'paused');assert.equal(next.pendingSeek!.positionSeconds,84);assert.equal(next.positionSeconds,0);s.fact(next.intentId,84,'paused');await tick();assert(!progress.some(p=>p.positionSeconds===84));assert(!s.seekApplied(old.intentId,old.pendingSeek!.revision,84,'paused'));s.ready(next.intentId);assert(s.seekApplied(next.intentId,next.pendingSeek!.revision,84,'paused'));await tick();assert.equal(progress.at(-1).positionSeconds,84);assert.equal(s.getSnapshot().intent,'paused');s.leave();await tick();
});
test('fatal retry retains active playing target while ordinary Play and replacement intent discard stale retry',async()=>{
 const {service:s}=await started();s.seek(70);s.fail(s.getSnapshot().intentId,'Network lost');await s.retry();assert.equal(s.getSnapshot().intent,'playing');assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,70);s.fail(s.getSnapshot().intentId,'Again');await s.play('other',0);assert.equal(s.getSnapshot().intent,'playing');assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,0);await s.retry();assert.equal(s.getSnapshot().itemId,'other');s.leave();
});


test('fatal Retry target and pause survive a failed replacement create and another Retry',async()=>{
 let creates=0;const s=new PlaybackService({createPlayback:async()=>{if(++creates===2)throw Error('Offline');return{id:'s'+creates,generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:12};},stopPlayback:async()=>{},progressPlayback:async()=>{}},()=>String(creates),{seekTimeoutMs:1000});
 await s.play('movie');let n=s.getSnapshot();s.ready(n.intentId);s.seekApplied(n.intentId,n.pendingSeek!.revision,12,'playing');s.pause();s.seek(84);s.fail(s.getSnapshot().intentId,'Fatal');await s.retry();assert.equal(s.getSnapshot().phase,'error');await s.retry();n=s.getSnapshot();assert.equal(n.pendingSeek!.positionSeconds,84);assert.equal(n.intent,'paused');s.leave();
});
test('explicit start-over playing intent survives create failure and early fatal callback without a session',async()=>{
 let count=0;const s=new PlaybackService({createPlayback:async()=>{if(++count===1)throw Error('Offline');return{id:'s'+count,generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:99};},stopPlayback:async()=>{},progressPlayback:async()=>{}},()=>String(count));await s.play('movie',0);assert.equal(s.getSnapshot().phase,'error');await s.retry();assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,0);assert.equal(s.getSnapshot().intent,'playing');s.leave();
});
test('fatal Retry target survives replacement startup timeout before a session is received',async()=>{
 let count=0,release!:(v:any)=>void;const s=new PlaybackService({createPlayback:async()=>{const id='s'+(++count);if(count===2)return new Promise(r=>release=r);return{id,generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:12};},stopPlayback:async()=>{},progressPlayback:async()=>{}},()=>String(count),{startupTimeoutMs:15,seekTimeoutMs:1000});await s.play('movie');let n=s.getSnapshot();s.ready(n.intentId);s.seekApplied(n.intentId,n.pendingSeek!.revision,12,'playing');s.pause();s.seek(84);s.fail(s.getSnapshot().intentId,'Fatal');const attempt=s.retry();await new Promise(r=>setTimeout(r,25));assert.equal(s.getSnapshot().phase,'error');release({id:'s2',generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:12});await attempt;await s.retry();n=s.getSnapshot();assert.equal(n.pendingSeek!.positionSeconds,84);assert.equal(n.intent,'paused');s.leave();
});


test('latest paused seek during initial readiness survives startup timeout and fatal Retry',async()=>{
 let creates=0;const s=new PlaybackService({createPlayback:async()=>({id:'s'+(++creates),generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:12}),stopPlayback:async()=>{},progressPlayback:async()=>{}},()=>String(creates),{startupTimeoutMs:15,seekTimeoutMs:1000});await s.play('movie',0);s.pause();s.seek(84);await new Promise(r=>setTimeout(r,25));assert.equal(s.getSnapshot().phase,'error');await s.retry();assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,84);assert.equal(s.getSnapshot().intent,'paused');s.leave();
});
test('Pause during a pending create survives that create failure and error Retry',async()=>{
 let creates=0,reject!:(e:Error)=>void;const s=new PlaybackService({createPlayback:async()=>{if(++creates===1)return new Promise((_,r)=>reject=r);return{id:'s'+creates,generation:1,streamUrl:'/media',mode:'direct',duration:120,resumeSeconds:12};},stopPlayback:async()=>{},progressPlayback:async()=>{}},()=>String(creates));const pending=s.play('movie',0);await tick();s.pause();reject(Error('Offline'));await pending;await s.retry();assert.equal(s.getSnapshot().pendingSeek!.positionSeconds,0);assert.equal(s.getSnapshot().intent,'paused');s.leave();
});
