import test from 'node:test';import assert from 'node:assert/strict';
import {ShowWorkspaceService,type ShowWorkspaceRoute,validateShowWorkspaceRoute} from '../src/show-workspace.ts';
import type {LibraryContentApi} from '../src/library-content.ts';
const scope={serverId:'server',viewerId:'hosted/account/profile'},route:ShowWorkspaceRoute={libraryId:'library',showId:'show'};
function dto(options:{season?:string|null;group?:boolean;episode?:string;entries?:string[];next?:string;rev?:number;seasons?:string[];nextSeason?:string;totalSeasons?:number;kind?:string}={}):any{
 const season=options.season===undefined?'season1':options.season,rev=options.rev??1,ids=options.entries??['ep1','ep2'];
 return {scope:{serverId:'server',libraryId:'library',viewerFence:'fence'},revision:{catalog:rev,viewer:1},show:{id:'show',libraryId:'library',title:'The Harbor',year:2024,overview:'A coastal story.\nSecond line.',libraryKind:options.kind??'tv',providerMatchStatus:'unresolved'},seasons:(options.seasons??['season1','specials']).map((id,i)=>({id,showId:'show',number:id==='specials'?0:i+1,title:id==='specials'?'Specials':'Season '+(i+1)})),seasonTotalCount:options.totalSeasons??2,nextSeasonCursor:options.nextSeason??'',groups:options.group?[{id:'unassigned_absolute',title:'Unassigned absolute episodes',count:2}]:[],selected:{seasonId:season,...(options.group?{group:'unassigned_absolute'}:{}),...(options.episode?{episodeId:options.episode}:{})},episodes:{scope:{serverId:'server',libraryId:'library',libraryKind:options.kind??'tv',view:season===null?'show':'season',entityId:season??'show',viewerFence:'fence'},revision:{catalog:rev,viewer:1},heading:{key:'entity.title',fallback:'The Harbor · Episodes'},navigation:[{id:'browse',labelKey:'library.shows',view:'browse'}],query:{sort:'episode',direction:'asc',category:'',q:'',limit:2,searchMode:'none'},sorts:[{id:'episode',labelKey:'sort.episode',directions:['asc']}],filters:[],sections:ids.length?[{id:season===null?'unassigned_absolute':'episodes',type:'list',heading:{key:'content.episodes',fallback:'Episodes'},entries:ids.map(id=>({id,kind:'episode',title:id,available:true,navigation:{view:'item',entityId:id},playback:{itemId:id,startSeconds:0}})),totalCount:10,nextCursor:options.next??''}]:[],...(ids.length?{}:{empty:{key:'content.empty',fallback:'No episodes.'}})}};
}
function setup(handler:(path:string,signal?:AbortSignal)=>Promise<any>,timeoutMs=1000){const api:LibraryContentApi={request:<T>(p:string,_m?:string,_b?:unknown,s?:AbortSignal)=>handler(p,s) as Promise<T>};return new ShowWorkspaceService({api,scope,pageSize:2,seasonPageSize:2,timeoutMs});}
function deferred(){let resolve!:(v:any)=>void;const promise=new Promise<any>(r=>{resolve=r;});return {promise,resolve};}const tick=()=>new Promise(r=>setTimeout(r,0));
test('show projection retains every valid genre beyond the former preview size',async()=>{const genres=Array.from({length:25},(_,i)=>`Genre ${i}`);const s=setup(async()=>{const d=dto();d.show.genres=genres;return d;});await s.select(route);assert.deepEqual(s.getSnapshot().data!.show.genres,genres);});
test('bounded show payload retains show identity, inline episode actions, specials and immutable metadata',async()=>{const s=setup(async()=>dto());await s.select(route);const d=s.getSnapshot().data!;assert.equal(d.show.overview,'A coastal story.\nSecond line.');assert.equal(d.seasons[1].title,'Specials');assert.deepEqual(d.episodes.sections[0].entries[0].playback,{itemId:'ep1',startSeconds:0});assert.throws(()=>{(d.seasons as any).push({});});assert.equal(s.getSnapshot().phase,'ready');});
test('episode-only hard link resolves bounded target page and initial expansion without scanning seasons',async()=>{const calls:string[]=[];const s=setup(async p=>{calls.push(p);return dto({season:'season99',seasons:['season1'],totalSeasons:99,nextSeason:'seasons-next',episode:'ep185',entries:['ep185','ep186'],next:'next'});});await s.select({libraryId:'library',episodeId:'ep185'});assert.equal(calls.length,1);assert.match(calls[0],/episodeId=ep185/);assert.equal(s.getSnapshot().anchor.expandedEpisodeId,'ep185');assert.equal(s.getSnapshot().data!.selected.seasonId,'season99');});
test('conflicting ancestor, selected season, deep first row and embedded revision/fence fail closed',async()=>{for(const mutate of [(d:any)=>{d.show.id='other';},(d:any)=>{d.selected.seasonId='other';},(d:any)=>{d.episodes.sections[0].entries.reverse();},(d:any)=>{d.episodes.revision.viewer=9;},(d:any)=>{d.episodes.scope.viewerFence='other';},(d:any)=>{d.seasons[0].showId='other';}]){const s=setup(async()=>{const d=dto({episode:'ep1'});mutate(d);return d;});await s.select({...route,seasonId:'season1',episodeId:'ep1'});assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,'error');}});
test('season switch clears old hard-link ancestry; canonical group remains server-authored',async()=>{const calls:string[]=[];const s=setup(async p=>{calls.push(p);const q=new URL(p,'https://test').searchParams;return q.has('selectedSeasonId')?dto({season:'specials'}):q.has('group')?dto({season:null,group:true,kind:'anime'}):dto({episode:'ep1',group:false});});await s.select({...route,seasonId:'season1',episodeId:'ep1'});await s.selectSeason('specials');const q=new URL(calls[1],'https://test').searchParams;assert.equal(q.get('showId'),'show');assert.equal(q.get('selectedSeasonId'),'specials');assert.equal(q.has('seasonId'),false);assert.equal(q.has('episodeId'),false);assert.throws(()=>s.selectGroup('unassigned_absolute'));await s.select({...route,group:'unassigned_absolute'});assert.equal(s.getSnapshot().data!.selected.seasonId,null);assert.equal(s.getSnapshot().data!.episodes.scope.view,'show');});
test('episode continuation retains target binding; captured page/focus/scroll restores after player cancellation',async()=>{const calls:string[]=[];const handler=async(p:string)=>{calls.push(p);const q=new URL(p,'https://test').searchParams;return dto({episode:'ep185',entries:q.has('cursor')?['ep187','ep188']:['ep185','ep186'],next:q.has('cursor')?'':'page2'});};const s=setup(handler);await s.select({...route,episodeId:'ep185'});await s.nextEpisodes();assert.match(calls[1],/episodeId=ep185/);assert.match(calls[1],/cursor=page2/);s.updateAnchor({expandedEpisodeId:'ep188',focusedEpisodeId:'ep188',scrollOffset:850});const restore=s.captureRestore()!;s.cancel();await s.select(restore.route,restore);assert.equal(s.getSnapshot().pagination.cursor,'page2');assert.equal(s.getSnapshot().anchor.focusedEpisodeId,'ep188');assert.equal(s.getSnapshot().anchor.scrollOffset,850);await s.previousEpisodes();assert.equal(s.getSnapshot().data!.episodes.sections[0].entries[0].id,'ep185');});
test('partial season pages do not discard episode cursor and do not accumulate entire series',async()=>{const calls:string[]=[];const s=setup(async p=>{calls.push(p);const q=new URL(p,'https://test').searchParams;return dto({entries:q.has('cursor')?['ep3','ep4']:['ep1','ep2'],next:q.has('cursor')?'':'episodes-next',seasons:q.has('seasonCursor')?['season3']:['season1','season2'],totalSeasons:3,nextSeason:q.has('seasonCursor')?'':'seasons-next'});});await s.select(route);await s.nextEpisodes();s.updateAnchor({expandedEpisodeId:'ep3',focusedEpisodeId:'ep3',scrollOffset:22});await s.nextSeasons();assert.equal(s.getSnapshot().data!.seasons.length,1);assert.equal(s.getSnapshot().data!.seasons[0].id,'season3');assert.equal(s.getSnapshot().pagination.cursor,'episodes-next');assert.equal(s.getSnapshot().anchor.focusedEpisodeId,'ep3');assert.match(calls.at(-1)!,/cursor=episodes-next/);await s.previousSeasons();assert.equal(s.getSnapshot().data!.seasons[0].id,'season1');});
test('empty show has no invented season or unassigned group',async()=>{const s=setup(async()=>dto({season:null,seasons:[],totalSeasons:0,entries:[]}));await s.select(route);assert.deepEqual(s.getSnapshot().data!.groups,[]);assert.equal(s.getSnapshot().data!.selected.seasonId,null);assert.equal(s.getSnapshot().data!.episodes.sections.length,0);assert.throws(()=>s.selectSeason('season1'));});
test('unavailable episode retains inline navigation and has no false playback action',async()=>{const s=setup(async()=>{const d=dto();d.episodes.sections[0].entries[0].available=false;delete d.episodes.sections[0].entries[0].playback;return d;});await s.select(route);assert.equal(s.getSnapshot().data!.episodes.sections[0].entries[0].available,false);});
test('late response after selected season changes is cancelled even with ignored abort',async()=>{const d=deferred();let signal:AbortSignal|undefined;const s=setup(async(p,a)=>{if(p.includes('selectedSeasonId'))return dto({season:'specials'});signal=a;return d.promise;});const old=s.select(route);await s.select({...route,selectedSeasonId:'specials'});await old;d.resolve(dto());await tick();assert.equal(signal!.aborted,true);assert.equal(s.getSnapshot().data!.selected.seasonId,'specials');});
test('scope reset rejects other-identity restoration and clears pending/denied content',async()=>{let denied=false;const s=setup(async()=>{if(denied)throw Object.assign(new Error('denied'),{code:'unauthorized'});return dto();});await s.select(route);const restore=s.captureRestore()!;denied=true;await s.refresh();assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().error!.code,'unauthorized');s.setScope({...scope,viewerId:'other'},{request:async<T>()=>dto() as T});assert.throws(()=>s.select(route,restore));assert.equal(s.getSnapshot().phase,'idle');});
test('revision change rejects continuation and retry explicitly restarts first page',async()=>{let revision=1;const urls:string[]=[];const s=setup(async p=>{urls.push(p);return dto({rev:revision,next:'next'});});await s.select(route);revision=2;await s.nextEpisodes();assert.equal(s.getSnapshot().phase,'refresh-required');assert.equal(s.getSnapshot().data,null);await s.retry();assert.equal(s.getSnapshot().phase,'ready');assert.equal(new URL(urls.at(-1)!,'https://test').searchParams.has('cursor'),false);});
test('expired server cursor and changed restore fence request explicit refresh, never silently page one',async()=>{let stale=false;const s=setup(async()=>{if(stale)throw Object.assign(new Error('expired'),{code:'stale_continuation'});return dto({next:'next'});});await s.select(route);stale=true;await s.nextEpisodes();assert.equal(s.getSnapshot().phase,'refresh-required');assert.equal(s.getSnapshot().data,null);});
test('read errors retry same target and finite timeout releases ignored-abort request',async()=>{let fail=true;const s=setup(async()=>{if(fail)throw new Error('offline');return dto();});await s.select(route);assert.equal(s.getSnapshot().phase,'error');fail=false;await s.retry();assert.equal(s.getSnapshot().phase,'ready');const slow=setup(async()=>new Promise(()=>{}),5);await slow.select(route);assert.equal(slow.getSnapshot().error!.code,'timeout');});
test('duplicate active reads coalesce; oversized seasons and weak episode payload rejected by canonical validator',async()=>{const d=deferred();const s=setup(async()=>d.promise);const a=s.select(route);assert.equal(a,s.select(route));d.resolve(dto());await a;for(const change of [(d:any)=>{d.seasons.push({id:'third',showId:'show',number:3,title:'Season3'});},(d:any)=>{d.episodes.sections[0].entries[0].kind=undefined;},(d:any)=>{d.episodes.sections[0].entries[0].playback.itemId='other';}]){const bad=setup(async()=>{const v=dto();change(v);return v;});await bad.select(route);assert.equal(bad.getSnapshot().phase,'error');}});
test('route helper rejects unknown/query injection fields and anchors from other pages',async()=>{assert.throws(()=>validateShowWorkspaceRoute({...route,token:'secret'} as any));assert.throws(()=>validateShowWorkspaceRoute({libraryId:'library'}));const s=setup(async()=>dto());await s.select(route);assert.throws(()=>s.updateAnchor({expandedEpisodeId:'other',focusedEpisodeId:null,scrollOffset:0}));const restore=s.captureRestore()!;assert.throws(()=>s.select(route,{...restore,history:Array(65).fill(null)}));});
test('own playback return rebuilds the same page with advanced progress revision and retained inline focus; Previous remains functional',async()=>{let viewer=1;const urls:string[]=[];const s=setup(async p=>{urls.push(p);const q=new URL(p,'https://test').searchParams;const first=q.get('episodeId');const page2=q.has('cursor')||first==='ep3';const d=dto({episode:first??undefined,entries:page2?['ep3','ep4']:['ep1','ep2'],next:page2?'':'next'});d.revision.viewer=viewer;d.episodes.revision.viewer=viewer;return d;});await s.select(route);await s.nextEpisodes();s.updateAnchor({expandedEpisodeId:'ep4',focusedEpisodeId:'ep4',scrollOffset:912});const saved=s.captureRestore()!;viewer=2;s.cancel();await s.restoreAfterPlayback(saved);assert.equal(s.getSnapshot().phase,'ready');assert.deepEqual(s.getSnapshot().data!.episodes.sections[0].entries.map(e=>e.id),['ep3','ep4']);assert.equal(s.getSnapshot().anchor.focusedEpisodeId,'ep4');assert.equal(s.getSnapshot().anchor.scrollOffset,912);const q=new URL(urls.at(-1)!,'https://test').searchParams;assert.equal(q.get('episodeId'),'ep3');assert.equal(q.has('cursor'),false);assert.equal(q.has('seasonCursor'),false);assert.equal(s.getSnapshot().pagination.canPrevious,true);await s.previousEpisodes();assert.equal(s.getSnapshot().data!.episodes.sections[0].entries[0].id,'ep1');assert.equal(s.getSnapshot().pagination.canPrevious,false);});
test('own-playback recovery still rejects changed catalog, backwards viewer revision, permission fence, deleted target and denial',async()=>{for(const mode of ['catalog','viewer','fence','removed','denied']){let recovery=false;const s=setup(async p=>{if(recovery&&mode==='removed')throw Object.assign(new Error('gone'),{code:'not_found'});if(recovery&&mode==='denied')throw Object.assign(new Error('denied'),{code:'unauthorized'});const q=new URL(p,'https://test').searchParams;const d=dto({episode:q.get('episodeId')??undefined});if(recovery){if(mode==='catalog'){d.revision.catalog=2;d.episodes.revision.catalog=2;}if(mode==='viewer'){d.revision.viewer=0;d.episodes.revision.viewer=0;}if(mode==='fence'){d.scope.viewerFence='other';d.episodes.scope.viewerFence='other';}}return d;});await s.select(route);const saved=s.captureRestore()!;recovery=true;await s.restoreAfterPlayback(saved);assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().phase,mode==='denied'?'error':'refresh-required');}});
test('episode history remains bounded after many pages',async()=>{let next=0;const s=setup(async()=>dto({entries:['ep'+next,'other'+next],next:'cursor'+(++next)}));await s.select(route);for(let i=0;i<70;i++)await s.nextEpisodes();assert.equal(s.getSnapshot().pagination.history.length,64);assert.equal(s.captureRestore()!.pageAnchors.length,64);});
test('explicit metadata refresh accepts newer catalog while preserving server page anchor, inline episode and selection',async()=>{let revision=1;const urls:string[]=[];const s=setup(async p=>{urls.push(p);const q=new URL(p,'https://test').searchParams;return dto({rev:revision,episode:q.get('episodeId')??undefined,entries:q.has('cursor')||q.get('episodeId')==='ep3'?['ep3','ep4']:['ep1','ep2'],next:q.has('cursor')?'':'next'});});await s.select(route);await s.nextEpisodes();s.updateAnchor({expandedEpisodeId:'ep4',focusedEpisodeId:'ep4',scrollOffset:410});const saved=s.captureRestore()!;revision=2;await s.refreshAfterMetadata(saved);assert.equal(s.getSnapshot().phase,'ready');assert.equal(s.getSnapshot().data!.revision.catalog,2);assert.equal(s.getSnapshot().anchor.expandedEpisodeId,'ep4');assert.equal(s.getSnapshot().anchor.scrollOffset,410);const q=new URL(urls.at(-1)!,'https://test').searchParams;assert.equal(q.get('episodeId'),'ep3');assert.equal(q.get('selectedSeasonId'),'season1');assert.equal(q.has('cursor'),false);assert.equal(q.has('seasonCursor'),false);});
test('metadata refresh rejects changed permission, backward catalog, removed expanded episode and wrong ancestry',async()=>{for(const mode of ['fence','backward','removed','ancestry']){let refresh=false;const s=setup(async p=>{const q=new URL(p,'https://test').searchParams;const d=dto({rev:refresh&&mode==='backward'?0:1,episode:q.get('episodeId')??undefined,entries:refresh&&mode==='removed'?['ep1']:['ep1','ep2']});if(refresh&&mode==='fence'){d.scope.viewerFence='other';d.episodes.scope.viewerFence='other';}if(refresh&&mode==='ancestry')d.show.id='different';return d;});await s.select(route);s.updateAnchor({expandedEpisodeId:'ep2',focusedEpisodeId:'ep2',scrollOffset:90});const saved=s.captureRestore()!;refresh=true;await s.refreshAfterMetadata(saved);assert.equal(s.getSnapshot().data,null);assert.notEqual(s.getSnapshot().phase,'ready');}});

test('same-show paging retains the last page during a slow read; network failure keeps it but permission failure clears it',async()=>{
 const slow=deferred();let calls=0,denied=false;
 const s=setup(async()=>{calls++;if(calls===1)return dto({next:'next'});if(calls===2)return slow.promise;if(denied)throw Object.assign(new Error('Access removed'),{code:'forbidden'});throw Object.assign(new Error('Connection interrupted'),{code:'network_error'});});
 await s.select(route);const before=s.getSnapshot().data;const paging=s.nextEpisodes();
 assert.equal(s.getSnapshot().phase,'loading');assert.equal(s.getSnapshot().data,before);
 slow.resolve(dto({entries:['ep3','ep4']}));await paging;
 assert.equal(s.getSnapshot().data!.episodes.sections[0].entries[0].id,'ep3');
 await s.refresh();assert.equal(s.getSnapshot().phase,'error');assert.equal(s.getSnapshot().data!.episodes.sections[0].entries[0].id,'ep3');
 denied=true;await s.retry();assert.equal(s.getSnapshot().data,null);
});
test('selecting another show clears retained data immediately',async()=>{
  const slow=deferred();let calls=0;const s=setup(async()=>++calls===1?dto():slow.promise);
  await s.select(route);const pending=s.select({...route,showId:'other'});assert.equal(s.getSnapshot().data,null);s.cancel();await pending;
});
test('M32: server-sent hero facts and nextUp parse additively; malformed extras are dropped, never fatal',async()=>{
  const full=setup(async()=>{const d=dto();
    d.show={...d.show,logoUrl:'/v1/metadata/show/show/art/logo?v=abc&w=800',network:'AMC',studio:'Sony Pictures',contentRating:'TV-MA',originalTitle:'Breaking Bad',country:'United States',genres:['Drama','Crime']};
    d.nextUp={id:'ep2',kind:'episode',title:'ep2',available:true,libraryId:'library',seasonNumber:2,episodeNumber:3,duration:2700,progressSeconds:120,navigation:{view:'item',entityId:'ep2'},playback:{itemId:'ep2',startSeconds:120}};
    return d;});
  await full.select(route);const d=full.getSnapshot().data!;
  assert.equal(d.show.network,'AMC');assert.equal(d.show.studio,'Sony Pictures');assert.equal(d.show.contentRating,'TV-MA');assert.equal(d.show.originalTitle,'Breaking Bad');assert.equal(d.show.country,'United States');assert.deepEqual([...d.show.genres!],['Drama','Crime']);assert.equal(d.show.logoUrl,'/v1/metadata/show/show/art/logo?v=abc&w=800');
  assert.equal(d.nextUp!.id,'ep2');assert.equal(d.nextUp!.episodeNumber,3);assert.equal(d.nextUp!.playback!.startSeconds,120);
  assert.throws(()=>{(d.show.genres as unknown as string[]).push('Horror');});
  const broken=setup(async()=>{const v=dto();v.show={...v.show,network:42,genres:'Drama',logoUrl:'https://evil.example/x'};v.nextUp={id:'x'};return v;});
  await broken.select(route);const b=broken.getSnapshot().data!;
  assert.equal(b.show.network,undefined);assert.equal(b.show.genres,undefined);assert.equal(b.show.logoUrl,undefined);assert.equal(b.nextUp,undefined);assert.equal(broken.getSnapshot().phase,'ready');
});
