import test from 'node:test';import assert from 'node:assert/strict';
import {StorageManagementService} from '../src/storage-management.ts';
const scope={serverId:'server',viewerId:JSON.stringify(['local','owner','profile'])},wire={serverId:'server',viewerFence:'fence'},op='1788580000000-12345678-1234-1234-1234-123456789012';
const credentials={name:'Storage',executable:'/server/rclone',remote:'private:folder',config:'[private]\ntype = s3\nsecret_access_key = secret-value'};
function mount(changes:Record<string,unknown>={}):any{return {id:'mount',name:'Storage',executable:'/server/rclone',executableDigest:'a'.repeat(64),mountPath:'/server/mounts/mount',desiredState:'stopped',observedState:'stopped',controlRevision:1,removalPending:false,actions:['start','delete'],...changes};}
function list(mounts:any[]=[mount()]):any{return {scope:wire,revision:1,limits:{definitions:8,active:4},mounts};}
function receipt(changes:Record<string,unknown>={}):any{return {scope:wire,operationId:op,mountId:'mount',controlRevision:2,accepted:true,deleted:false,mount:mount({controlRevision:2,desiredState:'running',actions:['stop','restart']}),...changes};}
function service(fn:(p:string,m:string,b:any,s?:AbortSignal)=>Promise<unknown>,timeoutMs=1000,id=async()=>op){return new StorageManagementService({scope,operationId:id,timeoutMs,api:{request:<T>(p:string,m='GET',b?:unknown,s?:AbortSignal)=>fn(p,m,b,s) as Promise<T>}});}
function deferred(){let resolve!:(v:unknown)=>void;const promise=new Promise<unknown>(r=>resolve=r);return {promise,resolve};}
test('server-authored control actions and quarantined/removal observations remain distinct',async()=>{const s=service(async()=>list([mount({observedState:'quarantined',actions:['stop']})]));await s.load();assert.equal(s.getSnapshot().data!.mounts[0].observedState,'quarantined');assert.deepEqual(s.getSnapshot().data!.mounts[0].actions,['stop']);assert.throws(()=>s.act('mount','restart',1));assert.throws(()=>{(s.getSnapshot().data!.mounts as any).push(mount());});s.dispose();});
test('create submits secrets only in request, snapshots and error state never retain them',async()=>{const writes:any[]=[];const s=service(async(p,m,b)=>{if(m==='POST'){writes.push({p,b});throw new Error(credentials.config+' '+credentials.remote);}return list([]);});await s.load();await s.create(credentials);assert.equal(writes.length,1);assert.equal(writes[0].b.config,credentials.config);assert.equal(writes[0].b.operationId,op);assert.equal(s.getSnapshot().mutation.phase,'ambiguous');const json=JSON.stringify(s.getSnapshot());assert(!json.includes('secret-value'));assert(!json.includes('private:folder'));assert(!json.includes('secret_access_key'));s.dispose();});
test('lost response recovery GETs exact original receipt and never repeats credential body or mints ID',async()=>{const requests:{p:string;m:string;b:any}[]=[];let ids=0;const s=service(async(p,m,b)=>{requests.push({p,m,b});if(m==='POST')throw new TypeError('Lost');if(p.includes('/operations/'))return receipt({controlRevision:1,mount:mount()});return list([]);},1000,async()=>{ids++;return op;});await s.load();await s.create(credentials);await s.recover();assert.equal(ids,1);assert.equal(requests.filter(r=>r.m==='POST').length,1);assert(requests.some(r=>r.p==='/v1/storage/operations/'+op&&r.m==='GET'&&r.b===undefined));assert.equal(s.getSnapshot().mutation.phase,'accepted');s.dispose();});
test('unknown receipt remains ambiguous and never automatically resubmits',async()=>{let writes=0;const s=service(async(p,m)=>{if(m==='POST'){writes++;throw new Error('Lost');}if(p.includes('/operations/'))throw Object.assign(new Error('Missing'),{status:404,code:'not_found'});return list();});await s.load();await s.act('mount','start',1);await s.recover();assert.equal(s.getSnapshot().mutation.phase,'ambiguous');assert.equal(s.getSnapshot().mutation.error?.code,'not_found');assert.equal(writes,1);s.dispose();});
test('explicit CAS, server action authorization and command mutex block stale or duplicate intent',async()=>{const d=deferred();let writes=0;const s=service(async(_p,m,b)=>{if(m==='POST'){writes++;assert.equal(b.expectedRevision,1);assert.equal(b.action,'start');return d.promise;}return list();});await s.load();assert.throws(()=>s.act('mount','start',2));const pending=s.act('mount','start',1);assert.throws(()=>s.act('mount','start',1));await Promise.resolve();d.resolve(receipt());await pending;assert.equal(writes,1);assert.equal(s.getSnapshot().mutation.phase,'accepted');s.dispose();});
test('delete receipt is accepted removal intent, not a claim that cleanup completed',async()=>{const removing=mount({controlRevision:2,removalPending:true,actions:[]});const s=service(async(_p,m,b)=>{if(m==='DELETE'){assert.deepEqual(b,{expectedRevision:1,operationId:op});return receipt({deleted:true,mount:removing});}return list();});await s.load();await s.remove('mount',1);assert.equal(s.getSnapshot().mutation.receipt!.deleted,true);assert.equal(s.getSnapshot().mutation.receipt!.mount!.removalPending,true);assert.deepEqual(s.getSnapshot().mutation.receipt!.mount!.actions,[]);s.dispose();});
test('scope change fences late accepted command and clears source/control metadata',async()=>{const d=deferred();const s=service(async(_p,m)=>m==='POST'?d.promise:list());await s.load();const pending=s.act('mount','start',1);await Promise.resolve();s.setScope({...scope,viewerId:'another'},{request:async<T>()=>{throw new Error('unused');}});await pending;d.resolve(receipt());await Promise.resolve();assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().mutation.operationId,null);assert.equal(s.getSnapshot().mutation.phase,'idle');s.dispose();});
test('cancel keeps only original operation context so interrupted action can recover',async()=>{const d=deferred();let dispatched;const started=new Promise(r=>dispatched=r);const s=service(async(p,m)=>{if(m==='POST'){dispatched!();return d.promise;}if(p.includes('/operations/'))return receipt();return list();});await s.load();const pending=s.act('mount','start',1);await started;s.cancel();await pending;assert.equal(s.getSnapshot().mutation.phase,'ambiguous');assert.equal(s.getSnapshot().mutation.operationId,op);await s.recover();assert.equal(s.getSnapshot().mutation.phase,'accepted');s.dispose();});
test('cancel during async operation ID generation never sends a command or leaves preparing stuck',async()=>{const d=deferred();let writes=0;const s=service(async(_p,m)=>{if(m!=='GET')writes++;return list();},1000,()=>d.promise as Promise<string>);await s.load();const pending=s.act('mount','start',1);s.cancel();await pending;d.resolve(op);await Promise.resolve();assert.equal(writes,0);assert.equal(s.getSnapshot().mutation.phase,'idle');s.dispose();});
test('clock expiry, capacity and CAS errors are typed without hidden retries/new intent',async()=>{for(const code of ['storage_operation_expired','storage_command_capacity','storage_command_conflict']){let ids=0,writes=0;const s=service(async(_p,m)=>{if(m==='POST'){writes++;throw Object.assign(new Error(credentials.config),{code,serverTime:'2026-09-05T03:00:00Z',retryAfterSeconds:60});}return list();},1000,async()=>{ids++;return op;});await s.load();await s.act('mount','start',1);assert.equal(s.getSnapshot().mutation.phase,code==='storage_command_conflict'?'conflict':'error');assert.equal(s.getSnapshot().mutation.error!.code,code);assert.equal(s.getSnapshot().mutation.error!.serverTime,'2026-09-05T03:00:00Z');assert.equal(ids,1);assert.equal(writes,1);assert(!JSON.stringify(s.getSnapshot()).includes('secret_access_key'));s.dispose();}});
test('malformed receipts cannot accept another operation/mount/revision or leaked credentials',async()=>{for(const change of [{operationId:'other'},{mountId:'foreign'},{controlRevision:9},{mount:mount({controlRevision:2,remote:'private:folder'})}]){const s=service(async(_p,m)=>m==='POST'?receipt(change):list());await s.load();await s.act('mount','start',1);assert.equal(s.getSnapshot().mutation.phase,'ambiguous');assert.equal(s.getSnapshot().mutation.receipt,null);assert(!JSON.stringify(s.getSnapshot()).includes('private:folder'));s.dispose();}});
test('owner denial and changed fence clear previous privileged list and receipts',async()=>{let deny=false;const s=service(async()=>{if(deny)throw Object.assign(new Error('Denied'),{status:403});return list();});await s.load();deny=true;await s.load();assert.equal(s.getSnapshot().phase,'error');assert.equal(s.getSnapshot().data,null);assert.equal(s.getSnapshot().mutation.operationId,null);s.dispose();const changed=service(async()=>list());await changed.load();changed.setScope(scope,{request:async<T>()=>({...list(),scope:{...wire,viewerFence:'new'}}) as T});await changed.load();assert.equal(changed.getSnapshot().phase,'ready');changed.dispose();});
test('timeout of ignored transport is ambiguous, while oversized/malformed lists fail closed',async()=>{const s=service(async(_p,m)=>m==='POST'?new Promise(()=>{}):list(),5);await s.load();await s.act('mount','start',1);assert.equal(s.getSnapshot().mutation.phase,'ambiguous');assert.equal(s.getSnapshot().mutation.error!.code,'timeout');s.dispose();for(const raw of [list(Array(9).fill(mount())),list([mount({removalPending:true,actions:['start']})]),{...list(),scope:{...wire,serverId:'other'}}]){const bad=service(async()=>raw);await bad.load();assert.equal(bad.getSnapshot().phase,'error');assert.equal(bad.getSnapshot().data,null);bad.dispose();}});
test('safe executable/configuration codes are actionable definite rejections without submitted data or retry',async()=>{for(const code of ['storage_executable_invalid','storage_config_invalid']){let writes=0;const s=service(async(_p,m)=>{if(m==='POST'){writes++;throw Object.assign(new Error(credentials.config+' '+credentials.remote),{status:400,code,retryable:false});}return list([]);});await s.load();await s.create(credentials);assert.equal(s.getSnapshot().mutation.phase,'error');assert.equal(s.getSnapshot().mutation.error?.code,code);assert.equal(s.getSnapshot().mutation.error?.retryable,false);assert.equal(writes,1);assert(!JSON.stringify(s.getSnapshot()).includes('secret_access_key'));assert(!JSON.stringify(s.getSnapshot()).includes('private:folder'));assert.match(s.getSnapshot().mutation.error!.message,code==='storage_executable_invalid'?/native rclone executable/:/configuration format/);s.dispose();}});

test('allocation recovery is a definite rejection and never triggers credential replay',async()=>{let writes=0;const s=service(async(_p,m)=>{if(m==='POST'){writes++;throw Object.assign(new Error(credentials.config),{status:409,code:'storage_allocation_recovery_required',retryable:false});}return list([]);});await s.load();await s.create(credentials);const state=s.getSnapshot();assert.equal(state.mutation.phase,'error');assert.equal(state.mutation.error?.code,'storage_allocation_recovery_required');assert.equal(state.mutation.error?.retryable,false);assert.match(state.mutation.error!.message,/allocations need recovery/);assert.equal(writes,1);assert(!JSON.stringify(state).includes('secret_access_key'));s.dispose();});
