import {ApiError} from '@core/index.ts';
export type IdentityProvider='google'|'apple';
export type IdentityOptions={password:boolean;registration?:boolean;verifiedContactRequired:boolean;providers:{id:IdentityProvider;enabled:boolean}[]};
export type IdentityTransaction={transactionId:string;status:'onboarding'|'contact_pending'|'completed'|'failed';provider:IdentityProvider;contactVerified:boolean;expiresAt:string;needsUsername?:boolean};
export type Registration={registrationId:string;status:'contact_pending';revision:string;maskedAddress:string;expiresAt:string};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const id=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,160}$/.test(v);
const date=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const invalid=()=>new Error('The account service returned an invalid response. Try signing in again.');
export function parseIdentityOptions(v:unknown):IdentityOptions{if(!object(v)||typeof v.password!=='boolean'||typeof v.verifiedContactRequired!=='boolean'||!Array.isArray(v.providers)||v.providers.length>2)throw invalid();const seen=new Set();const providers=v.providers.map(p=>{if(!object(p)||!['google','apple'].includes(String(p.id))||typeof p.enabled!=='boolean'||seen.has(p.id))throw invalid();seen.add(p.id);return{id:p.id as IdentityProvider,enabled:p.enabled}});return{password:v.password,registration:v.registration===true,verifiedContactRequired:v.verifiedContactRequired,providers};}
export function parseIdentityTransaction(v:unknown,expected?:string):IdentityTransaction{if(!object(v)||!id(v.transactionId)||expected&&v.transactionId!==expected||!['onboarding','contact_pending','completed','failed'].includes(String(v.status))||!['google','apple'].includes(String(v.provider))||typeof v.contactVerified!=='boolean'||!date(v.expiresAt))throw invalid();return{transactionId:v.transactionId,status:v.status as IdentityTransaction['status'],provider:v.provider as IdentityProvider,contactVerified:v.contactVerified,expiresAt:v.expiresAt,needsUsername:v.needsUsername!==false};}
export function parseRegistration(v:unknown):Registration{if(!object(v)||!id(v.registrationId)||v.status!=='contact_pending'||typeof v.revision!=='string'||typeof v.maskedAddress!=='string'||v.maskedAddress.length>320||!date(v.expiresAt))throw invalid();return{registrationId:v.registrationId,status:v.status,revision:v.revision,maskedAddress:v.maskedAddress,expiresAt:v.expiresAt};}
export function providerRedirect(v:unknown,provider:IdentityProvider){if(!object(v)||!id(v.transactionId)||!date(v.expiresAt)||typeof v.authorizationUrl!=='string'||v.authorizationUrl.length>8192)throw invalid();const url=new URL(v.authorizationUrl);if(url.protocol!=='https:'||url.username||url.password||url.port||url.hostname!==(provider==='google'?'accounts.google.com':'appleid.apple.com'))throw invalid();return url.href;}
export async function accountRequest<T>(origin:string,path:string,method='GET',body?:unknown,signal?:AbortSignal,token?:string):Promise<T>{if(!path.startsWith('/v1/'))throw invalid();const response=await fetch(origin+path,{method,credentials:'include',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(15000),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!response.ok){const v=await response.json().catch(()=>null);throw new ApiError(response.status,v?.error?.code??'request_failed',v?.error?.message??'Could not reach your Portico Account.',v?.error?.retryable??response.status>=500);}return response.status===204?undefined as T:response.json();}
export function consumeIdentityLocation(){const url=new URL(location.href);const callback=['/auth/sso/google/callback','/auth/sso/apple/callback'].includes(url.pathname);const transaction=url.searchParams.get('identityTransaction');const identityError=url.searchParams.has('identityError');if(callback||transaction!==null||identityError){history.replaceState(null,'','/account');}return{callback,transaction:transaction&&id(transaction)?transaction:undefined,invalid:identityError||transaction!==null&&!id(transaction)};}
