/** Channel (Live TV, Library Channels) projection shapes shared by the v1 channel control
 * (spec §18.6) and the player: the reference, the desired transport, the media window. */
export type ChannelReference = Readonly<{kind:'live-source'|'library-channel'; sourceId:string; channelId:string; generation:string}>;
export type ChannelSeek = Readonly<{seekCommandId:string; bufferGeneration:string; kind:'position'|'live'; positionUs:string|null}>;
export type ChannelDesired = Readonly<{state:'playing'|'paused'; seek:ChannelSeek|null; retryRequestId:string|null}>;
export type ChannelProgramme = Readonly<{id:string;itemId:string;title:string;startMs:number;endMs:number}>;
export type ChannelMedia = Readonly<{streamUrl:string;bufferGeneration:string;presentationGeneration:string;originMs:number;windowRevision:string;windowStartUs:string;windowEndUs:string;liveEdgeUs:string;gaps:readonly {startUs:string;endUs:string}[];state:string;errorCode:string;logoUrl:string}>;
export type ChannelProjection = Readonly<{channel:ChannelReference;name:string;programme:ChannelProgramme|null;next:ChannelProgramme|null;desired:ChannelDesired;media:ChannelMedia;overlay:{enabled:boolean;corner:string;sizePercent:number;insetPercent:number;treatment:string};confirmedPositionUs:string|null;acknowledgedSeekCommandId:string|null;seekError:string}>;
export const controlID=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,128}$/.test(v);
export const channelSeconds=(v:string):number=>{if(!/^(?:0|-?[1-9][0-9]{0,18})$/.test(v)||!Number.isSafeInteger(Number(v)))throw new Error('Invalid channel clock.');return Number(v)/1e6;};
export const channelMessage=(code:string)=>({window_expired:'That position has left the retained window. Choose Go Live.',media_gap:'This position crosses a source interruption. Choose another position or Go Live.',source_unavailable:'The channel source is unavailable. Reconnecting; Retry starts another attempt.',source_changed:'The channel changed. Refresh the guide and select it again.',schedule_preparing:'The server is preparing the channel schedule.',unsupported_tuple:'This source is not compatible with this device and the allowed quality settings.',transcoding_disabled:'This source needs conversion, but transcoding is disabled by the owner.',decoder_confinement_unavailable:'The server platform does not provide the required decoder confinement.',lease_expired:'Playback authorization expired. Retry to renew access.',access_revoked:'This profile no longer has access to the channel.',engine_seek_failed:'The player did not reach that retained position. Choose Go Live or retry the seek.',revision_conflict:'The channel changed while applying that control. Try the control again.',owner_account_cap:'The owner-configured account playback limit has been reached.',owner_server_cap:'The owner-configured server playback limit has been reached.',tuner_busy:'All tuners for this source are in use.'} as Record<string,string>)[code]??'Channel playback could not complete. Check the source and retry.';
