// Generates src/ui/tokens.css from packages/design. The web never redefines
// a colour; it consumes the shared projection the Apple apps also use.
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const design = await import('../../packages/design/src/index.ts');
const {colors, spacing, radii, motion, layers, profileArtColors, typeScale, displayDesktopSize, targets, componentSpec} = design;
const lines = [':root {'];
const kebab = s => s.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
for (const [k, v] of Object.entries(colors)) lines.push(`  --color-${kebab(k)}: ${v};`);
for (const [k, v] of Object.entries(profileArtColors)) lines.push(`  --profile-art-${k}: ${v};`);
for (const [k, v] of Object.entries(spacing)) lines.push(`  --space-${k}: ${v}px;`);
for (const [k, v] of Object.entries(radii)) lines.push(`  --radius-${k}: ${v === 999 ? '999px' : v + 'px'};`);
for (const [k, v] of Object.entries(motion)) lines.push(`  --motion-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(layers)) lines.push(`  --layer-${k}: ${v};`);
for (const [k, v] of Object.entries(targets)) lines.push(`  --target-${kebab(k)}: ${v}px;`);
// Overlay and menu geometry (CON-29): the web column of the shared component
// spec, so Dialog/Sheet/Menu read the same scale as the Apple primitives.
// Type roles come from the --type-* tokens above (title `heading`, subtitle
// `caption`); radii from --radius-overlay / --radius-panel / --radius-control.
const {overlay, menu} = componentSpec;
lines.push(`  --overlay-inset: ${overlay.inset.web}px;`);
lines.push(`  --overlay-header-top: ${overlay.headerPaddingTop.web}px;`);
lines.push(`  --overlay-header-gap: ${overlay.headerGap.web}px;`);
lines.push(`  --overlay-footer-gap: ${overlay.footer.gap.web}px;`);
lines.push(`  --overlay-footer-padding-y: ${overlay.footer.paddingY.web}px;`);
lines.push(`  --menu-padding: ${menu.padding.web}px;`);
lines.push(`  --menu-row-min: ${menu.row.minHeight.web}px;`);
lines.push(`  --menu-row-min-touch: ${menu.row.minHeight.phone}px;`);
lines.push(`  --menu-row-padding-x: ${menu.row.paddingX.web}px;`);
lines.push(`  --menu-row-gap: ${menu.row.gap.web}px;`);
// Type roles (handheld/web column). Web may make display fluid up to --type-display-size-desktop.
for (const [role, t] of Object.entries(typeScale.handheld)) {
  const r = kebab(role);
  lines.push(`  --type-${r}-size: ${t.size}px;`, `  --type-${r}-line: ${t.lineHeight}px;`, `  --type-${r}-weight: ${t.weight};`, `  --type-${r}-tracking: ${t.tracking}em;`);
}
lines.push(`  --type-display-size-desktop: ${displayDesktopSize}px;`);
lines.push('}');
const out = fileURLToPath(new URL('../src/ui/tokens.css', import.meta.url));
writeFileSync(out, '/* Generated by scripts/tokens.mjs from packages/design. Do not edit. */\n' + lines.join('\n') + '\n');
console.log('wrote', out);
