// Generated by apigen. Do not edit.
export const errors = [
  {
    "code": "administration_unavailable",
    "status": 503,
    "message": "Administration is temporarily unavailable.",
    "retry": "same_request"
  },
  {
    "code": "artwork_gone",
    "status": 410,
    "message": "This artwork version is no longer available.",
    "retry": "after_refresh"
  },
  {
    "code": "artwork_pending",
    "status": 404,
    "message": "Artwork is not available yet.",
    "retry": "same_request"
  },
  {
    "code": "body_too_large",
    "status": 413,
    "message": "The request is too large.",
    "retry": "never"
  },
  {
    "code": "channel_unavailable",
    "status": 503,
    "message": "This channel can't be played right now.",
    "retry": "same_request"
  },
  {
    "code": "cursor_expired",
    "status": 409,
    "message": "Refresh the list to continue.",
    "retry": "after_refresh"
  },
  {
    "code": "device_approval_pending",
    "status": 403,
    "message": "This device is waiting for approval.",
    "retry": "never"
  },
  {
    "code": "device_denied",
    "status": 403,
    "message": "This device is not approved.",
    "retry": "never"
  },
  {
    "code": "device_not_found",
    "status": 404,
    "message": "This device isn't available.",
    "retry": "never"
  },
  {
    "code": "event_stream_exists",
    "status": 409,
    "message": "An existing stream was retired; reconnect using your last event ID.",
    "retry": "same_request"
  },
  {
    "code": "feature_restricted",
    "status": 403,
    "message": "This feature is not permitted for this profile.",
    "retry": "never"
  },
  {
    "code": "idempotency_key_required",
    "status": 428,
    "message": "Send an Idempotency-Key with this request.",
    "retry": "never"
  },
  {
    "code": "idempotency_key_reused",
    "status": 422,
    "message": "This request conflicts with an earlier request.",
    "retry": "never"
  },
  {
    "code": "insufficient_disk",
    "status": 507,
    "message": "There isn't enough free disk space for this operation.",
    "retry": "same_request"
  },
  {
    "code": "internal",
    "status": 500,
    "message": "The request could not be completed.",
    "retry": "never"
  },
  {
    "code": "invalid_cursor",
    "status": 400,
    "message": "This page link is not valid.",
    "retry": "never"
  },
  {
    "code": "invalid_request",
    "status": 400,
    "message": "Check the request and try again.",
    "retry": "never"
  },
  {
    "code": "invitation_not_found",
    "status": 404,
    "message": "This invitation is not available.",
    "retry": "never"
  },
  {
    "code": "metadata_unavailable",
    "status": 503,
    "message": "Metadata is temporarily unavailable.",
    "retry": "same_request"
  },
  {
    "code": "method_not_allowed",
    "status": 405,
    "message": "This action is not supported.",
    "retry": "never"
  },
  {
    "code": "no_tuner_available",
    "status": 409,
    "message": "Every tuner is in use.",
    "retry": "after_refresh"
  },
  {
    "code": "not_controllable",
    "status": 403,
    "message": "This device can't be controlled from here.",
    "retry": "never"
  },
  {
    "code": "not_found",
    "status": 404,
    "message": "This item is not available.",
    "retry": "never"
  },
  {
    "code": "not_implemented",
    "status": 501,
    "message": "This server doesn't offer this yet.",
    "retry": "never"
  },
  {
    "code": "not_permitted",
    "status": 403,
    "message": "This action is not permitted.",
    "retry": "never"
  },
  {
    "code": "password_change_required",
    "status": 403,
    "message": "Change your password before continuing.",
    "retry": "never"
  },
  {
    "code": "playlist_capacity",
    "status": 409,
    "message": "This is more than a playlist can hold.",
    "retry": "never"
  },
  {
    "code": "prepare_not_allowed",
    "status": 409,
    "message": "The next item can't be prepared now.",
    "retry": "after_refresh"
  },
  {
    "code": "prepared_canceled",
    "status": 409,
    "message": "The prepared next item was canceled.",
    "retry": "never"
  },
  {
    "code": "prepared_expired",
    "status": 410,
    "message": "The prepared next item expired.",
    "retry": "never"
  },
  {
    "code": "queue_building",
    "status": 503,
    "message": "This part of the queue is still loading. Try again in a moment.",
    "retry": "same_request"
  },
  {
    "code": "queue_ended",
    "status": 409,
    "message": "There is nothing after this in the queue.",
    "retry": "never"
  },
  {
    "code": "queue_too_large",
    "status": 422,
    "message": "This queue is too long. Remove some of it or start a new one.",
    "retry": "never"
  },
  {
    "code": "rate_limited",
    "status": 429,
    "message": "Too many attempts. Try again later.",
    "retry": "same_request"
  },
  {
    "code": "request_in_progress",
    "status": 409,
    "message": "This request is still being processed.",
    "retry": "same_request"
  },
  {
    "code": "restore_integrity_failed",
    "status": 422,
    "message": "This backup failed its integrity check and can't be restored.",
    "retry": "never"
  },
  {
    "code": "restore_not_portico",
    "status": 422,
    "message": "This file is not a Portico database.",
    "retry": "never"
  },
  {
    "code": "restore_pre_release",
    "status": 409,
    "message": "This backup was created by an earlier pre-release Portico and can't be restored.",
    "retry": "never"
  },
  {
    "code": "restore_schema_newer",
    "status": 409,
    "message": "This backup was written by a newer Portico. Update this server before restoring it.",
    "retry": "never"
  },
  {
    "code": "restore_source_invalid",
    "status": 400,
    "message": "This restore source can't be used. Pick one of the listed backups or a Portico database file on the server.",
    "retry": "never"
  },
  {
    "code": "revision_mismatch",
    "status": 412,
    "message": "This information changed. Refresh and try again.",
    "retry": "after_refresh"
  },
  {
    "code": "revision_required",
    "status": 428,
    "message": "Refresh before making this change.",
    "retry": "after_refresh"
  },
  {
    "code": "seek_unavailable",
    "status": 409,
    "message": "That position isn't in the channel's buffer.",
    "retry": "after_refresh"
  },
  {
    "code": "session_ended",
    "status": 410,
    "message": "This playback has ended.",
    "retry": "never"
  },
  {
    "code": "source_unavailable",
    "status": 503,
    "message": "The file for this title can't be reached right now.",
    "retry": "same_request"
  },
  {
    "code": "stream_exists",
    "status": 409,
    "message": "This device already has an event stream open.",
    "retry": "never"
  },
  {
    "code": "stream_limit_reached",
    "status": 409,
    "message": "This account is already playing as many streams as it is allowed.",
    "retry": "never"
  },
  {
    "code": "stream_unavailable",
    "status": 503,
    "message": "This connection cannot stream events.",
    "retry": "same_request"
  },
  {
    "code": "transcode_not_allowed",
    "status": 403,
    "message": "This title needs converting, and converting is turned off for this account.",
    "retry": "never"
  },
  {
    "code": "unauthorized",
    "status": 401,
    "message": "Authentication is required.",
    "retry": "after_reauth"
  },
  {
    "code": "unsupported_media",
    "status": 422,
    "message": "This title can't be played on this device.",
    "retry": "never"
  },
  {
    "code": "unsupported_media_type",
    "status": 415,
    "message": "This request format is not supported.",
    "retry": "never"
  },
  {
    "code": "unsupported_selector",
    "status": 422,
    "message": "This selection can't be played as a queue.",
    "retry": "never"
  },
  {
    "code": "visibility_building",
    "status": 503,
    "message": "Library visibility is being prepared. Retry shortly.",
    "retry": "same_request"
  },
  {
    "code": "web_unavailable",
    "status": 503,
    "message": "The web app is temporarily unavailable.",
    "retry": "same_request"
  }
] as const;
