// Generated by apigen. Do not edit.
export const routes = [
  {
    "id": "add_queue_segment",
    "method": "POST",
    "path": "/v1/queues/{id}/segments",
    "summary": "Play next, add to the queue, or insert after an entry",
    "access": "device",
    "lane": "media",
    "cost": "selection_sized_async",
    "bodyLimit": 32768,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building"
    ],
    "status": 200
  },
  {
    "id": "advance_queue",
    "method": "POST",
    "path": "/v1/queues/{id}:advance",
    "summary": "Move to the next, previous or a chosen entry; starts its session when one is playing",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building",
      "queue_ended",
      "stream_limit_reached",
      "transcode_not_allowed",
      "unsupported_media"
    ],
    "status": 200
  },
  {
    "id": "change_playback_session",
    "method": "PATCH",
    "path": "/v1/playback/sessions/{id}",
    "summary": "Change tracks, quality, version or state; a change to the bytes starts a new generation",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "session_ended",
      "revision_required",
      "revision_mismatch",
      "stream_limit_reached",
      "transcode_not_allowed",
      "unsupported_media"
    ],
    "status": 200
  },
  {
    "id": "commit_queue_next",
    "method": "POST",
    "path": "/v1/queues/{id}:commit-next",
    "summary": "Commit the prepared next entry at the audio boundary: a new session inheriting state, rate, quality and track (spec §18.3)",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building",
      "prepared_expired",
      "prepared_canceled",
      "not_implemented"
    ],
    "status": 200
  },
  {
    "id": "create_download_request",
    "method": "POST",
    "path": "/v1/downloads/requests",
    "summary": "Queue all visible members of a container for offline preparation",
    "access": "device",
    "lane": "default",
    "cost": "selection_sized_async",
    "bodyLimit": 8192,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_permitted",
      "not_found",
      "idempotency_key_reused",
      "rate_limited",
      "internal"
    ],
    "status": 202
  },
  {
    "id": "create_job",
    "method": "POST",
    "path": "/v1/jobs",
    "summary": "Capture a selection and enqueue a durable bulk job",
    "access": "device",
    "lane": "default",
    "cost": "selection_sized_async",
    "bodyLimit": 65536,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_reused",
      "revision_mismatch",
      "rate_limited",
      "internal"
    ],
    "status": 202
  },
  {
    "id": "create_queue",
    "method": "POST",
    "path": "/v1/queues",
    "summary": "Play: replace this device's queue from selectors, optionally starting the first session",
    "access": "device",
    "lane": "media",
    "cost": "selection_sized_async",
    "bodyLimit": 65536,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building",
      "idempotency_key_required",
      "idempotency_key_reused",
      "stream_limit_reached",
      "transcode_not_allowed",
      "unsupported_media",
      "source_unavailable"
    ],
    "status": 201
  },
  {
    "id": "delete_admin_backup",
    "method": "DELETE",
    "path": "/v1/admin/backups/{id}",
    "summary": "Delete a server backup",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "invalid_request",
      "not_found",
      "administration_unavailable",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "delete_device",
    "method": "DELETE",
    "path": "/v1/devices/{id}",
    "summary": "Forget a device and sign out its sessions",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "invalid_request",
      "not_found",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "delete_device_sessions",
    "method": "DELETE",
    "path": "/v1/devices/{id}/sessions",
    "summary": "Sign out every session on this device",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "invalid_request",
      "not_found",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "delete_direct_session",
    "method": "DELETE",
    "path": "/v1/direct/sessions/{id}",
    "summary": "Sign out one direct-account session",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "invalid_request",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "delete_queue",
    "method": "DELETE",
    "path": "/v1/queues/{id}",
    "summary": "Clear the queue; idempotent",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_found"
    ],
    "status": 204
  },
  {
    "id": "get_admin_backups",
    "method": "GET",
    "path": "/v1/admin/backups",
    "summary": "List server backups and restore status",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "administration_unavailable",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_admin_maintenance_settings",
    "method": "GET",
    "path": "/v1/admin/maintenance/settings",
    "summary": "Read owner maintenance settings and choices",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "administration_unavailable",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_admin_updates",
    "method": "GET",
    "path": "/v1/admin/updates",
    "summary": "Read the owner's cached release check",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_auth_capabilities",
    "method": "GET",
    "path": "/v1/auth/capabilities",
    "summary": "Read the server's available sign-in methods",
    "access": "public",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_bootstrap",
    "method": "GET",
    "path": "/v1/bootstrap",
    "summary": "Read this viewer's startup state",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "deviceClass"
    ],
    "errors": [
      "unauthorized",
      "not_permitted",
      "invalid_request",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_capabilities",
    "method": "GET",
    "path": "/v1/capabilities",
    "summary": "Read this viewer's feature states and published limits",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_capability_report",
    "method": "GET",
    "path": "/v1/admin/diagnostics/capabilities",
    "summary": "Why Live TV, recording, prepared media or hardware encoding is unavailable on this server",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_permitted"
    ],
    "status": 200
  },
  {
    "id": "get_container_personal_state",
    "method": "GET",
    "path": "/v1/containers/{kind}/{id}/personal-state",
    "summary": "Read a container watermark, revision and visible-member counts",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_reused",
      "revision_mismatch",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_device_capabilities",
    "method": "GET",
    "path": "/v1/me/devices/current/capabilities",
    "summary": "Read this device's playback capability profile",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "get_devices",
    "method": "GET",
    "path": "/v1/devices",
    "summary": "List this account's devices",
    "access": "device",
    "lane": "security",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "installationId"
    ],
    "errors": [
      "unauthorized",
      "invalid_request",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_account",
    "method": "GET",
    "path": "/v1/direct",
    "summary": "Read the current direct account and its profiles",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_pin_recovery",
    "method": "GET",
    "path": "/v1/direct/pin-recovery",
    "summary": "Read available PIN reset confirmations",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_profile_avatars",
    "method": "GET",
    "path": "/v1/direct/profiles/avatars",
    "summary": "List this direct account's profile pictures",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_profile_restrictions",
    "method": "GET",
    "path": "/v1/direct/profiles/{id}/restrictions",
    "summary": "Read a direct profile's content and feature restrictions",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "invalid_request",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_registration_policy",
    "method": "GET",
    "path": "/v1/direct/registration-policy",
    "summary": "Read owner sign-up and device-approval policy",
    "access": "owner",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_permitted",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_direct_sessions",
    "method": "GET",
    "path": "/v1/direct/sessions",
    "summary": "Read this direct account's active and recently signed-out sessions",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "page_sized",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_download_request",
    "method": "GET",
    "path": "/v1/downloads/requests/{id}",
    "summary": "Read visible request counts and a window of preparations",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "cursor",
      "limit"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_permitted",
      "not_found",
      "idempotency_key_reused",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_events",
    "method": "GET",
    "path": "/v1/events",
    "summary": "Read the authorized event ring by long-poll or server-sent stream",
    "access": "device",
    "lane": "realtime",
    "cost": "constant",
    "bodyLimit": 0,
    "query": [
      "after",
      "waitSeconds",
      "topics"
    ],
    "errors": [
      "unauthorized",
      "invalid_request",
      "invalid_cursor",
      "event_stream_exists",
      "stream_unavailable",
      "internal"
    ],
    "status": 200,
    "sse": true
  },
  {
    "id": "get_job",
    "method": "GET",
    "path": "/v1/jobs/{id}",
    "summary": "Read this profile's job progress",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_reused",
      "revision_mismatch",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_job_failures",
    "method": "GET",
    "path": "/v1/jobs/{id}/failures",
    "summary": "Read visible failures from this profile's job",
    "access": "device",
    "lane": "default",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "cursor"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_reused",
      "revision_mismatch",
      "rate_limited",
      "internal",
      "invalid_cursor"
    ],
    "status": 200
  },
  {
    "id": "get_playback_options",
    "method": "GET",
    "path": "/v1/items/{itemId}/playback-options",
    "summary": "Read what a title offers and what this device would get",
    "access": "viewer_item_restrictions",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 0,
    "query": [
      "versionId",
      "partId",
      "audioId",
      "subtitleId",
      "quality",
      "maxVideoBitrateKbps",
      "maxHeight",
      "maxAudioBitrateKbps"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "get_playback_session",
    "method": "GET",
    "path": "/v1/playback/sessions/{id}",
    "summary": "Read a playback session",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "get_playlist_order",
    "method": "GET",
    "path": "/v1/playlists/{id}/order",
    "summary": "Read a revision-fenced window of playlist occurrence IDs",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "cursor",
      "limit"
    ],
    "errors": [
      "invalid_request",
      "invalid_cursor",
      "unauthorized",
      "not_found",
      "revision_mismatch",
      "idempotency_key_reused",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_queue",
    "method": "GET",
    "path": "/v1/queues/{id}",
    "summary": "Read a queue's header",
    "access": "device",
    "lane": "browsing",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "get_queue_window",
    "method": "GET",
    "path": "/v1/queues/{id}/window",
    "summary": "Read the entries around the current one (at most 200)",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "around",
      "before",
      "after"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "get_rating_systems",
    "method": "GET",
    "path": "/v1/rating-systems",
    "summary": "List supported content-rating systems",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "get_server",
    "method": "GET",
    "path": "/v1/server",
    "summary": "Read server identity and API level",
    "access": "public",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "internal"
    ],
    "status": 200
  },
  {
    "id": "list_admin_sessions",
    "method": "GET",
    "path": "/v1/admin/sessions",
    "summary": "Active playback sessions: who, what, how it's delivered and from where",
    "access": "admin_scope",
    "scope": "playback",
    "lane": "default",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "limit",
      "cursor"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_permitted"
    ],
    "status": 200
  },
  {
    "id": "list_queue_entries",
    "method": "GET",
    "path": "/v1/queues/{id}/entries",
    "summary": "Read a page of entries from a position (at most 200)",
    "access": "device",
    "lane": "browsing",
    "cost": "page_sized",
    "bodyLimit": 0,
    "query": [
      "from",
      "limit",
      "cursor"
    ],
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found"
    ],
    "status": 200
  },
  {
    "id": "move_queue_entry",
    "method": "POST",
    "path": "/v1/queues/{id}/entries/{entryId}:move",
    "summary": "Move one entry before or after another",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building"
    ],
    "status": 200
  },
  {
    "id": "patch_device",
    "method": "PATCH",
    "path": "/v1/devices/{id}",
    "summary": "Edit this account's device record",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "invalid_request",
      "not_found",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "post_admin_backups",
    "method": "POST",
    "path": "/v1/admin/backups",
    "summary": "Start a server backup",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "invalid_request",
      "insufficient_disk",
      "administration_unavailable",
      "internal"
    ],
    "status": 202
  },
  {
    "id": "post_admin_backups_restore",
    "method": "POST",
    "path": "/v1/admin/backups/restore",
    "summary": "Stage a backup for restore on restart",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "invalid_request",
      "restore_source_invalid",
      "restore_schema_newer",
      "restore_pre_release",
      "restore_integrity_failed",
      "restore_not_portico",
      "insufficient_disk",
      "administration_unavailable",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "post_admin_state_permissions_fix",
    "method": "POST",
    "path": "/v1/admin/state-permissions:fix",
    "summary": "Tighten state folder permissions",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "administration_unavailable",
      "internal"
    ],
    "status": 200,
    "optionalBody": true
  },
  {
    "id": "post_device",
    "method": "POST",
    "path": "/v1/devices",
    "summary": "Register or refresh this account's device",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "device_approval_pending",
      "device_denied",
      "invalid_request",
      "internal"
    ],
    "status": 201
  },
  {
    "id": "post_device_approval",
    "method": "POST",
    "path": "/v1/devices/{id}/approval",
    "summary": "Approve or deny a pending device",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "not_permitted",
      "invalid_request",
      "not_found",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "post_device_session_binding",
    "method": "POST",
    "path": "/v1/devices/{id}/sessions/bind",
    "summary": "Verify a session's existing device binding",
    "access": "device",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "device_approval_pending",
      "invalid_request",
      "not_found",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "post_direct_profile_pin_reset",
    "method": "POST",
    "path": "/v1/direct/profiles/{id}/pin-reset",
    "summary": "Clear or replace a direct profile PIN",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "invalid_request",
      "request_in_progress",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "post_direct_sign_out_everywhere",
    "method": "POST",
    "path": "/v1/direct/sessions/sign-out-everywhere",
    "summary": "Sign this direct account out of every device",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "internal"
    ],
    "status": 204
  },
  {
    "id": "prepare_queue_next",
    "method": "POST",
    "path": "/v1/queues/{id}:prepare-next",
    "summary": "Prepare the next entry's audio before the current one ends (spec §18.2; private until committed)",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building",
      "idempotency_key_required",
      "idempotency_key_reused",
      "queue_ended",
      "prepare_not_allowed",
      "not_implemented"
    ],
    "status": 200
  },
  {
    "id": "preview_invitation",
    "method": "POST",
    "path": "/v1/access/invitations/preview",
    "summary": "Preview an invitation without consuming its code",
    "access": "public",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "invitation_not_found",
      "rate_limited",
      "invalid_request",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "put_admin_maintenance_settings",
    "method": "PUT",
    "path": "/v1/admin/maintenance/settings",
    "summary": "Save owner maintenance settings",
    "access": "owner",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 65536,
    "errors": [
      "unauthorized",
      "invalid_request",
      "revision_mismatch",
      "not_permitted",
      "not_found",
      "request_in_progress",
      "administration_unavailable",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "put_device_capabilities",
    "method": "PUT",
    "path": "/v1/me/devices/current/capabilities",
    "summary": "Replace this device's playback capability profile",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 32768,
    "errors": [
      "invalid_request",
      "unauthorized",
      "revision_mismatch"
    ],
    "status": 204
  },
  {
    "id": "put_direct_profile_restrictions",
    "method": "PUT",
    "path": "/v1/direct/profiles/{id}/restrictions",
    "summary": "Replace a direct profile's restrictions",
    "access": "admin_scope",
    "scope": "direct_account",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 32768,
    "errors": [
      "unauthorized",
      "password_change_required",
      "device_approval_pending",
      "device_denied",
      "not_permitted",
      "invalid_request",
      "revision_mismatch",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "put_direct_registration_policy",
    "method": "PUT",
    "path": "/v1/direct/registration-policy",
    "summary": "Save owner sign-up and device-approval policy",
    "access": "owner",
    "lane": "security",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "unauthorized",
      "not_permitted",
      "invalid_request",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "remove_queue_entry",
    "method": "DELETE",
    "path": "/v1/queues/{id}/entries/{entryId}",
    "summary": "Remove one entry",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 0,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building"
    ],
    "status": 200
  },
  {
    "id": "reorder_playlist_window",
    "method": "PUT",
    "path": "/v1/playlists/{id}/order",
    "summary": "Move or permute at most 200 playlist occurrences",
    "access": "device",
    "lane": "default",
    "cost": "page_sized",
    "bodyLimit": 65536,
    "errors": [
      "invalid_request",
      "invalid_cursor",
      "unauthorized",
      "not_found",
      "revision_mismatch",
      "idempotency_key_reused",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "report_playback_timeline",
    "method": "POST",
    "path": "/v1/playback/sessions/{id}/timeline",
    "summary": "Report progress; renews the lease",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "session_ended",
      "revision_required",
      "revision_mismatch"
    ],
    "status": 204
  },
  {
    "id": "save_queue_as_playlist",
    "method": "POST",
    "path": "/v1/queues/{id}:save-as-playlist",
    "summary": "Save the queue, in play order, as a new playlist; a long queue is copied in the background and a replay of the key reports progress",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 8192,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building",
      "idempotency_key_required",
      "idempotency_key_reused"
    ],
    "status": 201
  },
  {
    "id": "set_container_personal_state",
    "method": "PUT",
    "path": "/v1/containers/{kind}/{id}/personal-state",
    "summary": "Set a container watched watermark for this profile",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 2048,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_reused",
      "revision_mismatch",
      "rate_limited",
      "internal"
    ],
    "status": 200
  },
  {
    "id": "start_playback_session",
    "method": "POST",
    "path": "/v1/playback/sessions",
    "summary": "Start playback (201), or report that it is being prepared (202)",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 8192,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "idempotency_key_required",
      "idempotency_key_reused",
      "stream_limit_reached",
      "transcode_not_allowed",
      "source_unavailable",
      "unsupported_media",
      "feature_restricted",
      "no_tuner_available",
      "queue_building"
    ],
    "status": 201
  },
  {
    "id": "stop_playback_session",
    "method": "DELETE",
    "path": "/v1/playback/sessions/{id}",
    "summary": "Stop playback; idempotent",
    "access": "device",
    "lane": "media",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found"
    ],
    "status": 204,
    "optionalBody": true
  },
  {
    "id": "terminate_admin_session",
    "method": "POST",
    "path": "/v1/admin/sessions/{id}:terminate",
    "summary": "End a viewer's playback, showing them an optional message; idempotent",
    "access": "admin_scope",
    "scope": "playback",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 4096,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_permitted",
      "not_found"
    ],
    "status": 204,
    "optionalBody": true
  },
  {
    "id": "update_queue",
    "method": "PATCH",
    "path": "/v1/queues/{id}",
    "summary": "Set repeat, or shuffle on or off",
    "access": "device",
    "lane": "default",
    "cost": "constant",
    "bodyLimit": 1024,
    "errors": [
      "invalid_request",
      "unauthorized",
      "not_found",
      "revision_required",
      "revision_mismatch",
      "unsupported_selector",
      "queue_too_large",
      "queue_building"
    ],
    "status": 200
  }
] as const;
