// Generated by apigen. Do not edit.
import { schemas } from './schemas.ts';

type Schema = {type?: string; properties?: Record<string, Schema>; required?: readonly string[]; items?: Schema; additionalProperties?: Schema; minimum?: number; maximum?: number; nullable?: boolean};
/** Presentation objects accept additive fields. Optional nulls are treated as absent. */
function value(schema: Schema, input: unknown, path: string): unknown {
  const reject = (): never => { throw new Error(`Invalid contract value at ${path}`); };
  if (input === null && schema.nullable) return null;
  // The empty schema is any JSON value.
  if (schema.type === undefined) return input;
  switch (schema.type) {
    case 'any': if (input === null || input === undefined) return reject(); return input;
    case 'string': if (typeof input !== 'string') return reject(); return input;
    case 'boolean': if (typeof input !== 'boolean') return reject(); return input;
    case 'integer': if (typeof input !== 'number' || !Number.isSafeInteger(input)) return reject(); return input;
    case 'number': if (typeof input !== 'number' || !Number.isFinite(input)) return reject(); return input;
    case 'array': if (!Array.isArray(input) || !schema.items) return reject(); return input.map((entry, i) => value(schema.items!, entry, `${path}[${i}]`));
    case 'object': {
      if (input === null || typeof input !== 'object' || Array.isArray(input)) return reject();
      const source = input as Record<string, unknown>;
      const result: Record<string, unknown> = Object.create(null);
      if (schema.additionalProperties) {
        for (const [key, entry] of Object.entries(source)) result[key] = value(schema.additionalProperties, entry, `${path}.${key}`);
      } else {
        for (const [key, field] of Object.entries(schema.properties ?? {})) {
          const required = schema.required?.includes(key) ?? false;
          if (!required && (source[key] === undefined || source[key] === null)) continue;
          result[key] = value(field, source[key], `${path}.${key}`);
        }
      }
      return result;
    }
  }
  return reject();
}
export function decode(name: keyof typeof schemas, input: unknown): unknown {
  const schema = schemas[name];
  if (!schema) throw new Error('Unknown contract schema');
  return value(schema as Schema, input, '$');
}
