package app

import (
	"net/http"

	"github.com/PorticoMediaServer/portico-server/internal/app/apiroute"
)

func (s *Server) registerAuthRoutes(reg *apiroute.Registry) {
	reg.Public("/api/auth/capabilities", s.handleAuthCapabilities)
	reg.Public("/api/auth/me", s.handleAuthMe)
	reg.Public("/api/auth/setup", s.handleSetup)
	reg.Public("/api/auth/portico-setup/claim/start", s.handlePorticoSetupClaimStart)
	reg.Public("/api/auth/portico-setup/status", s.handlePorticoSetupStatus)
	reg.Public("/api/auth/login", s.handleLogin)
	reg.Public("/api/auth/profile-authentications/local", s.handleLocalProfileAccountAuthentication)
	reg.Public("/api/auth/profile-selections/local", s.handleLocalProfileSelection)
	reg.Session("/api/auth/profile-selections/session", s.withAuth(s.handleActiveLocalProfileSelection))
	reg.Public("/api/auth/profile-sessions/browser", s.handleBrowserProfileSession)
	reg.Public("/api/auth/profile-sessions/native", s.handleNativeProfileSession)
	reg.Public("/api/auth/browser-accounts", s.handleBrowserAccounts)
	reg.Public("/api/auth/browser-accounts/", s.handleBrowserAccountRoute)
	reg.Public("/api/auth/sessions", s.handleNativeSessions)
	reg.Public("/api/auth/sessions/refresh", s.handleNativeSessionRefresh)
	reg.Public("/api/auth/sessions/revoke", s.handleNativeSessionRevoke)
	reg.Public("/api/auth/portico/handshakes", s.handlePorticoAttachmentHandshake)
	reg.Public("/api/auth/portico/sessions", s.handlePorticoSessionAttach)
	reg.Public("/api/auth/portico/start", s.handlePorticoLoginStart)
	reg.Public("/api/auth/portico/callback", s.handlePorticoLoginCallback)
	reg.Public("/api/auth/quick-connect/start", s.handleQuickConnectStart)
	reg.Public("/api/auth/quick-connect/status", s.handleQuickConnectStatus)
	reg.Public("/api/auth/quick-connect/exchange", s.handleQuickConnectExchange)
	reg.Session("/api/auth/quick-connect/pending", s.withAuth(s.handleQuickConnectPending))
	reg.Session("/api/auth/quick-connect/authorize", s.withAuth(s.handleQuickConnectAuthorize))
	reg.Session("/api/auth/quick-connect/deny", s.withAuth(s.handleQuickConnectDeny))
	reg.Public("/api/auth/tv-setup/sessions", s.handleTVSetupSessions)
	reg.Public("/api/auth/tv-setup/sessions/", s.handleTVSetupSessionRoute)
	reg.Session("/api/auth/tv-setup/grants", s.withAuth(s.handleTVSetupGrant))
	reg.Public("/api/auth/tv-setup/redeem", s.handleTVSetupRedeem)
	reg.Session("/api/auth/logout", s.withAuth(s.handleLogout))
	reg.Session("/api/auth/api-keys", s.withAuth(s.handleAPIKeys))
	reg.Session("/api/auth/api-keys/", s.withAuth(s.handleAPIKeyRoute))
}

func (s *Server) registerAccountRoutes(reg *apiroute.Registry) {
	reg.Public("/api/branding", s.handleBranding)
	reg.Public("/api/product-language/", s.handleProductLanguage)
	reg.Session("/api/account/profile", s.withAuth(s.handleAccountProfile))
	reg.Session("/api/account/password", s.withAuth(s.handleAccountPassword))
	reg.Session("/api/account/image", s.withAuth(s.handleAccountImage))
	reg.Session("/api/account/preferences", s.withAuth(s.handleAccountPreferences))
	reg.Session("/api/account/library-navigation", s.withAuth(s.handleLibraryNavigationPreferences))
	reg.Session("/api/account/sessions", s.withAuth(s.handleAccountSessions))
	reg.Session("/api/account/sessions/", s.withAuth(s.handleAccountSessionRoute))
	reg.Session("/api/account/watch-history", s.withAuth(s.handleAccountWatchHistory))
	reg.Session("/api/account/profiles", s.withAuth(s.handleAccountProfiles))
	reg.Session("/api/account/profiles/order", s.withAuth(s.handleAccountProfileOrder))
	reg.Session("/api/account/profiles/", s.withAuth(s.handleAccountProfiles))
	reg.Session("/api/account/profile-admin-proofs", s.withAuth(s.handleProfileAdministrationProof))
	reg.Session("/api/account/profile-trusts", s.withAuth(s.handleAutomaticProfileTrusts))
	reg.Session("/api/account/profile-trusts/redeem", s.withAuth(s.handleAutomaticProfileTrusts))
	reg.Session("/api/preferences", s.withAuth(s.handleViewerPreferences))
	reg.Session("/api/preferences/", s.withAuth(s.handleViewerPreferenceDocument))
	reg.Session("/api/notifications", s.withAuth(s.handleViewerNotifications))
	reg.Session("/api/notifications/", s.withAuth(s.handleViewerNotifications))
	reg.Session("/api/feedback", s.withAuth(s.handleViewerFeedback))
	reg.Session("/api/feedback/capabilities", s.withAuth(s.handleViewerFeedbackCapabilities))
	reg.Session("/api/display-preferences/", s.withAuth(s.handleDisplayPreferences))
	reg.Public("/api/localization", s.handleLocalization)
}

func (s *Server) registerSystemRoutes(reg *apiroute.Registry) {
	reg.Public("/api/readiness", s.handleReadiness)
	reg.Public("/api/system", s.handleSystem)
	reg.Session("/api/system/capabilities", s.withAuth(s.handleSystemCapabilities))
	reg.Session("/api/system/identity", s.withAuth(s.handleSystemIdentity))
	reg.Session("/api/system/identity/reset", s.withAuth(s.handleSystemIdentityReset))
	reg.Session("/api/system/time", s.withAuth(s.handleSystemTime))
	reg.Session("/api/system/diagnostics", s.withAuth(s.handleSystemDiagnostics))
	reg.Session("/api/system/startup", s.withAuth(s.handleSystemStartup))
	reg.Session("/api/system/release", s.withAuth(s.handleSystemRelease))
	reg.Session("/api/system/storage", s.withAuth(s.handleSystemStorage))
	reg.Session("/api/system/storage/paths", s.withAuth(s.handleSystemStoragePaths))
	reg.Session("/api/system/storage/cleanup", s.withAuth(s.handleSystemStorageCleanup))
	reg.Session("/api/transcode/capacity", s.withAuth(s.handleTranscodeCapacity))
	reg.Session("/api/network/connection-info", s.withAuth(s.handleNetworkConnectionInfo))
}

func (s *Server) registerRemoteAccessRoutes(reg *apiroute.Registry) {
	reg.Session("/api/remote-access/status", s.withAuth(s.handleRemoteAccessStatus))
	reg.Session("/api/remote-access/claim/start", s.withAuth(s.handleRemoteAccessClaimStart))
	reg.Session("/api/remote-access/claim/cancel", s.withAuth(s.handleRemoteAccessClaimCancel))
	reg.Session("/api/remote-access/unclaim", s.withAuth(s.handleRemoteAccessUnclaim))
	reg.Session("/api/remote-access/settings", s.withAuth(s.handleRemoteAccessSettings))
	reg.Session("/api/remote-access/test-direct", s.withAuth(s.handleRemoteAccessTestDirect))
	reg.Session("/api/remote-access/certificates/renew", s.withAuth(s.handleRemoteAccessCertificateRenew))
	reg.Session("/api/remote-access/routes/local", s.withAuth(s.handleRemoteAccessLocalRoutes))
	reg.Session("/api/remote-access/policy-sync", s.withAuth(s.handleRemoteAccessPolicySync))
	reg.Session("/api/remote-access/members/", s.withAuth(s.handleRemoteAccessMemberRoute))
	reg.Public("/api/remote-access/health", s.handleRemoteAccessHealth)
}

func (s *Server) registerLibraryAndMediaRoutes(reg *apiroute.Registry) {
	reg.Session("/api/product-contract", s.withAuth(s.handleProductContract))
	reg.Session("/api/libraries/{libraryId}/browse-capabilities", s.withAuth(s.handleLibraryBrowseCapabilities))
	reg.Session("/api/libraries/{libraryId}/browse", s.withAuth(s.handleLibraryBrowse))
	reg.Session("/api/home", s.withAuth(s.handleHome))
	reg.Session("/api/home/rows/", s.withAuth(s.handleHomeRowRoute))
	reg.Session("/api/watchlist", s.withAuth(s.handleWatchlist))
	reg.Session("/api/favorites", s.withAuth(s.handleFavorites))
	reg.Session("/api/suggestions", s.withAuth(s.handleSuggestions))
	reg.Session("/api/filesystem/browse", s.withAuth(s.handleFilesystemBrowse))
	reg.Session("/api/filesystem/directories", s.withAuth(s.handleFilesystemDirectories))
	reg.Session("/api/libraries", s.withAuth(s.handleLibraries))
	reg.Session("/api/libraries/", s.withAuth(s.handleLibraryRoute))
	reg.Session("/api/metadata/health", s.withAuth(s.handleMetadataHealth))
	reg.Session("/api/metadata/repair", s.withAuth(s.handleMetadataRepair))
	reg.Session("/api/download-preparations", s.withAuth(s.handleDownloadPreparations))
	reg.Session("/api/download-preparations/", s.withAuth(s.handleDownloadPreparations))
	reg.Session("/api/media/{id}/download-grants", s.withAuth(s.handleMediaDownloadGrantRoute))
	reg.Media("/api/media/", s.withMediaResourceAuth(s.handleMediaRoute))
	reg.Session("/api/instant-mix/", s.withAuth(s.handleInstantMix))
	reg.Session("/api/search", s.withAuth(s.handleSearch))
	reg.Session("/api/search/history", s.withAuth(s.handleSearchHistory))
	reg.Session("/api/people/media", s.withAuth(s.handlePersonMedia))
	reg.Session("/api/people/", s.withAuth(s.handlePersonRoute))
	reg.Session("/api/saved/share-candidates", s.withAuth(s.handleSavedShareCandidates))
	reg.Session("/api/playlists", s.withAuth(s.handleSavedPlaylists))
	reg.Session("/api/playlists/", s.withAuth(s.handleSavedPlaylists))
	reg.Session("/api/collections", s.withAuth(s.handleCollections))
	reg.Session("/api/collections/", s.withAuth(s.handleCollections))
	reg.Session("/api/saved-views", s.withAuth(s.handleSavedViews))
	reg.Session("/api/saved-views/", s.withAuth(s.handleSavedViews))
	reg.Session("/api/artwork/", s.withAuth(s.handleArtwork))
}

func (s *Server) registerPlaybackRoutes(reg *apiroute.Registry) {
	reg.Session("/api/playback/cast/bootstrap", s.withAuth(s.handleCastBootstrap))
	reg.Public("/api/playback/cast/redeem", s.handleCastRedeem)
	reg.Session("/api/playback/cast/reconnect", s.withAuth(s.handleCastReconnect))
	reg.Public("/api/playback/cast/sessions/", s.handleCastSessionRoute)
	reg.Session("/api/playback/bitrate-test", s.withAuth(s.handlePlaybackBitrateTest))
	reg.Session("/api/playback/active", s.withAuth(s.handlePlaybackActive))
	reg.Session("/api/playback/history/export.csv", s.withAuth(s.handlePlaybackHistoryExportCSV))
	reg.Session("/api/playback/history", s.withAuth(s.handlePlaybackHistory))
	reg.Session("/api/playback/next", s.withAuth(s.handlePlaybackNext))
	reg.Session("/api/playback/queue", s.withAuth(s.handlePlaybackQueue))
	reg.Session("/api/playback-sessions", s.withAuth(s.handlePlaybackSessionCreate))
	reg.Session("/api/playback/targets", s.withAuth(s.handlePlaybackTargets))
	reg.Session("/api/playback/receivers", s.withAuth(s.handlePlaybackReceivers))
	reg.Session("/api/playback/receivers/", s.withAuth(s.handlePlaybackReceiverRoute))
	reg.Public("/api/playback-sessions/{sessionId}/continuation", s.handlePlaybackContinuationRoute)
	reg.Session("/api/playback-sessions/", s.withAuth(s.handlePlaybackSessionRoute))
	reg.Session("/api/watch-with-friends/groups", s.withAuth(s.handleWatchWithFriendsGroups))
	reg.Session("/api/watch-with-friends/groups/", s.withAuth(s.handleWatchWithFriendsGroups))
}

func (s *Server) registerLiveTVRoutes(reg *apiroute.Registry) {
	reg.Session("/api/library-channels", s.withAuth(s.handleLibraryChannels))
	reg.Session("/api/library-channels/guide", s.withAuth(s.handleLibraryChannelsGuide))
	reg.Media("/api/library-channels/", s.withMediaResourceAuth(s.handleLibraryChannelRoute))
	reg.Session("/api/live-tv", s.withAuth(s.handleLiveTV))
	reg.Media("/api/live-tv/", s.withMediaResourceAuth(s.handleLiveTVRoute))
	reg.Session("/api/dvr/", s.withAuth(s.handleDVR))
}

func (s *Server) registerAdminRoutes(reg *apiroute.Registry) {
	reg.Session("/api/admin/dvr/status", s.withAuth(s.handleAdminDVROperationalStatus))
	reg.Session("/api/admin/library-channels", s.withAuth(s.handleAdminLibraryChannels))
	reg.Session("/api/admin/library-channels/", s.withAuth(s.handleAdminLibraryChannelRoute))
	reg.Session("/api/identity-reconciliation/reviews", s.withAuth(s.handleIdentityReconciliationReviews))
	reg.Session("/api/identity-reconciliation/reviews/", s.withAuth(s.handleIdentityReconciliationReviewRoute))
	reg.Session("/api/dlna/status", s.withAuth(s.handleDLNAStatus))
	reg.Session("/api/dashboard/activity", s.withAuth(s.handleDashboardActivity))
	reg.Session("/api/dashboard", s.withAuth(s.handleDashboard))
	reg.Session("/api/dashboard/overview-usage", s.withAuth(s.handleDashboardOverviewUsage))
	reg.Session("/api/settings/summary", s.withAuth(s.handleSettingsSummary))
	reg.Session("/api/settings", s.withAuth(s.handleSettings))
	reg.Session("/api/devices", s.withAuth(s.handleDevices))
	reg.Session("/api/devices/", s.withAuth(s.handleDevices))
	reg.Session("/api/audit-events", s.withAuth(s.handleAuditEvents))
	reg.Session("/api/backups", s.withAuth(s.handleBackups))
	reg.Session("/api/backups/", s.withAuth(s.handleBackups))
	reg.Session("/api/tasks", s.withAuth(s.handleScheduledTasks))
	reg.Session("/api/tasks/", s.withAuth(s.handleScheduledTasks))
	reg.Session("/api/logs", s.withAuth(s.handleLogs))
	reg.Session("/api/logs/stream", s.withAuth(s.handleLogStream))
	reg.Session("/api/events", s.withAuth(s.handleAppEvents))
	reg.Session("/api/events/poll", s.withAuth(s.handleAppEventsPoll))
	reg.Session("/api/client-logs", s.withAuth(s.handleClientLogs))
	reg.Session("/api/users", s.withAuth(s.handleUsers))
	reg.Session("/api/users/", s.withAuth(s.handleUserRoute))
	reg.Session("/api/activity", s.withAuth(s.handleActivity))
	reg.Session("/api/activity/", s.withAuth(s.handleActivity))
	reg.Session("/api/admin/viewer-feedback", s.withAuth(s.handleAdminViewerFeedback))
	reg.Session("/api/admin/viewer-feedback/", s.withAuth(s.handleAdminViewerFeedback))
	reg.Session("/api/admin/viewer-notification-recipients", s.withAuth(s.handleAdminViewerNotificationRecipients))
	reg.Session("/api/admin/viewer-notifications", s.withAuth(s.handleAdminViewerNotices))
}

func (s *Server) registerDLNARoutes(mux *http.ServeMux) {
	mux.HandleFunc("/dlna/device.xml", s.handleDLNADeviceDescription)
	mux.HandleFunc("/dlna/content-directory.xml", s.handleDLNAContentDirectoryDescription)
	mux.HandleFunc("/dlna/connection-manager.xml", s.handleDLNAConnectionManagerDescription)
	mux.HandleFunc("/dlna/content-directory", s.handleDLNAContentDirectoryControl)
	mux.HandleFunc("/dlna/connection-manager", s.handleDLNAConnectionManagerControl)
	mux.HandleFunc("/dlna/media/", s.handleDLNAMedia)
}
