// Code generated by tools/foundation/generate.py; DO NOT EDIT.
package foundationcontract

const (
	EnvelopeRevision           = 1
	ClientProtocolMinimum      = 1
	ClientProtocolMaximum      = 1
	APIContractDigest          = "33e17683ba7d56442d93f58766834ae624ccac6f525e89bc68548729e7137bcd"
	APIContractDigestAlgorithm = "sha256"
	APIContractIdentity        = "apps/portico-cloud/api/openapi/portico-hosted.openapi.json+apps/portico-server/api/openapi/openapi.yaml+apps/portico-server/api/openapi/portico-server.openapi.json"
	DefaultBuildVersion        = "0.0.0-development"
	DefaultBuildNumber         = "0"
	DefaultBuildChannel        = "development"
	DefaultBuildCommit         = "UNSTAMPED_DEVELOPMENT"
	DefaultEnvironment         = "development"
)

var SemanticRevisions = map[string]int{"externalAction": 1, "paginationCursor": 1, "playback": 1, "problemRecoveryAction": 1, "product": 1, "viewerProfileAuthority": 1}
var HostedAPIAuthorityByEnvironment = map[string]string{"development": "http://localhost:8080", "production": "REQUIRED_EXTERNAL_CONFIGURATION", "staging": "REQUIRED_EXTERNAL_CONFIGURATION", "test": "http://127.0.0.1:8080"}

const (
	UnknownOptionalCapabilitiesPolicy   = "ignore_and_preserve"
	UnknownRequiredSemanticsPolicy      = "reject_actionably"
	AuthorizationOnPartialUpgradePolicy = "never_broaden"
	APIContractDigestMismatchPolicy     = "allow_semantic_overlap"
)
