// Code generated by Product Contracts/scripts/compile-contracts.rb; DO NOT EDIT.
package foundationcontract

import "strings"

const (
	EnvelopeRevision           = 2
	ClientProtocolMinimum      = 1
	ClientProtocolMaximum      = 1
	APIContractDigest          = "36f41124c30a4e846e8e562d0bc090e55beb21d573b65f51463d1056392f66c4"
	APIContractDigestAlgorithm = "sha256"
	APIContractIdentity        = "portico-internal/hosted-services/api/openapi/portico-hosted.openapi.json+portico-server/api/openapi/openapi.yaml+portico-server/api/openapi/portico-server.openapi.json"
	DefaultBuildVersion        = "0.0.0-development"
	DefaultBuildNumber         = "0"
	DefaultBuildChannel        = "development"
	DefaultBuildCommit         = "UNSTAMPED_DEVELOPMENT"
	DefaultEnvironment         = "development"
)

func SemanticRevisions() map[string]int {
	return map[string]int{"externalAction": 1, "paginationCursor": 1, "playback": 1, "problemRecoveryAction": 1, "product": 2, "viewerProfileAuthority": 1}
}
func HostedAPIAuthorityByEnvironment() map[string]string {
	return map[string]string{"development": "http://localhost:8080", "production": "REQUIRED_EXTERNAL_CONFIGURATION", "staging": "REQUIRED_EXTERNAL_CONFIGURATION", "test": "http://127.0.0.1:8080"}
}
func PermissionIDs() []string {
	return []string{"playMedia", "downloadMedia", "editMetadata", "manageLyrics", "manageSubtitles", "watchWithFriends", "viewLiveTV", "playLiveTV", "viewDVR", "scheduleDVR", "manageDVR", "deleteDVRRecordings", "deleteMedia", "transcode", "manageLibraries", "manageUsers", "manageServer"}
}
func GrantablePermissionIDs() []string {
	return []string{"playMedia", "downloadMedia", "editMetadata", "manageLyrics", "manageSubtitles", "watchWithFriends", "viewLiveTV", "playLiveTV", "viewDVR", "scheduleDVR", "manageDVR", "deleteDVRRecordings", "deleteMedia", "transcode"}
}

type WorkClass string

const (
	WorkClassSecurityFence       WorkClass = "security-fence"
	WorkClassProtectedCapture    WorkClass = "protected-capture"
	WorkClassEstablishedPlayback WorkClass = "established-playback"
	WorkClassPlaybackStart       WorkClass = "playback-start"
	WorkClassInteractive         WorkClass = "interactive"
	WorkClassForegroundTransfer  WorkClass = "foreground-transfer"
	WorkClassBackgroundMedia     WorkClass = "background-media"
	WorkClassMaintenance         WorkClass = "maintenance"
)

func ParseWorkClass(value string) (WorkClass, bool) {
	class := WorkClass(strings.TrimSpace(value))
	switch class {
	case WorkClassSecurityFence, WorkClassProtectedCapture, WorkClassEstablishedPlayback, WorkClassPlaybackStart, WorkClassInteractive, WorkClassForegroundTransfer, WorkClassBackgroundMedia, WorkClassMaintenance:
		return class, true
	default:
		return "", false
	}
}

func (class WorkClass) Valid() bool {
	_, ok := ParseWorkClass(string(class))
	return ok
}

func (class WorkClass) Priority() int {
	switch class {
	case WorkClassSecurityFence:
		return 1
	case WorkClassProtectedCapture:
		return 2
	case WorkClassEstablishedPlayback:
		return 3
	case WorkClassPlaybackStart:
		return 4
	case WorkClassInteractive:
		return 5
	case WorkClassForegroundTransfer:
		return 6
	case WorkClassBackgroundMedia:
		return 7
	case WorkClassMaintenance:
		return 8
	default:
		return 0
	}
}

func CanonicalWorkClasses() []WorkClass {
	return []WorkClass{WorkClassSecurityFence, WorkClassProtectedCapture, WorkClassEstablishedPlayback, WorkClassPlaybackStart, WorkClassInteractive, WorkClassForegroundTransfer, WorkClassBackgroundMedia, WorkClassMaintenance}
}

func WorkClasses() []string {
	classes := CanonicalWorkClasses()
	values := make([]string, len(classes))
	for index, class := range classes {
		values[index] = string(class)
	}
	return values
}

func WorkClassPriorities() map[string]int {
	return map[string]int{string(WorkClassSecurityFence): 1, string(WorkClassProtectedCapture): 2, string(WorkClassEstablishedPlayback): 3, string(WorkClassPlaybackStart): 4, string(WorkClassInteractive): 5, string(WorkClassForegroundTransfer): 6, string(WorkClassBackgroundMedia): 7, string(WorkClassMaintenance): 8}
}

const (
	UnknownOptionalCapabilitiesPolicy   = "ignore_and_preserve"
	UnknownRequiredSemanticsPolicy      = "reject_actionably"
	AuthorizationOnPartialUpgradePolicy = "never_broaden"
	APIContractDigestMismatchPolicy     = "allow_semantic_overlap"
)
