import {serviceProblem, serviceText} from './presentation/service-text.ts';
/** Review one account's sign-in families. No credentials or device guesses in state. */
export interface AccountSessionReviewApi {request<T>(path:string,method?:string,body?:unknown,signal?:AbortSignal):Promise<T>}
export type AccountSessionScope=Readonly<{accountId:string;familyId:string}>;
export type AccountSessionRow=Readonly<{id:string;mode:'browser'|'native';createdAt:string;expiresAt:string;revokedAt?:string;status:'active'|'revoked'|'expired';current:boolean}>;
export type AccountSessionError=Readonly<{code:string;message:string;retryable:boolean}>;
export type AccountSessionReviewSnapshot=Readonly<{scope:AccountSessionScope;phase:'idle'|'loading'|'ready'|'error'|'ended';items:readonly AccountSessionRow[];observedAt:string;nextCursor:string;hasPrevious:boolean;pending:string|null;retryId:string|null;error:AccountSessionError|null;mutationError:AccountSessionError|null;notice:string}>;
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,max=256):v is string=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v);
const id=(v:unknown):v is string=>text(v,128)&&v.length>0;
const date=(v:unknown):v is string=>text(v,128)&&/^\d{4}-\d{2}-\d{2}T/.test(v)&&Number.isFinite(Date.parse(v));
class Failure extends Error{code:string;retryable:boolean;constructor(code:string,message:string,retryable=false){super(message);this.code=code;this.retryable=retryable;}}
function invalid():never{throw new Failure('invalid_session_review','The account service returned invalid session information.');}
function errorInfo(e:unknown):AccountSessionError{const v=e as {code?:unknown;retryable?:unknown};return Object.freeze({code:id(v?.code)?v.code:'request_failed',message:serviceProblem(e,'account','accountSessions.error.load','load'),retryable:v?.retryable===true});}
function parse(value:unknown,scope:AccountSessionScope){
 if(!object(value)||value.accountId!==scope.accountId||value.currentFamilyId!==scope.familyId||!date(value.observedAt)||!text(value.nextCursor,2048)||Object.keys(value).some(key=>!['accountId','currentFamilyId','observedAt','items','nextCursor'].includes(key))||!Array.isArray(value.items)||value.items.length>40)invalid();
 const items=value.items.map(raw=>{if(!object(raw)||!id(raw.id)||!['browser','native'].includes(raw.mode as string)||!['active','expired','revoked'].includes(raw.status as string)||!date(raw.createdAt)||!date(raw.expiresAt)||raw.revokedAt!==undefined&&!date(raw.revokedAt)||typeof raw.current!=='boolean'||raw.current!==(raw.id===scope.familyId)||raw.current&&raw.status!=='active'||raw.revokedAt!==undefined&&raw.status!=='revoked')invalid();return Object.freeze({id:raw.id,mode:raw.mode,createdAt:raw.createdAt,expiresAt:raw.expiresAt,...(raw.revokedAt?{revokedAt:raw.revokedAt}:{}),status:raw.status,current:raw.current}) as AccountSessionRow;});
 if(new Set(items.map(row=>row.id)).size!==items.length||value.nextCursor&&items.length!==40)invalid();
 return {items:Object.freeze(items),observedAt:value.observedAt,nextCursor:value.nextCursor};
}
export class AccountSessionReviewService{
 private api:AccountSessionReviewApi;private scope:AccountSessionScope;private timeout:number;private disposed=false;private generation=0;private read=0;private controls=new Set<AbortController>();private listeners=new Set<()=>void>();private state:AccountSessionReviewSnapshot;private pages=[''];private page=0;private command?:{id:string;promise:Promise<void>};private retry?:string;
 constructor(o:{api:AccountSessionReviewApi;scope:AccountSessionScope;timeoutMs?:number}){if(!id(o.scope.accountId)||!id(o.scope.familyId))throw new Error('An account and sign-in session are required.');this.scope=Object.freeze({...o.scope});this.api=o.api;this.timeout=o.timeoutMs??15000;if(!Number.isFinite(this.timeout)||this.timeout<1||this.timeout>120000)throw new Error('Invalid session request timeout.');this.state=Object.freeze({scope:this.scope,phase:'idle',items:Object.freeze([]),observedAt:'',nextCursor:'',hasPrevious:false,pending:null,retryId:null,error:null,mutationError:null,notice:''});}
 getSnapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 private publish(p:Partial<AccountSessionReviewSnapshot>){if(this.disposed)return;this.state=Object.freeze({...this.state,...p});this.listeners.forEach(fn=>fn());}
 private active(){if(this.disposed)throw new Error('Account session review is closed.');}
 dispose(){this.disposed=true;this.generation++;this.controls.forEach(c=>c.abort());this.controls.clear();this.listeners.clear();this.retry=undefined;}
 refresh():Promise<void>{this.active();return this.command?.promise??this.load(0);}
 next():Promise<void>{this.active();if(this.command||this.state.phase!=='ready'||!this.state.nextCursor)throw new Error('No next session page.');this.pages[this.page+1]=this.state.nextCursor;return this.load(this.page+1);}
 previous():Promise<void>{this.active();if(this.command||this.state.phase!=='ready'||this.page===0)throw new Error('No previous session page.');return this.load(this.page-1);}
 private ended(){this.retry=undefined;this.publish({phase:'ended',items:Object.freeze([]),pending:null,retryId:null,error:null,mutationError:null,notice:serviceText('accountSessions.youWereSignedOut')});}
 private async load(page:number){const gen=this.generation,read=++this.read;this.publish({phase:'loading',items:Object.freeze([]),error:null,nextCursor:'',hasPrevious:false});try{const raw=await this.request('/v1/account/sessions'+(this.pages[page]?'?cursor='+encodeURIComponent(this.pages[page]):''));if(this.disposed||gen!==this.generation||read!==this.read)return;const value=parse(raw,this.scope);this.page=page;if(page===0)this.pages=[''];this.publish({...value,phase:'ready',hasPrevious:page>0});}catch(e){if(this.disposed||gen!==this.generation||read!==this.read)return;if((e as {status?:number})?.status===401)this.ended();else this.publish({phase:'error',error:errorInfo(e)});}}
 revoke(familyId:string):Promise<void>{this.active();if(this.command){if(this.command.id===familyId)return this.command.promise;throw new Error('Wait for the current session request.');}if(this.retry)throw new Error('Resolve the previous session request first.');if(this.state.phase!=='ready'||!this.state.items.some(row=>row.id===familyId&&row.status==='active'))throw new Error('Refresh sessions before ending this sign-in.');return this.run(familyId);}
 retryRevoke():Promise<void>{this.active();if(!this.retry)throw new Error('No session request to retry.');return this.run(this.retry);}
 private run(familyId:string):Promise<void>{
  if(this.command)return this.command.promise;const gen=this.generation;this.read++;this.retry=familyId;this.publish({pending:familyId,retryId:null,mutationError:null,notice:''});let done!:()=>void;const promise=new Promise<void>(resolve=>{done=resolve;});this.command={id:familyId,promise};
  void(async()=>{try{const raw=await this.request('/v1/account/sessions/'+encodeURIComponent(familyId),'DELETE');if(this.disposed||gen!==this.generation)return;if(!object(raw)||raw.id!==familyId||raw.revoked!==true||raw.current!==(familyId===this.scope.familyId))invalid();this.retry=undefined;if(raw.current){this.ended();return;}this.publish({notice:serviceText('accountSessions.ended')});await this.load(0);
  }catch(e){if(this.disposed||gen!==this.generation)return;if((e as {status?:number})?.status===401){this.ended();return;}const error=errorInfo(e);const ambiguous=error.retryable||['timeout','request_failed','invalid_session_review'].includes(error.code);if(!ambiguous)this.retry=undefined;this.publish({mutationError:error,retryId:this.retry??null});await this.load(0);
  }finally{if(!this.disposed&&gen===this.generation){this.command=undefined;this.publish({pending:null});}done();}})();return promise;
 }
 private async request(path:string,method='GET'):Promise<unknown>{const c=new AbortController();this.controls.add(c);let timer:ReturnType<typeof setTimeout>|undefined;let abort:(()=>void)|undefined;try{return await Promise.race([this.api.request(path,method,undefined,c.signal),new Promise<never>((_,reject)=>{abort=()=>reject(new Failure('cancelled','Session request cancelled.'));c.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>{reject(new Failure('timeout','The request timed out. Its outcome is not confirmed. Retry the same session request.',true));c.abort();},this.timeout);})]);}finally{if(timer)clearTimeout(timer);if(abort)c.signal.removeEventListener('abort',abort);this.controls.delete(c);}}
}
