import {unreadableServerResponse} from './server-messages.ts';
/** Owner Activity observations. No playback grants, credential storage, or automatic command replay. */
import type {ContentScope,LibraryContentApi} from './library-content.ts';
export type ActivityKind='playback'|'scans';
export type PlaybackFilter='open'|'recent';
export type ScanFilter=''|'queued'|'running'|'complete'|'failed'|'cancelled';
export type ActivityScope=Readonly<{serverId:string;viewerFence:string}>;
export type CleanupStatus='not_applicable'|'not_requested'|'pending'|'unknown'|'complete';
export type PlaybackActivity=Readonly<{sessionId:string;generation:number;itemId:string;title:string;libraryId:string;libraryName:string;libraryKind:string;state:'starting'|'playing'|'paused'|'ended'|'stopped'|'failed';delivery:'direct'|'hls'|'remote';createdAt:string|null;reportedAt:string|null;positionSeconds:number|null;expiresAt:string;authorizationStopped:boolean;cleanupStatus:CleanupStatus;actions:readonly 'stop'[]}>;
export type ScanActivity=Readonly<{id:string;libraryId:string;libraryName:string;libraryKind:string;status:Exclude<ScanFilter,''>;processed:number;createdAt:string;updatedAt:string|null;finishedAt:string|null;error?:string;actions:readonly ('cancel'|'retry')[]}>;
export type ActivityError=Readonly<{code:string;message:string;serverTime?:string}>;
export type ActivityPage<T>=Readonly<{phase:'idle'|'loading'|'ready'|'error'|'refresh-required';items:readonly T[];observedAt:string|null;observationBasis:'server'|'received';cursor:string|null;nextCursor:string;canPrevious:boolean;error:ActivityError|null}>;
export type ActivityReceipt=Readonly<{scope:ActivityScope;operationId:string;sessionId:string;generation:number;state:PlaybackActivity['state'];authorizationStopped:boolean;cleanupStatus:CleanupStatus}>;
export type ActivityMutation=Readonly<{phase:'idle'|'pending'|'recovering'|'accepted'|'reconciled'|'ambiguous'|'error';kind:'stop'|'cancel'|'retry'|null;targetId:string|null;operationId:string|null;receipt:ActivityReceipt|null;error:ActivityError|null}>;
export type ActivitySnapshot=Readonly<{generation:number;scope:ContentScope;playbackFilter:PlaybackFilter;scanFilter:ScanFilter;playback:ActivityPage<PlaybackActivity>;scans:ActivityPage<ScanActivity>;mutation:ActivityMutation}>;
const obj=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const text=(v:unknown,max=2048):v is string=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v);
const id=(v:unknown):v is string=>text(v,256)&&v.length>0;
const integer=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
const date=(v:unknown):v is string=>text(v,64)&&/^\d{4}-\d\d-\d\dT/.test(v)&&Number.isFinite(Date.parse(v));
const nullableDate=(v:unknown):v is string|null=>v===null||date(v);
const kinds=['movie','tv','anime','music','audiobook'];
const states=['starting','playing','paused','ended','stopped','failed'];
const cleanups=['not_applicable','not_requested','pending','unknown','complete'];
const filters=['','queued','running','complete','failed','cancelled'];
const operation=(v:unknown):v is string=>typeof v==='string'&&/^\d{13}-[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.test(v);
class Failure extends Error{code:string;constructor(code:string){super(code);this.code=code;}}
function invalid():never{throw new Failure('invalid_activity');}
function actions<T extends string>(v:unknown,allowed:readonly T[]):readonly T[]{if(!Array.isArray(v)||v.length>allowed.length||!v.every(x=>allowed.includes(x))||new Set(v).size!==v.length)invalid();return Object.freeze([...v]);}
function playback(v:unknown):PlaybackActivity{if(!obj(v)||!id(v.sessionId)||!integer(v.generation)||v.generation<1||!id(v.itemId)||!text(v.title)||!id(v.libraryId)||!text(v.libraryName)||!kinds.includes(String(v.libraryKind))||!states.includes(String(v.state))||!['direct','hls','remote'].includes(String(v.delivery))||!nullableDate(v.createdAt)||!nullableDate(v.reportedAt)||!(v.positionSeconds===null||typeof v.positionSeconds==='number'&&Number.isFinite(v.positionSeconds)&&v.positionSeconds>=0)||!date(v.expiresAt)||typeof v.authorizationStopped!=='boolean'||!cleanups.includes(String(v.cleanupStatus)))invalid();if((v.reportedAt===null)!==(v.positionSeconds===null))invalid();const offered=actions(v.actions,['stop'] as const);if(v.authorizationStopped&&offered.length)invalid();return Object.freeze({sessionId:v.sessionId,generation:v.generation,itemId:v.itemId,title:v.title,libraryId:v.libraryId,libraryName:v.libraryName,libraryKind:v.libraryKind as string,state:v.state as PlaybackActivity['state'],delivery:v.delivery as PlaybackActivity['delivery'],createdAt:v.createdAt,reportedAt:v.reportedAt,positionSeconds:v.positionSeconds,expiresAt:v.expiresAt,authorizationStopped:v.authorizationStopped,cleanupStatus:v.cleanupStatus as CleanupStatus,actions:offered});}
function scan(v:unknown):ScanActivity{if(!obj(v)||!id(v.id)||!id(v.libraryId)||!text(v.libraryName)||!kinds.includes(String(v.libraryKind))||!filters.slice(1).includes(String(v.status))||!integer(v.processed)||!date(v.createdAt)||!nullableDate(v.updatedAt)||!nullableDate(v.finishedAt)||v.error!==undefined&&!text(v.error))invalid();return Object.freeze({id:v.id,libraryId:v.libraryId,libraryName:v.libraryName,libraryKind:v.libraryKind as string,status:v.status as ScanActivity['status'],processed:v.processed,createdAt:v.createdAt,updatedAt:v.updatedAt,finishedAt:v.finishedAt,...(v.error?{error:'Scan could not finish. Check source access and scanning tools in Libraries.'}:{}),actions:actions(v.actions,['cancel','retry'] as const)});}
function error(e:unknown):ActivityError{const v=e as {status?:number;code?:string;serverTime?:unknown};const code=v?.status===401?'unauthorized':v?.status===403?'forbidden':typeof v?.code==='string'?v.code:'request_failed';const messages:Record<string,string>={unauthorized:'Sign in directly as a server owner to view Activity.',forbidden:'This account cannot manage server activity.',permission_changed:'The owner session changed. Reopen Activity.',invalid_activity:unreadableServerResponse,invalid_activity_request:'This activity page expired or is no longer valid. Refresh the list.',stale_continuation:'Scan history changed. Refresh the list.',playback_command_conflict:'The session or original stop command changed. Refresh before choosing another action.',playback_operation_expired:'The stop command is outside its retry window. Refresh and check the server clock.',playback_command_capacity:'The server cannot retain another stop command yet. Try later.',timeout:'The server did not respond in time.',not_found:'No result was found for this command. Check activity before making another choice.'};return Object.freeze({code,message:messages[code]??'Activity could not be updated. Refresh or check the command result.',...(date(v?.serverTime)?{serverTime:v.serverTime}:{})});}
const denied=(e:ActivityError)=>['unauthorized','forbidden','permission_changed'].includes(e.code);
const emptyPage=<T>(basis:'server'|'received'):ActivityPage<T>=>Object.freeze({phase:'idle',items:Object.freeze([]),observedAt:null,observationBasis:basis,cursor:null,nextCursor:'',canPrevious:false,error:null});
const idle=():ActivityMutation=>Object.freeze({phase:'idle',kind:null,targetId:null,operationId:null,receipt:null,error:null});
type Read={seq:number;controller?:AbortController;cursor:string|null;history:(string|null)[]};
type Intent={kind:'stop'|'cancel'|'retry';targetId:string;generation?:number;operationId:string|null};
export class ActivityService{
 private api:LibraryContentApi;private scope:ContentScope;private timeoutMs:number;private operationId:()=>Promise<string>;private epoch=0;private generation=0;private disposed=false;private fence?:string;private busy=false;private commandController?:AbortController;private intent?:Intent;private channels:Record<ActivityKind,Read>={playback:{seq:0,cursor:null,history:[]},scans:{seq:0,cursor:null,history:[]}};private listeners=new Set<()=>void>();private state:ActivitySnapshot;
 constructor(o:{api:LibraryContentApi;scope:ContentScope;operationId:()=>Promise<string>;timeoutMs?:number}){if(!id(o.scope.serverId)||!text(o.scope.viewerId,1024)||!o.scope.viewerId)throw new Error('Activity needs a bound owner scope.');this.api=o.api;this.scope=Object.freeze({...o.scope});this.operationId=o.operationId;this.timeoutMs=o.timeoutMs??15000;if(!integer(this.timeoutMs)||this.timeoutMs<1||this.timeoutMs>60000)throw new Error('Invalid Activity timeout.');this.state=this.empty();}
 private empty():ActivitySnapshot{return Object.freeze({generation:this.generation,scope:this.scope,playbackFilter:'open',scanFilter:'',playback:emptyPage<PlaybackActivity>('server'),scans:emptyPage<ScanActivity>('received'),mutation:idle()});}
 getSnapshot=()=>this.state;subscribe=(f:()=>void)=>{this.listeners.add(f);return()=>this.listeners.delete(f);};
 private publish(p:Partial<ActivitySnapshot>){this.state=Object.freeze({...this.state,...p,generation:++this.generation});for(const f of this.listeners)f();}
 private active(){if(this.disposed)throw new Error('Activity is disposed.');}
 private reset(){this.epoch++;for(const c of Object.values(this.channels)){c.controller?.abort();c.seq++;c.cursor=null;c.history=[];}this.commandController?.abort();this.busy=false;this.intent=undefined;this.fence=undefined;}
 cancel(){this.active();this.reset();this.publish(this.empty());}
 setScope(scope:ContentScope,api:LibraryContentApi){this.active();if(!id(scope.serverId)||!text(scope.viewerId,1024)||!scope.viewerId)throw new Error('Invalid owner scope.');this.reset();this.scope=Object.freeze({...scope});this.api=api;this.publish(this.empty());}
 dispose(){this.reset();this.disposed=true;this.listeners.clear();}
 load(){return Promise.all([this.refresh('playback'),this.refresh('scans')]).then(()=>{});}
 selectPlayback(status:PlaybackFilter){if(!['open','recent'].includes(status))throw new Error('Invalid session filter.');this.publish({playbackFilter:status,playback:emptyPage('server')});return this.refresh('playback');}
 selectScans(status:ScanFilter){if(!filters.includes(status))throw new Error('Invalid scan filter.');this.publish({scanFilter:status,scans:emptyPage('received')});return this.refresh('scans');}
 refresh(kind:ActivityKind){this.active();this.channels[kind].cursor=null;this.channels[kind].history=[];return this.read(kind);}
 reload(kind:ActivityKind){this.active();return this.read(kind);}
 next(kind:ActivityKind){this.active();const p=this.state[kind],c=this.channels[kind];if(p.phase!=='ready'||!p.nextCursor)return Promise.resolve();c.history=[...c.history,c.cursor].slice(-64);c.cursor=p.nextCursor;return this.read(kind);}
 previous(kind:ActivityKind){this.active();const c=this.channels[kind];if(!c.history.length)return Promise.resolve();c.cursor=c.history.pop()!;return this.read(kind);}
 private scopeWire(v:unknown):ActivityScope{if(!obj(v)||v.serverId!==this.scope.serverId||!id(v.viewerFence))invalid();if(this.fence&&this.fence!==v.viewerFence)throw new Failure('permission_changed');this.fence=v.viewerFence;return Object.freeze({serverId:this.scope.serverId,viewerFence:v.viewerFence});}
 private async read(kind:ActivityKind){const c=this.channels[kind];c.controller?.abort();const controller=new AbortController(),seq=++c.seq,epoch=this.epoch,cursor=c.cursor,history=[...c.history],filter=kind==='playback'?this.state.playbackFilter:this.state.scanFilter;c.controller=controller;const prior=this.state[kind];const keep=prior.cursor===cursor;this.publish({[kind]:Object.freeze({...prior,...(!keep?{items:Object.freeze([]),observedAt:null}:{}),phase:'loading',cursor,nextCursor:'',canPrevious:history.length>0,error:null})});try{const q=new URLSearchParams({limit:'40'});if(filter)q.set('status',filter);if(cursor)q.set('cursor',cursor);const raw=await this.deadline(this.api.request('/v1/admin/'+(kind==='playback'?'playback-sessions':'jobs')+'?'+q,'GET',undefined,controller.signal),controller);if(this.disposed||epoch!==this.epoch||seq!==c.seq)return;if(!obj(raw)||!Array.isArray(raw.items)||raw.items.length>40||!text(raw.nextCursor,4096))invalid();this.scopeWire(raw.scope);if(kind==='playback'?raw.status!==filter||!date(raw.observedAt):!integer(raw.revision))invalid();const items=raw.items.map(v=>kind==='playback'?playback(v):scan(v));if(kind==='scans'&&filter&&items.some(x=>'status'in x&&x.status!==filter)||kind==='playback'&&filter==='open'&&items.some(x=>'authorizationStopped'in x&&x.authorizationStopped))invalid();const ids=items.map(x=>'sessionId'in x?x.sessionId:x.id);if(new Set(ids).size!==ids.length)invalid();if(raw.nextCursor&&(raw.nextCursor===cursor||history.includes(raw.nextCursor)))throw new Failure('stale_continuation');this.publish({[kind]:Object.freeze({phase:'ready',items:Object.freeze(items),observedAt:kind==='playback'?raw.observedAt:new Date().toISOString(),observationBasis:kind==='playback'?'server':'received',cursor,nextCursor:raw.nextCursor,canPrevious:history.length>0,error:null})});}catch(e){if(this.disposed||epoch!==this.epoch||seq!==c.seq)return;const issue=error(e);if(denied(issue)){this.reset();this.publish({...this.empty(),[kind]:Object.freeze({...emptyPage(kind==='playback'?'server':'received'),phase:'error',error:issue})});return;}const stale=['stale_continuation','invalid_activity_request','invalid_activity'].includes(issue.code);this.publish({[kind]:Object.freeze({...this.state[kind],phase:stale?'refresh-required':'error',...(stale?{items:Object.freeze([]),observedAt:null}:{}),nextCursor:'',error:issue})});}}
 stop(sessionId:string,generation:number){this.active();const row=this.state.playback.items.find(x=>x.sessionId===sessionId);if(this.state.playback.phase!=='ready'||!row||row.generation!==generation||!row.actions.includes('stop'))throw new Error('Refresh and choose an available session.');return this.command({kind:'stop',targetId:sessionId,generation,operationId:null},'/v1/admin/playback-sessions/'+encodeURIComponent(sessionId)+'/stop','POST');}
  scanAction(jobId:string,action:'cancel'|'retry'){this.active();const row=this.state.scans.items.find(x=>x.id===jobId);if(this.state.scans.phase!=='ready'||!row||!row.actions.includes(action))throw new Error('Refresh and choose an available scan action.');return this.command({kind:action,targetId:jobId,operationId:null},action==='cancel'?'/v1/admin/ingestion/jobs/'+encodeURIComponent(jobId):'/v1/libraries/'+encodeURIComponent(row.libraryId)+'/scans',action==='cancel'?'DELETE':'POST');}
 private async command(intent:Intent,path:string,method:string){if(this.busy||this.state.mutation.phase==='ambiguous')throw new Error('Check the previous command first.');this.busy=true;this.intent=intent;const epoch=this.epoch,c=new AbortController();this.commandController=c;this.publish({mutation:Object.freeze({...idle(),phase:'pending',kind:intent.kind,targetId:intent.targetId})});let submitted=false;try{if(intent.kind==='stop'){const op=await this.deadline(this.operationId(),c);if(epoch!==this.epoch||this.disposed)return;if(!operation(op))throw new Failure('invalid_activity_request');intent.operationId=op;this.publish({mutation:Object.freeze({...this.state.mutation,operationId:op})});}submitted=true;const raw=await this.deadline(this.api.request(path,method,intent.kind==='stop'?{operationId:intent.operationId,expectedGeneration:intent.generation}:undefined,c.signal),c);if(epoch!==this.epoch||this.disposed)return;const receipt=intent.kind==='stop'?this.receipt(raw,intent):null;this.publish({mutation:Object.freeze({...this.state.mutation,phase:'accepted',receipt,error:null})});await this.refresh(intent.kind==='stop'?'playback':'scans');}catch(e){if(epoch===this.epoch&&!this.disposed)this.commandError(e,submitted);}finally{if(epoch===this.epoch)this.busy=false;}}
 private receipt(raw:unknown,i:Intent):ActivityReceipt{if(!obj(raw)||raw.operationId!==i.operationId||raw.sessionId!==i.targetId||raw.generation!==i.generation||!['stopped','ended','failed'].includes(String(raw.state))||raw.authorizationStopped!==true||!cleanups.includes(String(raw.cleanupStatus)))invalid();const scope=this.scopeWire(raw.scope);return Object.freeze({scope,operationId:raw.operationId as string,sessionId:i.targetId,generation:i.generation!,state:raw.state as PlaybackActivity['state'],authorizationStopped:true,cleanupStatus:raw.cleanupStatus as CleanupStatus});}
 private commandError(e:unknown,submitted:boolean){const issue=error(e);if(denied(issue)){this.reset();this.publish({...this.empty(),playback:Object.freeze({...emptyPage<PlaybackActivity>('server'),phase:'error',error:issue})});return;}const definite=['invalid_activity_request','playback_command_conflict','playback_operation_expired','playback_command_capacity'].includes(issue.code);this.publish({mutation:Object.freeze({...this.state.mutation,phase:submitted&&!definite?'ambiguous':'error',error:issue})});}
 /** Stop recovers only the original receipt. Scan reconciliation reads current history; it does not prove the old command succeeded. */
 async recover(){this.active();if(this.busy||!this.intent||this.state.mutation.phase!=='ambiguous')return;const i=this.intent,epoch=this.epoch,c=new AbortController();this.busy=true;this.commandController=c;this.publish({mutation:Object.freeze({...this.state.mutation,phase:'recovering',error:null})});try{if(i.kind==='stop'){const raw=await this.deadline(this.api.request('/v1/admin/playback-operations/'+encodeURIComponent(i.operationId!),'GET',undefined,c.signal),c);if(epoch!==this.epoch||this.disposed)return;const receipt=this.receipt(raw,i);this.publish({mutation:Object.freeze({...this.state.mutation,phase:'accepted',receipt,error:null})});await this.refresh('playback');}else{await this.refresh('scans');if(epoch!==this.epoch||this.disposed)return;this.publish({mutation:Object.freeze({...this.state.mutation,phase:this.state.scans.phase==='ready'?'reconciled':'ambiguous',error:this.state.scans.error})});}}catch(e){if(epoch===this.epoch&&!this.disposed)this.commandError(e,true);}finally{if(epoch===this.epoch)this.busy=false;}}
 private async deadline<T>(p:Promise<T>,c:AbortController):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;let abort=()=>{};try{return await Promise.race([p,new Promise<never>((_,reject)=>{abort=()=>reject(new Failure('cancelled'));c.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>{reject(new Failure('timeout'));c.abort();},this.timeoutMs);})]);}finally{if(timer)clearTimeout(timer);c.signal.removeEventListener('abort',abort);}}
}
