import {unreadableServerResponse} from './server-messages.ts';
/** Bounded JSON consumption. Failure messages never copy untrusted response bodies. */
export class BoundedReadError extends Error{code:string;status?:number;constructor(code:string,message:string,status?:number){super(message);this.code=code;this.status=status;}}
export async function readBoundedJson<T>(response:Response,maxBytes:number,signal:AbortSignal):Promise<T>{
 if(!Number.isSafeInteger(maxBytes)||maxBytes<1||maxBytes>1048576){void response.body?.cancel().catch(()=>{});throw new Error('Invalid response byte limit.');}
 if(!response.ok){void response.body?.cancel().catch(()=>{});throw new BoundedReadError('request_failed',response.status===401||response.status===403?'Server owner access is required.':response.status===429?'Another report is being prepared. Try again shortly.':'The support report could not be read. Try again.',response.status);}
 const declared=response.headers.get('Content-Length');if(declared!==null&&(!/^\d+$/.test(declared)||Number(declared)>maxBytes)){void response.body?.cancel().catch(()=>{});throw new BoundedReadError('response_too_large','The report exceeded the allowed size.');}
 if(response.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase()!=='application/json'||!response.body){void response.body?.cancel().catch(()=>{});throw new BoundedReadError('invalid_response',unreadableServerResponse);}
 const reader=response.body.getReader();let rejectAbort!:(e:Error)=>void;const aborted=new Promise<never>((_,reject)=>rejectAbort=reject);const onAbort=()=>{void reader.cancel().catch(()=>{});rejectAbort(new BoundedReadError('cancelled','The report request was cancelled.'));};signal.addEventListener('abort',onAbort,{once:true});const chunks:Uint8Array[]=[];let total=0;
 try{if(signal.aborted)onAbort();for(;;){const next=await Promise.race([reader.read(),aborted]);if(signal.aborted)throw new BoundedReadError('cancelled','The report request was cancelled.');if(next.done)break;total+=next.value.byteLength;if(total>maxBytes)throw new BoundedReadError('response_too_large','The report exceeded the allowed size.');chunks.push(next.value);}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}try{return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes)) as T;}catch{throw new BoundedReadError('invalid_response',unreadableServerResponse);}}
 finally{signal.removeEventListener('abort',onAbort);void reader.cancel().catch(()=>{});try{reader.releaseLock();}catch{}}
}
