import {unreadableServerResponse} from './server-messages.ts';
import {parsePreparedVersion,type PreparedVersion} from './prepared-media.ts';
import {validateSubtitlePlan,type SubtitlePlan} from './subtitles.ts';
import {parseSegmentMarkerSet,type SegmentMarkerSet} from './segment-markers.ts';
import {parseQualityRungs,parseResolvedDeliveryPolicy,type QualityRung,type ResolvedDeliveryPolicy} from './delivery.ts';
/** Read-only server playback facts. No client track default, source choice or playback transition. */
import type {ContentScope,LibraryContentApi} from './library-content.ts';
export type PlayerOffersQuery=Readonly<{libraryId:string;itemId:string;sessionId?:string;revision?:string}>;
export type PlayerOfferReason='source_selection_unavailable'|'track_selection_unavailable'|'subtitle_delivery_unavailable'|'quality_selection_unavailable'|'source_unavailable';
export type PlayerOfferControl=Readonly<{id:string;enabled:boolean;reason:PlayerOfferReason|''}>;
export type PlayerOfferedStream=Readonly<{index:number;type:'video'|'audio'|'subtitle';codec:string;language?:string;title?:string;channels?:number;channelLayout?:string;default:boolean;forced:boolean;enabled:boolean;reason:PlayerOfferReason|''}>;
export type PlayerSourceOffer=Readonly<{id:string;available:boolean;container:string;videoCodec:string;audioCodec:string;width:number;height:number;duration:number;factsRevision:number;factsStatus:'known'|'unavailable'|'stale';relation:'unknown';boundary:'whole_source'|'unknown_multi_episode';enabled:false;reason:PlayerOfferReason;streams:readonly PlayerOfferedStream[];qualities:readonly QualityRung[]}>;
export type PlayerCurrentOffer=Readonly<{sessionId:string;generation:number;state:string;sourceId:string;preparedVersionId?:string;delivery:'direct'|'hls';audioSelection:'platform_default'|'server_first_audio';subtitleSelection:'platform_default'|'disabled'|'off'|'track';qualityId:string}>;
export type PlayerOffersData=Readonly<{preparedVersions:readonly PreparedVersion[];preparedOffersRevision:string;subtitlePlan:SubtitlePlan|null;subtitlePlanUnavailableReason:string|null;scope:Readonly<{serverId:string;libraryId:string;itemId:string;viewerFence:string}>;revision:string;sources:readonly PlayerSourceOffer[];current:PlayerCurrentOffer|null;controls:readonly PlayerOfferControl[];markers:SegmentMarkerSet|null;deliveryPolicy:ResolvedDeliveryPolicy|null;offersRevision:string;transcodingEnabled:boolean}>;
export type PlayerOffersSnapshot=Readonly<{generation:number;scope:ContentScope;query:PlayerOffersQuery|null;phase:'idle'|'loading'|'ready'|'error'|'refresh-required';data:PlayerOffersData|null;error:Readonly<{code:string;message:string;retryable:boolean}>|null}>;
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown,max=1024):v is string=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v);
const id=(v:unknown):v is string=>text(v,256)&&/^[A-Za-z0-9_-]+$/.test(v);
const integer=(v:unknown):v is number=>Number.isSafeInteger(v)&&Number(v)>=0;
const reasons:PlayerOfferReason[]=['source_selection_unavailable','track_selection_unavailable','subtitle_delivery_unavailable','quality_selection_unavailable','source_unavailable'];
class Failure extends Error{code:string;retryable:boolean;constructor(code:string,message:string,retryable=false){super(message);this.code=code;this.retryable=retryable;}}
function invalid():never{throw new Failure('invalid_playback_offers',unreadableServerResponse);}
function array(v:unknown,max:number):unknown[]{if(!Array.isArray(v)||v.length>max)invalid();return v;}
function disabled(v:Record<string,unknown>):{enabled:false;reason:PlayerOfferReason}{if(v.enabled!==false||!reasons.includes(v.reason as PlayerOfferReason))invalid();return {enabled:false,reason:v.reason as PlayerOfferReason};}
function control(v:unknown,ids:readonly string[]):PlayerOfferControl{if(!obj(v)||typeof v.id!=='string'||!ids.includes(v.id))invalid();if((v.id==='subtitles'||v.id==='source'||v.id==='quality')&&v.enabled===true&&v.reason==='')return Object.freeze({id:v.id,enabled:true,reason:''});return Object.freeze({id:v.id,...disabled(v)});}
function stream(v:unknown):PlayerOfferedStream{if(!obj(v)||!integer(v.index)||!['video','audio','subtitle'].includes(String(v.type))||!text(v.codec,128)||typeof v.default!=='boolean'||typeof v.forced!=='boolean')invalid();for(const key of ['language','title','channelLayout'])if(v[key]!==undefined&&!text(v[key]))invalid();if(v.channels!==undefined&&(!integer(v.channels)||v.channels>128))invalid();// An audio track may be offered for selection (by stream index on the play command); nothing else is.
 const offered=v.type==='audio'&&v.enabled===true&&v.reason==='';if(!offered&&v.reason!==(v.type==='subtitle'?'subtitle_delivery_unavailable':'track_selection_unavailable'))invalid();return Object.freeze({index:v.index,type:v.type as PlayerOfferedStream['type'],codec:v.codec,default:v.default,forced:v.forced,...(offered?{enabled:true,reason:'' as const}:disabled(v)),...(v.language===undefined?{}:{language:v.language as string}),...(v.title===undefined?{}:{title:v.title as string}),...(v.channels===undefined?{}:{channels:v.channels as number}),...(v.channelLayout===undefined?{}:{channelLayout:v.channelLayout as string})});}
function source(v:unknown):PlayerSourceOffer{if(!obj(v)||!id(v.id)||typeof v.available!=='boolean'||!text(v.container,128)||!text(v.videoCodec,128)||!text(v.audioCodec,128)||!integer(v.width)||!integer(v.height)||typeof v.duration!=='number'||!Number.isFinite(v.duration)||v.duration<0||!integer(v.factsRevision)||!['known','unavailable','stale'].includes(String(v.factsStatus))||v.relation!=='unknown'||!['whole_source','unknown_multi_episode'].includes(String(v.boundary)))invalid();if(v.factsStatus==='unavailable'?v.factsRevision!==0:v.factsRevision<1)invalid();if(v.reason!==(v.available?'source_selection_unavailable':'source_unavailable'))invalid();const streams=array(v.streams,10000).map(stream);if(v.factsStatus!=='known'&&streams.length)invalid();if(new Set(streams.map(s=>s.index)).size!==streams.length)invalid();let qualities:readonly QualityRung[];try{qualities=parseQualityRungs(v.qualities);}catch{invalid();}
// A rung must not claim a picture the source cannot provide.
if(v.height&&qualities.some(q=>q.targetDisplayHeight!==undefined&&q.targetDisplayHeight>(v.height as number)))invalid();return Object.freeze({id:v.id,available:v.available,container:v.container,videoCodec:v.videoCodec,audioCodec:v.audioCodec,width:v.width,height:v.height,duration:v.duration,factsRevision:v.factsRevision,factsStatus:v.factsStatus as PlayerSourceOffer['factsStatus'],relation:'unknown',boundary:v.boundary as PlayerSourceOffer['boundary'],...disabled(v),streams:Object.freeze(streams),qualities:Object.freeze(qualities)});}
function parse(raw:unknown,q:PlayerOffersQuery,s:ContentScope):PlayerOffersData{if(!obj(raw)||!obj(raw.scope)||raw.scope.serverId!==s.serverId||raw.scope.libraryId!==q.libraryId||raw.scope.itemId!==q.itemId||!id(raw.scope.viewerFence)||!id(raw.revision))invalid();if(q.revision&&q.revision!==raw.revision)throw new Failure('stale_playback_offer','Playback options changed. Refresh to continue.',true);const sources=array(raw.sources,10000).map(source);if(new Set(sources.map(s=>s.id)).size!==sources.length)invalid();const controls=array(raw.controls,4).map(c=>control(c,['source','audio','subtitles','quality']));if(controls.length!==4||new Set(controls.map(c=>c.id)).size!==controls.length)invalid();
let deliveryPolicy:ResolvedDeliveryPolicy|null=null;if(raw.deliveryPolicy!=null){try{deliveryPolicy=parseResolvedDeliveryPolicy(raw.deliveryPolicy);}catch{invalid();}}
if(!id(raw.offersRevision)||!/^[0-9a-f]{64}$/.test(raw.offersRevision as string)||typeof raw.transcodingEnabled!=='boolean')invalid();
// The quality control is enabled exactly when some source publishes a rung the
// viewer can actually choose beyond automatic.
if(controls.some(c=>c.id==='quality'&&c.enabled)!==sources.some(s=>s.qualities.some(q=>q.enabled&&q.kind!=='automatic')))invalid();const preparedVersions=Object.freeze(array(raw.preparedVersions??[],10000).map(v=>parsePreparedVersion(v,q.itemId)));const preparedOffersRevision=raw.preparedOffersRevision??'';if(typeof preparedOffersRevision!=='string'||(preparedVersions.length>0&&!/^[0-9a-f]{64}$/.test(preparedOffersRevision))||new Set(preparedVersions.map(v=>v.id)).size!==preparedVersions.length||preparedVersions.some(v=>v.selectable&&!sources.some(s=>s.id===v.sourceId))||controls.some(c=>c.id==='source'&&c.enabled)!==preparedVersions.some(v=>v.selectable))invalid();let current:PlayerCurrentOffer|null=null;if(raw.current!==null){const c=raw.current;if(!obj(c)||!q.sessionId||c.sessionId!==q.sessionId||!integer(c.generation)||c.generation<1||!['starting','playing','paused','stopped','ended','failed'].includes(String(c.state))||!id(c.sourceId)||!sources.some(s=>s.id===c.sourceId)||!['direct','hls'].includes(String(c.delivery))||!id(c.qualityId)||!sources.some(s=>s.id===c.sourceId&&s.qualities.some(q=>q.id===c.qualityId))||c.audioSelection!==(c.delivery==='hls'?'server_first_audio':'platform_default')||c.subtitleSelection!==(raw.subtitlePlan&&obj(raw.subtitlePlan)?raw.subtitlePlan.mode:c.delivery==='hls'?'disabled':'platform_default'))invalid();if(c.preparedVersionId!==undefined&&(!id(c.preparedVersionId)||!preparedVersions.some(v=>v.id===c.preparedVersionId)))invalid();current=Object.freeze({...(c.preparedVersionId===undefined?{}:{preparedVersionId:c.preparedVersionId as string}),sessionId:c.sessionId as string,generation:c.generation,state:c.state as string,sourceId:c.sourceId,delivery:c.delivery as PlayerCurrentOffer['delivery'],qualityId:c.qualityId as string,audioSelection:c.audioSelection as PlayerCurrentOffer['audioSelection'],subtitleSelection:c.subtitleSelection as PlayerCurrentOffer['subtitleSelection']});}else if(q.sessionId)invalid();let subtitlePlan:SubtitlePlan|null=null;if(raw.subtitlePlan!=null){try{subtitlePlan=validateSubtitlePlan(raw.subtitlePlan);}catch{invalid();}if(!current||subtitlePlan.sessionId!==current.sessionId||subtitlePlan.generation!==current.generation||subtitlePlan.sourceId!==current.sourceId||!['starting','playing','paused'].includes(current.state))invalid();}const subtitlePlanUnavailableReason=raw.subtitlePlanUnavailableReason==null?null:raw.subtitlePlanUnavailableReason;if(subtitlePlanUnavailableReason!==null&&!text(subtitlePlanUnavailableReason,128))invalid();if(subtitlePlan&&subtitlePlanUnavailableReason!==null||controls.some(c=>c.id==='subtitles'&&c.enabled)!==!!subtitlePlan)invalid();let markers:SegmentMarkerSet|null=null;if(raw.markers!=null){if(!current)invalid();const source=sources.find(s=>s.id===current!.sourceId);try{markers=parseSegmentMarkerSet(raw.markers,current.sourceId,source?.duration);}catch{invalid();}if(current.preparedVersionId!==undefined)invalid();}
return Object.freeze({markers,deliveryPolicy,offersRevision:raw.offersRevision as string,transcodingEnabled:raw.transcodingEnabled as boolean,preparedVersions,preparedOffersRevision,subtitlePlan,subtitlePlanUnavailableReason,scope:Object.freeze({serverId:s.serverId,libraryId:q.libraryId,itemId:q.itemId,viewerFence:raw.scope.viewerFence}),revision:raw.revision,sources:Object.freeze(sources),current,controls:Object.freeze(controls)});}
function bound(scope:ContentScope):ContentScope{if(!id(scope.serverId)||!text(scope.viewerId,4096)||!scope.viewerId)throw new Error('Playback options require a bound viewer and server.');return Object.freeze({...scope});}
function query(q:PlayerOffersQuery):PlayerOffersQuery{if(!obj(q)||!id(q.libraryId)||!id(q.itemId)||q.sessionId!==undefined&&!id(q.sessionId)||q.revision!==undefined&&!id(q.revision))throw new Error('Invalid playback options target.');return Object.freeze({libraryId:q.libraryId,itemId:q.itemId,...(q.sessionId?{sessionId:q.sessionId}:{}),...(q.revision?{revision:q.revision}:{})});}
export class PlayerOffersService{
 private api:LibraryContentApi;private scope:ContentScope;private timeoutMs:number;private generation=0;private disposed=false;private controller?:AbortController;private pending?:Promise<void>;private key='';private viewerFence?:string;private last?:PlayerOffersData;private listeners=new Set<()=>void>();private state:PlayerOffersSnapshot;
 constructor(options:{api:LibraryContentApi;scope:ContentScope;timeoutMs?:number}){this.api=options.api;this.scope=bound(options.scope);this.timeoutMs=options.timeoutMs??15000;if(!Number.isFinite(this.timeoutMs)||this.timeoutMs<1||this.timeoutMs>60000)throw new Error('Invalid timeout.');this.state=this.empty();}
 getSnapshot=()=>this.state;subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};
 private empty():PlayerOffersSnapshot{return Object.freeze({generation:this.generation,scope:this.scope,query:null,phase:'idle',data:null,error:null});}
 private publish(p:Partial<PlayerOffersSnapshot>){this.state=Object.freeze({...this.state,...p,generation:this.generation});for(const f of this.listeners)f();}
 private active(){if(this.disposed)throw new Error('Playback options disposed.');}
 private stop(){this.generation++;this.controller?.abort();this.pending=undefined;this.key='';}
 select(target:PlayerOffersQuery):Promise<void>{this.active();const q=query(target),key=JSON.stringify(q);if(this.pending&&key===this.key)return this.pending;this.stop();this.key=key;const g=this.generation,c=new AbortController();this.controller=c;this.publish({query:q,phase:'loading',data:null,error:null});const task=this.read(q,this.api,this.scope,c,g);this.pending=task;return task;}
 refresh(){this.active();const q=this.state.query;return q?this.select({libraryId:q.libraryId,itemId:q.itemId,...(q.sessionId?{sessionId:q.sessionId}:{})}):Promise.resolve();}
 retry(){this.active();return this.state.query?this.select(this.state.query):Promise.resolve();}
 cancel(){this.active();this.stop();this.last=undefined;this.publish(this.empty());}
 setScope(scope:ContentScope,api:LibraryContentApi){this.active();const s=bound(scope);this.stop();this.scope=s;this.api=api;this.viewerFence=undefined;this.last=undefined;this.publish(this.empty());}
 dispose(){this.stop();this.last=undefined;this.disposed=true;this.listeners.clear();}
 private async read(q:PlayerOffersQuery,api:LibraryContentApi,scope:ContentScope,c:AbortController,g:number){let timer:ReturnType<typeof setTimeout>|undefined;let abort=()=>{};try{const params=new URLSearchParams();if(q.sessionId)params.set('sessionId',q.sessionId);if(q.revision)params.set('revision',q.revision);const raw=await Promise.race([api.request<unknown>('/v1/items/'+encodeURIComponent(q.itemId)+'/playback-offers'+(params.size?'?'+params:''),'GET',undefined,c.signal),new Promise<never>((_,reject)=>{abort=()=>reject(new Failure('cancelled','Playback options canceled.'));c.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>{reject(new Failure('timeout','Playback options took too long. Try again.',true));c.abort();},this.timeoutMs);})]);if(this.disposed||g!==this.generation)return;const data=parse(raw,q,scope);if(this.viewerFence&&data.scope.viewerFence!==this.viewerFence)throw new Failure('permission_changed','The viewer changed. Reopen playback options.');if(this.last?.current&&data.current?.sessionId===this.last.current.sessionId&&data.current.generation<this.last.current.generation)throw new Failure('stale_playback_offer','Playback session changed. Refresh to continue.',true);this.viewerFence=data.scope.viewerFence;this.last=data;this.publish({phase:'ready',data,error:null});}catch(e){if(this.disposed||g!==this.generation)return;const error=e as {code?:unknown;status?:unknown;retryable?:unknown};const code=error?.status===401?'unauthorized':error?.status===403?'forbidden':typeof error?.code==='string'?error.code:'request_failed';const message=code==='stale_playback_offer'?'Playback options changed. Refresh to continue.':['unauthorized','forbidden','permission_changed'].includes(code)?'This viewer cannot read these playback options.':code==='invalid_playback_offers'?unreadableServerResponse:'Playback options could not be loaded. Try again.';if(['unauthorized','forbidden','permission_changed'].includes(code))this.last=undefined;this.publish({phase:code==='stale_playback_offer'?'refresh-required':'error',data:null,error:Object.freeze({code,message,retryable:error?.retryable===true})});}finally{if(timer)clearTimeout(timer);c.signal.removeEventListener('abort',abort);if(g===this.generation)this.pending=undefined;}}
}
