/** Owner-only source metadata and operation recovery. Credentials exist only in an
 * explicit in-flight request, never in snapshots, storage, URLs or retry queues. */
import type {ContentScope,LibraryContentApi} from './library-content.ts';
export type RemoteSource=Readonly<{id:string;kind:'rclone'|'webdav';name:string;rootPath:string;generation:number;state:string;errorCode?:string;rangeSupport:'unknown'|'conditional'|'unsupported'|'sequential';origin?:string;insecureLocal:boolean;credentialPresent:boolean;mountId?:string}>;
export type DAVConfiguration=Readonly<{name:string;root:string;username:string;password:string;keepPassword:boolean;keepConnection:boolean;insecureLocal:boolean;expectedGeneration?:number}>;
export type RemoteReceipt=Readonly<{operationId:string;accepted:true;removed:boolean;source:RemoteSource}>;
export type AnalysisPolicy=Readonly<{libraryId:string;enabled:boolean;revision:number;effective?:boolean;scanTier?:string}>;
export type RemoteState=Readonly<{sources:readonly RemoteSource[];loading:boolean;busy:boolean;error:string;operationId:string|null;ambiguous:boolean;receipt:RemoteReceipt|null;mountSupported:boolean}>;
const record=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const text=(x:unknown,n=8192):x is string=>typeof x==='string'&&x.length<=n&&!/[\x00-\x1f\x7f]/.test(x);
const integer=(x:unknown):x is number=>typeof x==='number'&&Number.isSafeInteger(x)&&x>=0;
function invalid():never{throw new Error('Invalid remote source response.');}
function source(x:unknown):RemoteSource{
 if(!record(x)||!text(x.id,256)||!x.id||!['rclone','webdav'].includes(String(x.kind))||!text(x.name,512)||!text(x.rootPath)||!integer(x.generation)||x.generation<1||!['ready','healthy','degraded','credentials_required','binary_changed','offline','rate_limited','removing','removed'].includes(String(x.state))||!['unknown','conditional','unsupported','sequential'].includes(String(x.rangeSupport))||typeof x.insecureLocal!=='boolean'||typeof x.credentialPresent!=='boolean'||x.password!==undefined||x.config!==undefined||x.username!==undefined||x.root!==undefined)invalid();
 if(x.origin!==undefined&&(!text(x.origin)||!/^https?:\/\/[^/?#@]+$/.test(x.origin)))invalid();
 if(x.errorCode!==undefined&&(!text(x.errorCode,100)||!['source_changed','credentials_required','binary_changed','range_unsupported','invalid_configuration','cursor_expired','budget_exceeded','rate_limited','cancelled','offline'].includes(x.errorCode)))invalid();
 if(x.mountId!==undefined&&!text(x.mountId,256))invalid();
 return Object.freeze({id:x.id,kind:x.kind as RemoteSource['kind'],name:x.name,rootPath:x.rootPath,generation:x.generation,state:x.state as string,rangeSupport:x.rangeSupport as RemoteSource['rangeSupport'],insecureLocal:x.insecureLocal,credentialPresent:x.credentialPresent,...(x.origin===undefined?{}:{origin:x.origin as string}),...(x.errorCode===undefined?{}:{errorCode:x.errorCode as string}),...(x.mountId===undefined?{}:{mountId:x.mountId as string})});
}
const messages:Record<string,string>={remote_source_changed:'This source changed. Refresh before submitting a new configuration.',storage_command_conflict:'The source changed or this operation conflicts with a previous receipt.',storage_operation_expired:'The operation expired. Check the device clock and refresh.',remote_credentials_required:'The provider rejected the credentials. The previous configuration remains active.',remote_invalid_configuration:'Check the endpoint, approved network access and configuration.',remote_range_unsupported:'The server cannot safely range-read this provider representation.',remote_binary_changed:'The approved rclone executable changed. Reapprove it in source configuration.',remote_budget_exceeded:'This operation exceeded the configured safety budget.',remote_rate_limited:'The provider or server is busy. Check the original receipt before retrying.',unauthorized:'Owner sign-in is required.',forbidden:'This viewer cannot manage sources.'};
function safeError(e:unknown):string{const code=record(e)&&typeof e.code==='string'?e.code:'';return messages[code]??'The operation outcome is not confirmed. Check the original receipt; credentials will not be resent automatically.';}
export class RemoteSourceService{
 private state:RemoteState={sources:[],loading:false,busy:false,error:'',operationId:null,ambiguous:false,receipt:null,mountSupported:false};
 private listeners=new Set<()=>void>();private controllers=new Set<AbortController>();private epoch=0;private read=0;private disposed=false;private viewerFence?:string;
 private api:LibraryContentApi;private scope:ContentScope;private operationId:()=>Promise<string>;
 constructor(api:LibraryContentApi,scope:ContentScope,operationId:()=>Promise<string>){if(!scope.serverId||!scope.viewerId)throw new Error('Owner scope required.');this.api=api;this.scope=Object.freeze({...scope});this.operationId=operationId;}
 getSnapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn);};
 private publish(value:Partial<RemoteState>){if(this.disposed)return;this.state=Object.freeze({...this.state,...value});for(const fn of this.listeners)fn();}
 dispose(){this.epoch++;this.disposed=true;for(const c of this.controllers)c.abort();this.controllers.clear();this.listeners.clear();this.state={...this.state,sources:[],receipt:null,operationId:null};}
 private fence(raw:unknown){if(!record(raw)||!record(raw.scope)||raw.scope.serverId!==this.scope.serverId||!text(raw.scope.viewerFence,256)||!raw.scope.viewerFence||this.viewerFence&&this.viewerFence!==raw.scope.viewerFence)invalid();this.viewerFence=raw.scope.viewerFence;}
 private async request(path:string,method='GET',body?:unknown):Promise<unknown>{if(this.disposed)throw new Error('Scope changed.');const c=new AbortController();this.controllers.add(c);let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([this.api.request(path,method,body,c.signal),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{c.abort();reject(new Error('timeout'));},45000);})]);}finally{if(timer)clearTimeout(timer);this.controllers.delete(c);}}
 async load(){const epoch=this.epoch,sequence=++this.read;this.publish({loading:true,error:''});try{const raw=await this.request('/v1/storage/sources');if(this.disposed||epoch!==this.epoch||sequence!==this.read)return;this.fence(raw);if(!record(raw)||!Array.isArray(raw.sources)||raw.sources.length>16||typeof raw.mountSupported!=='boolean')invalid();const rows=raw.sources.map(source);if(new Set(rows.map(s=>s.id)).size!==rows.length)invalid();this.publish({sources:Object.freeze(rows),mountSupported:raw.mountSupported});}catch(e){if(epoch===this.epoch&&sequence===this.read)this.publish({error:safeError(e),sources:[],receipt:null,mountSupported:false});}finally{if(epoch===this.epoch&&sequence===this.read)this.publish({loading:false});}}
 private parseReceipt(raw:unknown,op:string):RemoteReceipt{this.fence(raw);if(!record(raw)||!record(raw.receipt)||raw.receipt.operationId!==op||raw.receipt.accepted!==true||typeof raw.receipt.removed!=='boolean')invalid();return Object.freeze({operationId:op,accepted:true,removed:raw.receipt.removed,source:source(raw.receipt.source)});}
 async configure(id:string|null,input:DAVConfiguration){if(this.disposed||this.state.busy||this.state.ambiguous)throw new Error('Finish or recover the current source command first.');if(!text(input.name,100)||!input.name.trim()||!text(input.root)||!text(input.username,1024)||!text(input.password))throw new Error('Invalid connection fields.');return this.command('/v1/storage/sources/webdav'+(id?'/'+encodeURIComponent(id):''),id?'PUT':'POST',input);}
 async remove(row:RemoteSource){if(this.disposed||row.kind!=='webdav'||this.state.busy||this.state.ambiguous)throw new Error('This source cannot be removed now.');return this.command('/v1/storage/sources/webdav/'+encodeURIComponent(row.id),'DELETE',{expectedGeneration:row.generation});}
 private async command(path:string,method:string,body:unknown){const epoch=this.epoch;this.publish({busy:true,error:'',receipt:null,operationId:null});let submitted=false;try{const op=await this.operationId();if(epoch!==this.epoch||this.disposed)return;if(!/^\d{13}-[0-9a-f-]{36}$/i.test(op))invalid();this.publish({operationId:op});submitted=true;const pending=this.request(path,method,{...(body as object),operationId:op});body=undefined;const raw=await pending;if(epoch!==this.epoch||this.disposed)return;const receipt=this.parseReceipt(raw,op);this.publish({receipt,ambiguous:false});await this.load();}catch(e){if(epoch!==this.epoch||this.disposed)return;const code=record(e)?String(e.code):'';const rejected=['storage_command_conflict','storage_operation_expired','remote_invalid_configuration','remote_credentials_required','unauthorized','forbidden'].includes(code);this.publish({ambiguous:submitted&&!rejected,error:safeError(e)});}finally{body=undefined;if(epoch===this.epoch)this.publish({busy:false});}}
 async recover(){if(this.state.busy||!this.state.operationId)throw new Error('No source operation to recover.');const op=this.state.operationId,epoch=this.epoch;this.publish({busy:true,error:''});try{const raw=await this.request('/v1/storage/source-operations/'+encodeURIComponent(op));if(epoch!==this.epoch||this.disposed)return;this.publish({receipt:this.parseReceipt(raw,op),ambiguous:false});await this.load();}catch(e){if(epoch===this.epoch)this.publish({ambiguous:true,error:safeError(e)});}finally{if(epoch===this.epoch)this.publish({busy:false});}}
 async policy(libraryId:string):Promise<AnalysisPolicy>{const epoch=this.epoch,raw=await this.request('/v1/libraries/'+encodeURIComponent(libraryId)+'/strm-analysis-policy');if(epoch!==this.epoch||this.disposed)throw new Error('Scope changed.');return this.parsePolicy(raw,libraryId);}
 private parsePolicy(raw:unknown,id:string):AnalysisPolicy{this.fence(raw);if(!record(raw)||!record(raw.policy)||raw.policy.libraryId!==id||typeof raw.policy.enabled!=='boolean'||!integer(raw.policy.revision))invalid();if(raw.policy.effective!==undefined&&typeof raw.policy.effective!=='boolean'||raw.policy.scanTier!==undefined&&!['file_list_only','basic','complete','custom'].includes(String(raw.policy.scanTier)))invalid();return Object.freeze({libraryId:id,enabled:raw.policy.enabled,revision:raw.policy.revision,...(raw.policy.effective===undefined?{}:{effective:raw.policy.effective as boolean}),...(raw.policy.scanTier===undefined?{}:{scanTier:raw.policy.scanTier as string})});}
 async setPolicy(policy:AnalysisPolicy,enabled:boolean):Promise<AnalysisPolicy>{const epoch=this.epoch,raw=await this.request('/v1/libraries/'+encodeURIComponent(policy.libraryId)+'/strm-analysis-policy','PUT',{enabled,expectedRevision:policy.revision});if(epoch!==this.epoch||this.disposed)throw new Error('Scope changed.');return this.parsePolicy(raw,policy.libraryId);}
 async networkPolicy(libraryId:string):Promise<NetworkPolicy>{const epoch=this.epoch,raw=await this.request('/v1/libraries/'+encodeURIComponent(libraryId)+'/network-roots');if(epoch!==this.epoch||this.disposed)throw new Error('Scope changed.');this.fence(raw);if(!record(raw)||!record(raw.policy)||raw.policy.libraryId!==libraryId||!integer(raw.policy.revision)||!Array.isArray(raw.policy.origins)||raw.policy.origins.length>8||!raw.policy.origins.every(origin=>text(origin,8192)))invalid();return Object.freeze({libraryId,revision:raw.policy.revision,origins:Object.freeze(raw.policy.origins as string[])});}
 async setNetworkPolicy(policy:NetworkPolicy,roots:readonly string[]):Promise<NetworkPolicy>{if(roots.length>8||roots.some(root=>!text(root,8192)))throw new Error('Invalid network roots.');const epoch=this.epoch;await this.request('/v1/libraries/'+encodeURIComponent(policy.libraryId)+'/network-roots','POST',{roots,expectedRevision:policy.revision});if(epoch!==this.epoch||this.disposed)throw new Error('Scope changed.');return this.networkPolicy(policy.libraryId);}

}
export type SourceAvailability='ready'|'unavailable'|'changed'|'unsupported'|'resolve_on_play';
export async function readSourceAvailability(api:LibraryContentApi,itemId:string,signal:AbortSignal):Promise<SourceAvailability>{
 const raw=await api.request<unknown>('/v1/items/'+encodeURIComponent(itemId)+'/source-availability','GET',undefined,signal);
 if(signal.aborted)throw new Error('Source request cancelled.');
 if(!record(raw)||raw.itemId!==itemId||!['ready','unavailable','changed','unsupported','resolve_on_play'].includes(String(raw.state)))invalid();
 return raw.state as SourceAvailability;
}
export function sourceAvailabilityMessage(state:SourceAvailability):string{return {ready:'',unavailable:'This source is unavailable. Ask the server owner to check its connection.',changed:'The source changed. Ask the server owner to refresh this library before retrying.',unsupported:'This source cannot currently provide safe playback ranges.',resolve_on_play:'This external source will be checked securely by the server when playback starts.'}[state];}

export type NetworkPolicy=Readonly<{libraryId:string;revision:number;origins:readonly string[]}>;
