import {unreadableServerResponse} from './server-messages.ts';
/** One server-owned show workspace; episode details and playback have separate scoped owners. */
import {validateContentEntry,validateContentProjection,type ContentEntry,type ContentProjection,type ContentScope,type LibraryContentApi} from './library-content.ts';
export type ShowWorkspaceRoute=Readonly<{libraryId:string;showId?:string;seasonId?:string;episodeId?:string;selectedSeasonId?:string;group?:string}>;
/** How the owner asked a show to be presented (Spec — Title Pages §4). A flat show (seasons hidden, or ranges) lists its episodes under groups, not seasons. */
export type ShowSettings=Readonly<{hideSeasons:boolean;absoluteNumbering:boolean;ranges:boolean;newestFirst:boolean;revision:number}>;
export const defaultShowSettings:ShowSettings=Object.freeze({hideSeasons:false,absoluteNumbering:false,ranges:false,newestFirst:false,revision:0});
/** The episode groups a workspace can name: unassigned absolute episodes, a flat show's whole list, its specials, or a range of a hundred. */
const SHOW_GROUP=/^(unassigned_absolute|all|specials|range:\d{1,7})$/;
const group=(v:unknown):v is string=>typeof v==='string'&&SHOW_GROUP.test(v);
/** One of a show's people (cast first, then creators, writers and directors), from the server's show credits. */
export type WorkspaceShowCredit=Readonly<{id?:string;name:string;role?:string;department?:string;ordinal:number;portraitUrl?:string}>;
export type WorkspaceShow=Readonly<{id:string;libraryId:string;title:string;credits?:readonly WorkspaceShowCredit[];year?:number;overview?:string;posterUrl?:string;backdropUrl?:string;logoUrl?:string;network?:string;studio?:string;contentRating?:string;originalTitle?:string;country?:string;genres?:readonly string[];providerSourceUrl?:string;providerObservedAt?:string;libraryKind:'tv'|'anime';providerMatchStatus:string}>;
export type WorkspaceSeason=Readonly<{id:string;showId:string;number:number;title:string}>;
export type ShowWorkspaceData=Readonly<{scope:Readonly<{serverId:string;libraryId:string;viewerFence:string}>;revision:Readonly<{catalog:number;viewer:number}>;show:WorkspaceShow;seasons:readonly WorkspaceSeason[];seasonTotalCount:number;nextSeasonCursor:string;groups:readonly Readonly<{id:string;title:string;count:number}>[];selected:Readonly<{seasonId:string|null;group?:string;episodeId?:string}>;episodes:ContentProjection;nextUp?:ContentEntry;settings:ShowSettings}>;
export type ShowWorkspaceAnchor=Readonly<{expandedEpisodeId:string|null;focusedEpisodeId:string|null;scrollOffset:number}>;
export type ShowWorkspaceRestore=Readonly<{scope:ContentScope;route:ShowWorkspaceRoute;cursor:string|null;history:readonly (string|null)[];seasonCursor:string|null;seasonHistory:readonly (string|null)[];revision:ShowWorkspaceData['revision'];viewerFence:string;anchor:ShowWorkspaceAnchor;pageAnchorEpisodeId:string|null;pageAnchors:readonly string[];resolvedSelection:Readonly<{showId:string;seasonId:string|null;group?:string}>}>;
export type ShowWorkspaceError=Readonly<{code:string;message:string;retryable:boolean}>;
export type ShowWorkspaceSnapshot=Readonly<{generation:number;scope:ContentScope;route:ShowWorkspaceRoute|null;phase:'idle'|'loading'|'ready'|'error'|'refresh-required';data:ShowWorkspaceData|null;pagination:Readonly<{cursor:string|null;history:readonly (string|null)[];nextCursor:string|null;canPrevious:boolean}>;seasonPagination:Readonly<{cursor:string|null;history:readonly (string|null)[];nextCursor:string|null;canPrevious:boolean}>;anchor:ShowWorkspaceAnchor;error:ShowWorkspaceError|null}>;
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const str=(v:unknown,max=512):v is string=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v);
const id=(v:unknown):v is string=>str(v,256)&&!!v;
const count=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
class Failure extends Error{code:string;retryable:boolean;constructor(code:string,message:string,retryable=false){super(message);this.code=code;this.retryable=retryable;}}
function invalid():never{throw new Failure('invalid_show_workspace',unreadableServerResponse);}
function arr(v:unknown,max:number):unknown[]{if(!Array.isArray(v)||v.length>max)invalid();return v;}
function unique<T>(v:T[],key:(v:T)=>string):T[]{if(new Set(v.map(key)).size!==v.length)invalid();return v;}
const blankAnchor=():ShowWorkspaceAnchor=>Object.freeze({expandedEpisodeId:null,focusedEpisodeId:null,scrollOffset:0});
function bound(v:ContentScope):ContentScope{if(!record(v)||!id(v.serverId)||!str(v.viewerId,1024)||!v.viewerId)throw new Error('A server and composed authority/account/profile scope is required.');return Object.freeze({serverId:v.serverId,viewerId:v.viewerId});}
export function validateShowWorkspaceRoute(v:ShowWorkspaceRoute):ShowWorkspaceRoute{if(!record(v)||!id(v.libraryId)||!v.showId&&!v.seasonId&&!v.episodeId||v.group!==undefined&&!group(v.group)||v.group!==undefined&&v.selectedSeasonId!==undefined)throw new Error('Invalid show workspace target.');for(const k of Object.keys(v))if(!['libraryId','showId','seasonId','episodeId','selectedSeasonId','group'].includes(k))throw new Error('Unknown show workspace route field.');const result:{-readonly[K in keyof ShowWorkspaceRoute]:ShowWorkspaceRoute[K]}={libraryId:v.libraryId};for(const k of ['showId','seasonId','episodeId','selectedSeasonId'] as const)if(v[k]!==undefined){if(!id(v[k]))throw new Error('Invalid show workspace identifier.');result[k]=v[k];}if(v.group)result.group=v.group;return Object.freeze(result);}
function anchor(v:ShowWorkspaceAnchor):ShowWorkspaceAnchor{if(!record(v)||v.expandedEpisodeId!==null&&!id(v.expandedEpisodeId)||v.focusedEpisodeId!==null&&!id(v.focusedEpisodeId)||typeof v.scrollOffset!=='number'||!Number.isFinite(v.scrollOffset)||v.scrollOffset<0||v.scrollOffset>10000000)throw new Error('Invalid show workspace anchor.');return Object.freeze({...v});}
function cursor(v:unknown):string|null{if(v===null)return null;if(!str(v,4096)||!v)throw new Error('Invalid show workspace continuation.');return v;}
function parse(raw:unknown,r:ShowWorkspaceRoute,s:ContentScope,pageSize:number,seasonSize:number,page:string|null):ShowWorkspaceData{
 if(!record(raw)||!record(raw.scope)||!record(raw.revision)||!record(raw.show)||!record(raw.selected))invalid();const x=raw.scope,rev=raw.revision,show=raw.show,selected=raw.selected;
 if(x.serverId!==s.serverId||x.libraryId!==r.libraryId||!id(x.viewerFence)||!count(rev.catalog)||!count(rev.viewer)||!id(show.id)||show.libraryId!==r.libraryId||r.showId!==undefined&&show.id!==r.showId||!str(show.title,2048)||!['tv','anime'].includes(show.libraryKind as string)||!str(show.providerMatchStatus,128))invalid();
 const parsedShow:{-readonly[K in keyof WorkspaceShow]:WorkspaceShow[K]}={id:show.id,libraryId:r.libraryId,title:show.title,libraryKind:show.libraryKind as 'tv'|'anime',providerMatchStatus:show.providerMatchStatus};
  for(const k of ['posterUrl','backdropUrl'] as const)if(show[k]!==undefined){if(!str(show[k],4096)||!show[k].startsWith('/v1/metadata/show/'+encodeURIComponent(show.id)+'/art/'+(k==='posterUrl'?'poster':'backdrop')+'?'))invalid();parsedShow[k]=show[k];}
  // M32: hero facts the server already sends (network, studio, content
  // rating, genres, country, original title, logo). Additive: older servers
  // omit them and the show still parses. A present-but-malformed value is
  // dropped rather than failing the whole screen.
  if(show.logoUrl!==undefined&&str(show.logoUrl,4096)&&show.logoUrl.startsWith('/v1/metadata/show/'+encodeURIComponent(show.id)+'/art/logo?'))parsedShow.logoUrl=show.logoUrl;
  for(const k of ['network','studio','contentRating','originalTitle','country'] as const)if(show[k]!==undefined&&str(show[k],256)&&show[k])parsedShow[k]=show[k];
  if(Array.isArray(show.genres)){const genres=(show.genres as unknown[]).filter(g=>str(g,128)&&g) as string[];if(genres.length)parsedShow.genres=Object.freeze(genres);}
 if(show.year!==undefined){if(!count(show.year))invalid();parsedShow.year=show.year;}
 // Show credits (cast, creators, writers): additive, read from the workspace's own list. A malformed row is dropped, never fatal.
 if(Array.isArray(raw.showCredits)){const credits:WorkspaceShowCredit[]=[];for(const c of (raw.showCredits as unknown[]).slice(0,500)){if(!record(c)||!str(c.name,512)||!c.name)continue;const credit:{-readonly[K in keyof WorkspaceShowCredit]:WorkspaceShowCredit[K]}={name:c.name,ordinal:count(c.ordinal)?c.ordinal as number:credits.length};if(str(c.id,256)&&c.id)credit.id=c.id;if(str(c.role,512)&&c.role)credit.role=c.role;if(str(c.department,128)&&c.department)credit.department=c.department;if(str(c.portraitUrl,4096)&&c.portraitUrl)credit.portraitUrl=c.portraitUrl;credits.push(Object.freeze(credit));}if(credits.length)parsedShow.credits=Object.freeze(credits);}
 if(show.overview!==undefined){if(typeof show.overview!=='string'||show.overview.length>65536||/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(show.overview))invalid();parsedShow.overview=show.overview;}
 for(const k of ['providerSourceUrl','providerObservedAt'] as const)if(show[k]!==undefined){if(!str(show[k],4096))invalid();if(k==='providerSourceUrl'&&show[k]){try{const u=new URL(show[k] as string);if(u.protocol!=='https:'||u.username||u.password||!['www.themoviedb.org','thetvdb.com','anilist.co'].includes(u.hostname))invalid();}catch{invalid();}}parsedShow[k]=show[k];}
 if(selected.seasonId!==null&&!id(selected.seasonId)||selected.group!==undefined&&!group(selected.group)||selected.seasonId!==null&&selected.group!==undefined||selected.episodeId!==undefined&&!id(selected.episodeId))invalid();
 // Additive: a server without per-show settings sends none, and the show has the defaults.
 const st=record(raw.settings)?raw.settings:{};const settings:ShowSettings=Object.freeze({hideSeasons:st.hideSeasons===true,absoluteNumbering:st.absoluteNumbering===true,ranges:st.ranges===true,newestFirst:st.newestFirst===true,revision:count(st.revision)?st.revision:0});const flat=settings.hideSeasons||settings.ranges;
 // A flat show answers a link to one of its seasons with its own list.
 if(!flat&&(r.seasonId!==undefined&&selected.seasonId!==r.seasonId||r.selectedSeasonId!==undefined&&selected.seasonId!==r.selectedSeasonId)||r.group!==undefined&&selected.group!==r.group||r.episodeId!==selected.episodeId)invalid();
 const seasons=unique(arr(raw.seasons,seasonSize).map(v=>{if(!record(v)||!id(v.id)||v.showId!==show.id||!count(v.number)||!str(v.title,2048))invalid();return Object.freeze({id:v.id,showId:show.id as string,number:v.number,title:v.title});}),v=>v.id);
 if(!count(raw.seasonTotalCount)||raw.seasonTotalCount<seasons.length||!str(raw.nextSeasonCursor,4096)||raw.nextSeasonCursor!==''&&seasons.length===0)invalid();
 const groups=unique(arr(raw.groups,20000).map(v=>{if(!record(v)||!group(v.id)||!str(v.title,2048)||!count(v.count))invalid();return Object.freeze({id:v.id as string,title:v.title,count:v.count});}),v=>v.id);
 if(selected.group&&!groups.some(g=>g.id===selected.group))invalid();
 const episodes=validateContentProjection(raw.episodes,{libraryId:r.libraryId,view:selected.seasonId===null?'show':'season',entityId:selected.seasonId===null?show.id:selected.seasonId as string,sort:'episode',direction:'asc',category:'',q:''},s,pageSize);
 if(episodes.scope.viewerFence!==x.viewerFence||episodes.scope.libraryKind!==show.libraryKind||episodes.revision.catalog!==rev.catalog||episodes.revision.viewer!==rev.viewer||episodes.sections.length>1||episodes.query.searchMode!=='none')invalid();
 const section=episodes.sections[0];if(section&&(section.type!=='list'||section.id!==(selected.seasonId===null?selected.group:'episodes')||section.entries.length>pageSize||section.entries.some(e=>e.kind!=='episode'||e.navigation?.view!=='item'||e.navigation.entityId!==e.id||e.playback!==undefined&&(e.available!==true||e.playback.itemId!==e.id))))invalid();
  if(r.episodeId&&!page&&section?.entries[0]?.id!==r.episodeId)invalid();if(selected.seasonId===null&&!selected.group&&(section||raw.seasonTotalCount!==0))invalid();
  // M32: the server's primary action (Resume SxEy / Play next episode /
  // Play S1E1). Additive: older servers omit it and screens fall back to
  // their bounded client rule. A malformed value is dropped, never fatal.
  let nextUp:ContentEntry|undefined;if(raw.nextUp!==undefined&&raw.nextUp!==null){try{const entry=validateContentEntry(raw.nextUp);if(entry.kind==='episode')nextUp=entry;}catch{nextUp=undefined;}}
  return Object.freeze({scope:Object.freeze({serverId:s.serverId,libraryId:r.libraryId,viewerFence:x.viewerFence}),revision:Object.freeze({catalog:rev.catalog,viewer:rev.viewer}),show:Object.freeze(parsedShow),seasons:Object.freeze(seasons),seasonTotalCount:raw.seasonTotalCount,nextSeasonCursor:raw.nextSeasonCursor,groups:Object.freeze(groups),selected:Object.freeze({seasonId:selected.seasonId as string|null,...(selected.group?{group:selected.group as string}:{}),...(selected.episodeId?{episodeId:selected.episodeId as string}:{})}),episodes,...(nextUp?{nextUp}:{}),settings});
}
type Operation={route:ShowWorkspaceRoute;cursor:string|null;history:(string|null)[];seasonCursor:string|null;seasonHistory:(string|null)[];anchor:ShowWorkspaceAnchor;pageAnchors:string[];fence:{revision:ShowWorkspaceData['revision'];viewerFence:string;allowViewerAdvance?:boolean;allowCatalogAdvance?:boolean}|null};
export class ShowWorkspaceService{
 private api:LibraryContentApi;private scope:ContentScope;private pageSize:number;private seasonSize:number;private timeout:number;private generation=0;private disposed=false;private controller?:AbortController;private pending?:Promise<void>;private key='';private operation?:Operation;private state:ShowWorkspaceSnapshot;private listeners=new Set<()=>void>();
 constructor(o:{api:LibraryContentApi;scope:ContentScope;pageSize?:number;seasonPageSize?:number;timeoutMs?:number}){this.api=o.api;this.scope=bound(o.scope);this.pageSize=o.pageSize??40;this.seasonSize=o.seasonPageSize??128;this.timeout=o.timeoutMs??15000;if(!count(this.pageSize)||this.pageSize<1||this.pageSize>100||!count(this.seasonSize)||this.seasonSize<1||this.seasonSize>512||!Number.isFinite(this.timeout)||this.timeout<=0||this.timeout>120000)throw new Error('Invalid show request bounds.');this.state=this.empty();}
 private empty():ShowWorkspaceSnapshot{return Object.freeze({generation:this.generation,scope:this.scope,route:null,phase:'idle',data:null,pagination:Object.freeze({cursor:null,history:Object.freeze([]),nextCursor:null,canPrevious:false}),seasonPagination:Object.freeze({cursor:null,history:Object.freeze([]),nextCursor:null,canPrevious:false}),anchor:blankAnchor(),error:null});}
 getSnapshot=():ShowWorkspaceSnapshot=>this.state;subscribe=(fn:()=>void):(()=>void)=>{if(this.disposed)return()=>{};this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 private active(){if(this.disposed)throw new Error('Show workspace is disposed.');}
 private publish(p:Partial<ShowWorkspaceSnapshot>){if(this.disposed)return;this.state=Object.freeze({...this.state,...p});for(const f of this.listeners)f();}
 private stop(){this.generation++;this.controller?.abort();this.pending=undefined;this.key='';}
 setScope(s:ContentScope,api:LibraryContentApi){this.active();const checked=bound(s);this.stop();this.scope=checked;this.api=api;this.operation=undefined;this.publish(this.empty());}
 cancel(){this.active();this.stop();this.operation=undefined;this.publish(this.empty());}
 dispose(){this.stop();this.disposed=true;this.listeners.clear();}
 select(input:ShowWorkspaceRoute,restore?:ShowWorkspaceRestore):Promise<void>{this.active();const route=validateShowWorkspaceRoute(input);let op:Operation={route,cursor:null,history:[],seasonCursor:null,seasonHistory:[],anchor:blankAnchor(),pageAnchors:[],fence:null};if(restore){if(!record(restore)||restore.scope?.serverId!==this.scope.serverId||restore.scope?.viewerId!==this.scope.viewerId||JSON.stringify(validateShowWorkspaceRoute(restore.route))!==JSON.stringify(route)||!record(restore.revision)||!count(restore.revision.catalog)||!count(restore.revision.viewer)||!id(restore.viewerFence))throw new Error('Show restoration belongs to another scope or route.');op={route,cursor:cursor(restore.cursor),history:arr(restore.history,64).map(cursor),seasonCursor:cursor(restore.seasonCursor),seasonHistory:arr(restore.seasonHistory,64).map(cursor),anchor:anchor(restore.anchor),pageAnchors:arr(restore.pageAnchors,64).map(v=>{if(!id(v))invalid();return v;}),fence:{revision:Object.freeze({...restore.revision}),viewerFence:restore.viewerFence}};}return this.load(op);}
 selectSeason(id:string):Promise<void>{this.active();const d=this.state.data;if(!d||!d.seasons.some(v=>v.id===id)&&d.selected.seasonId!==id)throw new Error('Choose a server-provided season.');return this.select({libraryId:d.scope.libraryId,showId:d.show.id,selectedSeasonId:id});}
 selectGroup(group:string):Promise<void>{this.active();const d=this.state.data;if(!d?.groups.some(g=>g.id===group))throw new Error('Choose a server-provided episode group.');return this.select({libraryId:d.scope.libraryId,showId:d.show.id,group});}
 updateAnchor(input:ShowWorkspaceAnchor){this.active();const a=anchor(input),entries=this.state.data?.episodes.sections[0]?.entries??[];if((a.expandedEpisodeId&&!entries.some(e=>e.id===a.expandedEpisodeId))||(a.focusedEpisodeId&&!entries.some(e=>e.id===a.focusedEpisodeId)))throw new Error('Episode anchor must belong to the current server page.');if(this.operation)this.operation.anchor=a;this.publish({anchor:a});}
 captureRestore():ShowWorkspaceRestore|null{const op=this.operation,d=this.state.data;if(!op||!d||this.state.phase!=='ready')return null;return Object.freeze({scope:this.scope,route:op.route,cursor:op.cursor,history:Object.freeze([...op.history]),seasonCursor:op.seasonCursor,seasonHistory:Object.freeze([...op.seasonHistory]),revision:d.revision,viewerFence:d.scope.viewerFence,anchor:this.state.anchor,pageAnchorEpisodeId:d.episodes.sections[0]?.entries[0]?.id??null,pageAnchors:Object.freeze([...op.pageAnchors]),resolvedSelection:Object.freeze({showId:d.show.id,seasonId:d.selected.seasonId,...(d.selected.group?{group:d.selected.group}:{})})});}
 /** Own-playback return reads a fresh server target page; catalog/permission fences stay exact. No stale cursor is reused. */
 restoreAfterPlayback(restore:ShowWorkspaceRestore):Promise<void>{return this.restoreFresh(restore,false);}
 /** Explicit owner metadata publication refresh; never reuses old revision-bound cursors. */
 refreshAfterMetadata(restore:ShowWorkspaceRestore):Promise<void>{return this.restoreFresh(restore,true);}
 private restoreFresh(restore:ShowWorkspaceRestore,metadata:boolean):Promise<void>{
  this.active();if(!record(restore)||restore.scope?.serverId!==this.scope.serverId||restore.scope?.viewerId!==this.scope.viewerId||!record(restore.resolvedSelection)||!id(restore.resolvedSelection.showId)||restore.resolvedSelection.seasonId!==null&&!id(restore.resolvedSelection.seasonId)||restore.resolvedSelection.group!==undefined&&!group(restore.resolvedSelection.group)||!record(restore.revision)||!count(restore.revision.catalog)||!count(restore.revision.viewer)||!id(restore.viewerFence))throw new Error('Invalid playback restoration scope.');
  const original=validateShowWorkspaceRoute(restore.route),selected=restore.resolvedSelection,first=restore.pageAnchorEpisodeId;if(first!==null&&!id(first))throw new Error('Invalid playback page anchor.');
  const route=validateShowWorkspaceRoute({libraryId:original.libraryId,showId:selected.showId,...(selected.seasonId?{selectedSeasonId:selected.seasonId}:selected.group?{group:selected.group}:{}),...(first?{episodeId:first}:{})});
  const pageAnchors=arr(restore.pageAnchors,64).map(v=>{if(!id(v))invalid();return v;});
  return this.load({route,cursor:null,history:[],seasonCursor:null,seasonHistory:[],anchor:anchor(restore.anchor),pageAnchors,fence:{revision:Object.freeze({...restore.revision}),viewerFence:restore.viewerFence,allowViewerAdvance:true,allowCatalogAdvance:metadata}});
 }
 nextEpisodes():Promise<void>{return this.page('episodes',true);}previousEpisodes():Promise<void>{return this.page('episodes',false);}nextSeasons():Promise<void>{return this.page('seasons',true);}previousSeasons():Promise<void>{return this.page('seasons',false);}
 private page(kind:'episodes'|'seasons',next:boolean):Promise<void>{this.active();const d=this.state.data,op=this.operation;if(!d||!op||this.state.phase!=='ready')return Promise.resolve();const history=[...(kind==='episodes'?op.history:op.seasonHistory)],current=kind==='episodes'?op.cursor:op.seasonCursor;const pageAnchors=[...op.pageAnchors];if(kind==='episodes'&&!next&&!history.length&&pageAnchors.length){const first=pageAnchors.pop()!;return this.load({...op,route:validateShowWorkspaceRoute({...op.route,episodeId:first}),cursor:null,history:[],pageAnchors,anchor:blankAnchor(),fence:{revision:d.revision,viewerFence:d.scope.viewerFence,allowViewerAdvance:true}});}let value:string|null;if(next){const offered=kind==='episodes'?d.episodes.sections[0]?.nextCursor:d.nextSeasonCursor;if(!offered)return Promise.resolve();value=offered;if(history.includes(value)||value===current)throw new Error('Repeated server continuation.');history.push(current);if(history.length>64)history.shift();if(kind==='episodes'){const first=d.episodes.sections[0]?.entries[0]?.id;if(first)pageAnchors.push(first);if(pageAnchors.length>64)pageAnchors.shift();}}else{if(!history.length)return Promise.resolve();value=history.pop()!;if(kind==='episodes')pageAnchors.pop();}return this.load({...op,pageAnchors,...(kind==='episodes'?{cursor:value,history,anchor:blankAnchor()}:{seasonCursor:value,seasonHistory:history}),fence:{revision:d.revision,viewerFence:d.scope.viewerFence}});}
 /** Explicit refresh restarts both bounded pages while preserving the requested show/ancestry. */
 refresh():Promise<void>{this.active();return this.operation?this.select(this.operation.route):Promise.resolve();}
 retry():Promise<void>{this.active();if(!this.operation)return Promise.resolve();return this.state.phase==='refresh-required'?this.refresh():this.load(this.operation);}
 private load(op:Operation):Promise<void>{const key=JSON.stringify(op);if(this.pending&&this.key===key)return this.pending;this.stop();this.key=key;this.operation=op;const gen=this.generation,c=new AbortController();this.controller=c;const api=this.api,s=this.scope;const previous=this.state.data;const retained=previous&&previous.scope.libraryId===op.route.libraryId&&(op.route.showId===previous.show.id||!!op.route.episodeId&&this.state.route?.episodeId===op.route.episodeId)?previous:null;this.publish({generation:gen,route:op.route,phase:'loading',data:retained,error:null,anchor:op.anchor});const params=new URLSearchParams();for(const [k,v]of Object.entries(op.route))if(k!=='libraryId'&&v!==undefined)params.set(k,v);params.set('limit',String(this.pageSize));params.set('seasonLimit',String(this.seasonSize));if(op.cursor)params.set('cursor',op.cursor);if(op.seasonCursor)params.set('seasonCursor',op.seasonCursor);
 const promise=(async()=>{try{const raw=await this.deadline(api.request<unknown>('/v1/libraries/'+encodeURIComponent(op.route.libraryId)+'/show-workspace?'+params,'GET',undefined,c.signal),c);if(this.disposed||gen!==this.generation)return;const data=parse(raw,op.route,s,this.pageSize,this.seasonSize,op.cursor);if(op.fence?.allowCatalogAdvance&&[op.anchor.expandedEpisodeId,op.anchor.focusedEpisodeId].some(id=>id&&!data.episodes.sections[0]?.entries.some(e=>e.id===id)))throw new Failure('stale_continuation','The selected episode changed. Refresh this show.');if(op.fence&&(data.scope.viewerFence!==op.fence.viewerFence||(op.fence.allowCatalogAdvance?data.revision.catalog<op.fence.revision.catalog:data.revision.catalog!==op.fence.revision.catalog)||(op.fence.allowViewerAdvance?data.revision.viewer<op.fence.revision.viewer:data.revision.viewer!==op.fence.revision.viewer)))throw new Failure('stale_continuation','This show changed. Refresh to load its current episodes.',true);const entries=data.episodes.sections[0]?.entries??[];let a=op.anchor;if((a.expandedEpisodeId&&!entries.some(e=>e.id===a.expandedEpisodeId))||(a.focusedEpisodeId&&!entries.some(e=>e.id===a.focusedEpisodeId)))throw new Failure('stale_continuation','The requested episode anchor is no longer on this page.',true);if(op.route.episodeId&&!op.cursor&&!a.expandedEpisodeId)a=Object.freeze({...a,expandedEpisodeId:op.route.episodeId,focusedEpisodeId:op.route.episodeId});op.anchor=a;this.publish({phase:'ready',data,anchor:a,pagination:Object.freeze({cursor:op.cursor,history:Object.freeze([...op.history]),nextCursor:data.episodes.sections[0]?.nextCursor||null,canPrevious:!!op.history.length||!!op.pageAnchors.length}),seasonPagination:Object.freeze({cursor:op.seasonCursor,history:Object.freeze([...op.seasonHistory]),nextCursor:data.nextSeasonCursor||null,canPrevious:!!op.seasonHistory.length})});}catch(e){if(this.disposed||gen!==this.generation)return;const x=e as {code?:unknown;retryable?:unknown};let code=id(x?.code)?x.code:'request_failed';if(op.fence?.allowViewerAdvance&&['invalid_request','not_found'].includes(code))code='stale_continuation';this.publish({phase:['stale_continuation','invalid_cursor'].includes(code)?'refresh-required':'error',data:['request_failed','timeout','network_error','server_unavailable','service_unavailable'].includes(code)?retained:null,anchor:blankAnchor(),error:Object.freeze({code,message:e instanceof Error?e.message:'Could not load this show.',retryable:x?.retryable===true})});}finally{if(gen===this.generation){this.pending=undefined;this.key='';}}})();this.pending=promise;return promise;}
 private async deadline<T>(p:Promise<T>,c:AbortController):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined,abort:(()=>void)|undefined;try{return await Promise.race([p,new Promise<never>((_,reject)=>{abort=()=>reject(new Failure('cancelled','Show request cancelled.'));c.signal.addEventListener('abort',abort,{once:true});if(c.signal.aborted)abort();timer=setTimeout(()=>{reject(new Failure('timeout','Show request timed out.',true));c.abort();},this.timeout);})]);}finally{if(timer)clearTimeout(timer);if(abort)c.signal.removeEventListener('abort',abort);}}
}

/** Stores the owner's settings for one show; the answer is the settings with their new revision. */
export async function saveShowSettings(api:Pick<LibraryContentApi,'request'>,libraryId:string,showId:string,settings:ShowSettings):Promise<ShowSettings>{
 const raw=await api.request<unknown>('/v1/admin/libraries/'+encodeURIComponent(libraryId)+'/shows/'+encodeURIComponent(showId)+'/settings','PUT',settings);
 if(!record(raw)||!count(raw.revision))invalid();
 return Object.freeze({hideSeasons:raw.hideSeasons===true,absoluteNumbering:raw.absoluteNumbering===true,ranges:raw.ranges===true,newestFirst:raw.newestFirst===true,revision:raw.revision as number});
}
