import {unreadableServerResponse} from './server-messages.ts';
/** Managed-storage command receipts; no credential drafts, local execution or automatic intent replay. */
import type {ContentScope,LibraryContentApi} from './library-content.ts';
export type StorageAction='start'|'stop'|'restart'|'delete';
export type StorageMount=Readonly<{id:string;name:string;executable:string;executableDigest:string;mountPath:string;desiredState:'running'|'stopped';observedState:'stopped'|'starting'|'mounted'|'stopping'|'failed'|'unavailable'|'quarantined';controlRevision:number;removalPending:boolean;actions:readonly StorageAction[];error?:string;backendRevision:number;executableVersion:string;cacheBytes:number;cacheFloor:number}>;
export type StorageWireScope=Readonly<{serverId:string;viewerFence:string}>;
export type StorageData=Readonly<{scope:StorageWireScope;revision:number;limits:Readonly<{definitions:number;active:number}>;mounts:readonly StorageMount[]}>;
export type StorageReceipt=Readonly<{scope:StorageWireScope;operationId:string;mountId:string;controlRevision:number;accepted:true;deleted:boolean;mount?:StorageMount}>;
export type StorageError=Readonly<{code:string;message:string;retryable:boolean;retryAfterSeconds?:number;serverTime?:string}>;
export type StorageMutation=Readonly<{phase:'idle'|'preparing'|'pending'|'recovering'|'accepted'|'conflict'|'error'|'ambiguous';kind:'create'|'configure'|StorageAction|null;operationId:string|null;mountId:string|null;receipt:StorageReceipt|null;error:StorageError|null}>;
export type StorageManagementSnapshot=Readonly<{generation:number;scope:ContentScope;phase:'idle'|'loading'|'ready'|'error';data:StorageData|null;error:StorageError|null;mutation:StorageMutation}>;
export type StorageS3Setup=Readonly<{endpoint:string;region:string;accessKey:string;secretKey:string;bucket:string;prefix:string}>;
export type StorageConfigureInput=Readonly<{name?:string;executable?:string;remote?:string;config?:string;setup?:StorageS3Setup;cacheBytes?:number;cacheFloor?:number}>;
export type StorageCreateInput=Readonly<{name:string;executable:string;remote:string;config:string}>;
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const text=(v:unknown,max=4096):v is string=>typeof v==='string'&&v.length<=max&&!/[\x00-\x1f\x7f]/.test(v);
const id=(v:unknown):v is string=>text(v,256)&&v.length>0;
const integer=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
const operation=(v:unknown):v is string=>typeof v==='string'&&/^\d{13}-[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.test(v);
const actions:readonly StorageAction[]=['start','stop','restart','delete'];
class Failure extends Error{code:string;constructor(code:string,message:string){super(message);this.code=code;}}
function invalid():never{throw new Failure('invalid_storage','Invalid managed-storage response.');}
function array(v:unknown,max:number):unknown[]{if(!Array.isArray(v)||v.length>max)invalid();return v;}
function bound(v:ContentScope):ContentScope{if(!record(v)||!id(v.serverId)||!text(v.viewerId,1024)||!v.viewerId)throw new Error('Storage requires a bound server and owner viewer.');return Object.freeze({...v});}
function wire(v:unknown,s:ContentScope):StorageWireScope{if(!record(v)||v.serverId!==s.serverId||!id(v.viewerFence))invalid();return Object.freeze({serverId:s.serverId,viewerFence:v.viewerFence});}
function mount(v:unknown):StorageMount{if(!record(v)||!id(v.id)||!text(v.name,512)||!text(v.executable,8192)||!text(v.mountPath,8192)||typeof v.executableDigest!=='string'||!/^[a-f0-9]{64}$/.test(v.executableDigest)||!['running','stopped'].includes(String(v.desiredState))||!['stopped','starting','mounted','stopping','failed','unavailable','quarantined'].includes(String(v.observedState))||!integer(v.controlRevision)||v.controlRevision<1||typeof v.removalPending!=='boolean'||v.error!==undefined&&!text(v.error)||v.remote!==undefined||v.config!==undefined)invalid();const offered=array(v.actions,4);if(!offered.every(a=>actions.includes(a as StorageAction))||new Set(offered).size!==offered.length||v.removalPending&&offered.length)invalid();return Object.freeze({id:v.id,name:v.name,executable:v.executable,executableDigest:v.executableDigest,mountPath:v.mountPath,desiredState:v.desiredState as StorageMount['desiredState'],observedState:v.observedState as StorageMount['observedState'],controlRevision:v.controlRevision,removalPending:v.removalPending,backendRevision:integer(v.backendRevision)?v.backendRevision:1,executableVersion:text(v.executableVersion,512)?v.executableVersion:'',cacheBytes:integer(v.cacheBytes)?v.cacheBytes:0,cacheFloor:integer(v.cacheFloor)?v.cacheFloor:2147483648,actions:Object.freeze(offered as StorageAction[]),...(v.error===undefined?{}:{error:v.error as string})});}
const safeMessages:Record<string,string>={remote_credentials_required:'The provider rejected these credentials. The previous configuration remains active.',remote_binary_changed:'The approved executable changed. Explicitly approve its current fingerprint in source configuration.',remote_source_changed:'The source configuration changed. Refresh before retrying.',remote_offline:'The remote source is unavailable. Check the original command receipt before retrying.',remote_range_unsupported:'The provider does not offer safe conditional byte ranges.',remote_invalid_configuration:'Check the provider endpoint and configuration. The previous configuration remains active.',storage_allocation_recovery_required:'Private storage allocations need recovery before another configuration can be created.',storage_executable_invalid:'Choose an available native rclone executable with secure file permissions that passes version validation.',storage_config_invalid:'Check the remote name, supported provider type, and rclone configuration format.',storage_command_conflict:'The storage definition changed or this operation conflicts with its receipt. Refresh before issuing a new command.',storage_operation_expired:'This operation expired or the device clock is outside the server allowance. Check the clock and refresh; no new command was sent automatically.',storage_command_capacity:'The server cannot retain another storage receipt yet. Wait for retention cleanup before explicitly trying again.',invalid_request:'The server could not accept this storage configuration or command.',invalid_storage:unreadableServerResponse,permission_changed:'The owner session changed. Reopen storage management.',unauthorized:'Owner sign-in is required.',forbidden:'This owner session cannot manage storage.',not_found:'No receipt is available for this operation. Its outcome is still unconfirmed.',timeout:'The response timed out. Check the original operation receipt before issuing another command.',cancelled:'The request was canceled. Check the original operation receipt if it was submitted.',request_failed:'The storage response was interrupted. Check the original operation receipt before issuing another command.'};
function info(e:unknown):StorageError{const v=e as {code?:unknown;status?:unknown;retryAfterSeconds?:unknown;serverTime?:unknown};const code=typeof v?.code==='string'&&Object.hasOwn(safeMessages,v.code)?v.code:v?.status===401?'unauthorized':v?.status===403?'forbidden':v?.status===404?'not_found':'request_failed';return Object.freeze({code,message:safeMessages[code],...(typeof v?.serverTime==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/.test(v.serverTime)&&Number.isFinite(Date.parse(v.serverTime))?{serverTime:v.serverTime}:{}),retryable:['timeout','request_failed'].includes(code),...(typeof v?.retryAfterSeconds==='number'&&Number.isFinite(v.retryAfterSeconds)&&v.retryAfterSeconds>0?{retryAfterSeconds:v.retryAfterSeconds}:{})});}
const idle=():StorageMutation=>Object.freeze({phase:'idle',kind:null,operationId:null,mountId:null,receipt:null,error:null});
type Intent={kind:'create'|'configure'|StorageAction;mountId:string|null;expectedRevision?:number;operationId:string|null};
export class StorageManagementService{
 private api:LibraryContentApi;private scope:ContentScope;private readonly operationId:()=>Promise<string>;private readonly timeoutMs:number;private epoch=0;private generation=0;private disposed=false;private readSequence=0;private readController?:AbortController;private commandController?:AbortController;private pending?:Promise<void>;private recovering?:Promise<void>;private intent?:Intent;private viewerFence?:string;private listeners=new Set<()=>void>();private state:StorageManagementSnapshot;
 constructor(o:{api:LibraryContentApi;scope:ContentScope;operationId:()=>Promise<string>;timeoutMs?:number}){this.api=o.api;this.scope=bound(o.scope);this.operationId=o.operationId;this.timeoutMs=o.timeoutMs??15000;if(!Number.isFinite(this.timeoutMs)||this.timeoutMs<1||this.timeoutMs>60000)throw new Error('Invalid storage request timeout.');this.state=this.empty();}
 getSnapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>this.listeners.delete(fn);};
 private empty():StorageManagementSnapshot{return Object.freeze({generation:this.generation,scope:this.scope,phase:'idle',data:null,error:null,mutation:idle()});}
 private active(){if(this.disposed)throw new Error('Storage service is disposed.');}
 private publish(p:Partial<StorageManagementSnapshot>){this.state=Object.freeze({...this.state,...p,generation:++this.generation});for(const fn of this.listeners)fn();}
 private fence(s:StorageWireScope){if(this.viewerFence&&s.viewerFence!==this.viewerFence)throw new Failure('permission_changed','Owner changed.');this.viewerFence=s.viewerFence;}
 private reset(){this.epoch++;this.readController?.abort();this.commandController?.abort();this.pending=undefined;this.recovering=undefined;this.intent=undefined;this.viewerFence=undefined;}
 setScope(scope:ContentScope,api:LibraryContentApi){this.active();const next=bound(scope);this.reset();this.scope=next;this.api=api;this.publish(this.empty());}
 dispose(){this.reset();this.disposed=true;this.listeners.clear();}
 /** Cancel in this scope retains only the operation identifier for receipt recovery. */
 cancel(){this.active();const intent=this.intent,mutation=this.state.mutation;this.epoch++;this.readController?.abort();this.commandController?.abort();this.pending=undefined;this.recovering=undefined;this.publish({...this.empty(),mutation:intent?.operationId&&['preparing','pending','recovering','ambiguous'].includes(mutation.phase)?Object.freeze({...mutation,phase:'ambiguous',error:info(new Failure('cancelled','Canceled'))}):intent?.operationId?mutation:idle()});if(!intent?.operationId)this.intent=undefined;}
 load():Promise<void>{this.active();this.readController?.abort();const c=new AbortController(),epoch=this.epoch,seq=++this.readSequence,api=this.api;this.readController=c;this.publish({phase:'loading',data:null,error:null});return (async()=>{try{const raw=await this.deadline(api.request('/v1/storage/mounts','GET',undefined,c.signal),c);if(this.disposed||epoch!==this.epoch||seq!==this.readSequence)return;if(!record(raw)||!integer(raw.revision)||!record(raw.limits)||!integer(raw.limits.definitions)||raw.limits.definitions<1||raw.limits.definitions>8||!integer(raw.limits.active)||raw.limits.active<1||raw.limits.active>4)invalid();const s=wire(raw.scope,this.scope);this.fence(s);const mounts=array(raw.mounts,raw.limits.definitions).map(mount);if(new Set(mounts.map(m=>m.id)).size!==mounts.length)invalid();this.publish({phase:'ready',data:Object.freeze({scope:s,revision:raw.revision,limits:Object.freeze({definitions:raw.limits.definitions,active:raw.limits.active}),mounts:Object.freeze(mounts)})});}catch(e){if(this.disposed||epoch!==this.epoch||seq!==this.readSequence)return;const error=info(e);if(['unauthorized','forbidden','permission_changed'].includes(error.code)){this.reset();this.publish({...this.empty(),phase:'error',error});}else this.publish({phase:'error',data:null,error});}})();}
 refresh(){return this.load();}
 create(input:StorageCreateInput):Promise<void>{this.active();if(this.pending||this.recovering)throw new Error('Wait for the current storage command.');if(this.state.phase!=='ready'||!this.state.data)throw new Error('Load owner storage management first.');if(this.state.data.mounts.length>=this.state.data.limits.definitions)throw new Error('The server definition limit has been reached.');if(!record(input)||!text(input.name,100)||!input.name.trim()||new TextEncoder().encode(input.name.trim()).length>100||!text(input.executable,8192)||!input.executable||!text(input.remote,4096)||!input.remote||typeof input.config!=='string'||input.config.length===0||new TextEncoder().encode(input.config).length>65536||input.config.includes('\0'))throw new Error('Check the storage name, executable and connection configuration.');return this.command({kind:'create',mountId:null,operationId:null},'/v1/storage/mounts','POST',{name:input.name.trim(),executable:input.executable,remote:input.remote,config:input.config});}
 createS3(input:Readonly<{name:string;executable:string;setup:StorageS3Setup}>):Promise<void>{
  this.active();if(this.pending||this.recovering||this.state.phase!=='ready'||!this.state.data)throw new Error('Load storage and finish the current command first.');
  if(this.state.data.mounts.length>=this.state.data.limits.definitions)throw new Error('The source definition limit has been reached.');
  if(!text(input.name,100)||!input.name.trim()||!text(input.executable,8192)||!input.executable||!record(input.setup)||!Object.values(input.setup).every(v=>text(v,8192))||!input.setup.bucket||!input.setup.accessKey||!input.setup.secretKey)throw new Error('Check the managed S3 connection fields.');
  return this.command({kind:'create',mountId:null,operationId:null},'/v1/storage/mounts','POST',{name:input.name.trim(),executable:input.executable,setup:input.setup});
 }
 configure(mountId:string,expectedRevision:number,input:StorageConfigureInput):Promise<void>{
  this.active();const m=this.state.data?.mounts.find(m=>m.id===mountId);
  if(this.pending||this.recovering||this.state.phase!=='ready'||!m||m.removalPending||m.controlRevision!==expectedRevision)throw new Error('Refresh storage before changing this source.');
  if(input.config!==undefined&&(typeof input.config!=='string'||new TextEncoder().encode(input.config).length>65536||input.config.includes('\0')))throw new Error('Invalid configuration.');
  for(const key of ['name','executable','remote'] as const)if(input[key]!==undefined&&!text(input[key],8192))throw new Error('Invalid source field.');
  for(const key of ['cacheBytes','cacheFloor'] as const)if(input[key]!==undefined&&!integer(input[key]))throw new Error('Invalid cache limit.');
  return this.command({kind:'configure',mountId,expectedRevision,operationId:null},'/v1/storage/mounts/'+encodeURIComponent(mountId)+'/actions','POST',{...input,action:'configure',expectedRevision});
 }
 act(mountId:string,action:Exclude<StorageAction,'delete'>,expectedRevision:number){return this.change(mountId,action,expectedRevision);}
 remove(mountId:string,expectedRevision:number){return this.change(mountId,'delete',expectedRevision);}
 private change(mountId:string,action:StorageAction,expectedRevision:number):Promise<void>{this.active();if(this.pending||this.recovering)throw new Error('Wait for the current storage command.');const m=this.state.data?.mounts.find(m=>m.id===mountId);if(this.state.phase!=='ready'||!m||!m.actions.includes(action)||!integer(expectedRevision)||m.controlRevision!==expectedRevision)throw new Error('Refresh and choose a currently available storage action.');return this.command({kind:action,mountId,expectedRevision,operationId:null},'/v1/storage/mounts/'+encodeURIComponent(mountId)+(action==='delete'?'':'/actions'),action==='delete'?'DELETE':'POST',{expectedRevision,...(action==='delete'?{}:{action})});}
 private parseReceipt(raw:unknown,intent:Intent):StorageReceipt{if(!record(raw)||raw.operationId!==intent.operationId||!id(raw.mountId)||intent.mountId!==null&&raw.mountId!==intent.mountId||!integer(raw.controlRevision)||raw.controlRevision<1||intent.expectedRevision!==undefined&&raw.controlRevision!==intent.expectedRevision+1||raw.accepted!==true||typeof raw.deleted!=='boolean'||raw.deleted!==(intent.kind==='delete'))invalid();const scope=wire(raw.scope,this.scope);this.fence(scope);const m=raw.mount===undefined?undefined:mount(raw.mount);if(m&&(m.id!==raw.mountId||m.controlRevision!==raw.controlRevision||m.removalPending!==raw.deleted))invalid();return Object.freeze({scope,operationId:raw.operationId as string,mountId:raw.mountId,controlRevision:raw.controlRevision,accepted:true,deleted:raw.deleted,...(m?{mount:m}:{})});}
 private command(intent:Intent,path:string,method:string,body:Record<string,unknown>):Promise<void>{const c=new AbortController(),epoch=this.epoch;this.commandController=c;this.intent=intent;this.publish({mutation:Object.freeze({...idle(),phase:'preparing',kind:intent.kind,mountId:intent.mountId})});const task=(async()=>{let submitted=false;try{const op=await this.deadline(this.operationId(),c);if(this.disposed||epoch!==this.epoch)return;if(!operation(op))throw new Failure('invalid_request','Invalid operation identifier');intent.operationId=op;this.publish({mutation:Object.freeze({...this.state.mutation,phase:'pending',operationId:op})});submitted=true;const request=this.api.request(path,method,{...body,operationId:op},c.signal);body={};const raw=await this.deadline(request,c);if(this.disposed||epoch!==this.epoch)return;const receipt=this.parseReceipt(raw,intent);this.publish({mutation:Object.freeze({...this.state.mutation,phase:'accepted',mountId:receipt.mountId,receipt,error:null})});await this.load();}catch(e){body={};if(this.disposed||epoch!==this.epoch)return;this.commandError(e,intent,submitted);}finally{body={};if(epoch===this.epoch&&this.commandController===c)this.pending=undefined;}})();this.pending=task;return task;}
 private commandError(e:unknown,intent:Intent,submitted:boolean){const error=info(e);if(['unauthorized','forbidden','permission_changed'].includes(error.code)){this.reset();this.publish({...this.empty(),phase:'error',error});return;}const definite=['storage_allocation_recovery_required','storage_command_conflict','storage_operation_expired','storage_command_capacity','storage_executable_invalid','storage_config_invalid','invalid_request'].includes(error.code);this.publish({mutation:Object.freeze({...this.state.mutation,kind:intent.kind,operationId:intent.operationId,mountId:intent.mountId,receipt:null,phase:error.code==='storage_command_conflict'?'conflict':submitted&&!definite?'ambiguous':'error',error})});}
 /** Lookup the original receipt. A missing receipt never grants permission to replay create/config. */
 recover():Promise<void>{this.active();if(this.pending)throw new Error('Wait for the current storage command.');if(this.recovering)return this.recovering;const intent=this.intent;if(!intent?.operationId)throw new Error('There is no submitted operation to recover.');const epoch=this.epoch,c=new AbortController();this.commandController=c;this.publish({mutation:Object.freeze({...this.state.mutation,phase:'recovering',error:null})});const task=(async()=>{try{const raw=await this.deadline(this.api.request('/v1/storage/operations/'+encodeURIComponent(intent.operationId!),'GET',undefined,c.signal),c);if(this.disposed||epoch!==this.epoch)return;const receipt=this.parseReceipt(raw,intent);this.publish({mutation:Object.freeze({...this.state.mutation,phase:'accepted',mountId:receipt.mountId,receipt,error:null})});await this.load();}catch(e){if(!this.disposed&&epoch===this.epoch)this.commandError(e,intent,true);}finally{if(epoch===this.epoch)this.recovering=undefined;}})();this.recovering=task;return task;}
 private async deadline<T>(promise:Promise<T>,c:AbortController):Promise<T>{if(c.signal.aborted)throw new Failure('cancelled','Canceled');let timer:ReturnType<typeof setTimeout>|undefined;let abort=()=>{};try{return await Promise.race([promise,new Promise<never>((_,reject)=>{abort=()=>reject(new Failure('cancelled','Canceled'));c.signal.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>{reject(new Failure('timeout','Timed out'));c.abort();},this.timeoutMs);})]);}finally{if(timer)clearTimeout(timer);c.signal.removeEventListener('abort',abort);}}
}
