import {unreadableServerResponse} from './server-messages.ts';
import type {ContentScope} from './library-content.ts';
export type SupportCounts=Readonly<{total:number;byState:Readonly<Record<string,number>>}>;
export type SupportReport=Readonly<{schemaVersion:1;observedAt:string;build:Readonly<{version:string|null;buildId:string|null;sourceDigest:string|null;builtAt:string|null;targetOS:string;targetArch:string;goVersion:string|null}>;database:'readable';hostedConfigured:boolean;libraries:SupportCounts;scans:SupportCounts;mounts:Readonly<{available:boolean;counts:SupportCounts|null}>;recentScanFailures:Readonly<{limit:20;hasMore:boolean;items:readonly Readonly<{code:'source_unavailable'|'scan_failed';createdAt:string|null;updatedAt:string|null;finishedAt:string|null;processed:number|null}>[]}>}>;
export interface SupportApi{requestBounded<T>(path:string,maxBytes:number,signal:AbortSignal):Promise<T>}
export const supportFilename='portico-support-report.json';
const maxBytes=32768,record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v),count=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
const date=(v:unknown):v is string=>typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,9})?Z$/.test(v)&&Number.isFinite(Date.parse(v));
const build=(v:unknown):v is string|null=>v===null||typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9._+-]{0,127}$/.test(v);
function invalid():never{throw Object.assign(new Error(unreadableServerResponse),{code:'invalid_support_report'});}
function counts(raw:unknown,allowed:readonly string[]):SupportCounts{if(!record(raw)||!count(raw.total)||!record(raw.byState)||Object.keys(raw.byState).length>allowed.length)invalid();let sum=0;const byState:Record<string,number>={};for(const [name,n]of Object.entries(raw.byState)){if(!allowed.includes(name)||!count(n))invalid();sum+=n;byState[name]=n;}if(sum!==raw.total||!count(sum))invalid();return Object.freeze({total:raw.total,byState:Object.freeze(byState)});}
export function parseSupportReport(value:unknown):SupportReport{
 if(!record(value)||value.schemaVersion!==1||!date(value.observedAt)||value.database!=='readable'||typeof value.hostedConfigured!=='boolean'||!record(value.build)||!record(value.mounts)||typeof value.mounts.available!=='boolean'||!record(value.recentScanFailures))invalid();
 const b=value.build;for(const key of ['version','buildId','sourceDigest','goVersion'])if(!build(b[key]))invalid();if(!(b.builtAt===null||date(b.builtAt))||typeof b.targetOS!=='string'||typeof b.targetArch!=='string'||!build(b.targetOS)||!build(b.targetArch))invalid();
 const recent=value.recentScanFailures;if(recent.limit!==20||typeof recent.hasMore!=='boolean'||!Array.isArray(recent.items)||recent.items.length>20||recent.hasMore&&recent.items.length!==20)invalid();
 const items=recent.items.map(v=>{if(!record(v)||!['source_unavailable','scan_failed'].includes(v.code as string)||![v.createdAt,v.updatedAt,v.finishedAt].every(d=>d===null||date(d))||!(v.processed===null||count(v.processed)))invalid();return Object.freeze({code:v.code as 'source_unavailable'|'scan_failed',createdAt:v.createdAt as string|null,updatedAt:v.updatedAt as string|null,finishedAt:v.finishedAt as string|null,processed:v.processed as number|null});});
 const mounts=value.mounts.available?counts(value.mounts.counts,['stopped','starting','mounted','stopping','failed','unavailable','quarantined','unknown']):null;if(!value.mounts.available&&value.mounts.counts!==null)invalid();
 return Object.freeze({schemaVersion:1,observedAt:value.observedAt,build:Object.freeze({version:b.version as string|null,buildId:b.buildId as string|null,sourceDigest:b.sourceDigest as string|null,builtAt:b.builtAt as string|null,targetOS:b.targetOS,targetArch:b.targetArch,goVersion:b.goVersion as string|null}),database:'readable',hostedConfigured:value.hostedConfigured,libraries:counts(value.libraries,['movie','tv','anime','music','audiobook','unknown']),scans:counts(value.scans,['queued','running','complete','failed','cancelled','unknown']),mounts:Object.freeze({available:value.mounts.available,counts:mounts}),recentScanFailures:Object.freeze({limit:20,hasMore:recent.hasMore,items:Object.freeze(items)})});
}
export type SupportSnapshot=Readonly<{phase:'idle'|'loading'|'ready'|'error';report:SupportReport|null;error:string|null}>;
export class SupportDiagnosticsService{
 private state:SupportSnapshot=Object.freeze({phase:'idle',report:null,error:null});private listeners=new Set<()=>void>();private disposed=false;private generation=0;private controller?:AbortController;private fence?:string;private busy=false;private scope:ContentScope;
 private options:{api:SupportApi;scope:ContentScope;timeoutMs?:number};
 constructor(options:{api:SupportApi;scope:ContentScope;timeoutMs?:number}){this.options=options;if(!options.scope.serverId||!options.scope.viewerId)throw new Error('A selected server owner is required.');this.scope=Object.freeze({...options.scope});if(options.timeoutMs!==undefined&&(!Number.isFinite(options.timeoutMs)||options.timeoutMs<=0||options.timeoutMs>30000))throw new Error('Invalid support deadline.');}
 getSnapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};private publish(v:SupportSnapshot){if(this.disposed)return;this.state=Object.freeze(v);for(const fn of this.listeners)fn();}
 dispose(){this.disposed=true;this.generation++;this.controller?.abort();this.listeners.clear();}
 async prepare():Promise<SupportReport|null>{if(this.disposed||this.busy)return null;this.busy=true;const generation=++this.generation,c=new AbortController();this.controller=c;this.publish({phase:'loading',report:null,error:null});let timer:ReturnType<typeof setTimeout>|undefined;
  try{const raw=await Promise.race([this.options.api.requestBounded<unknown>('/v1/admin/support-report',maxBytes,c.signal),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{c.abort();reject(new Error('The support report timed out. Try again.'));},this.options.timeoutMs??10000);})]);if(this.disposed||generation!==this.generation||c.signal.aborted)return null;if(!record(raw)||!record(raw.scope)||raw.scope.serverId!==this.scope.serverId||typeof raw.scope.viewerFence!=='string'||!/^[a-f0-9]{64}$/.test(raw.scope.viewerFence)||this.fence&&this.fence!==raw.scope.viewerFence)invalid();const report=parseSupportReport(raw.report);this.fence=raw.scope.viewerFence;this.publish({phase:'ready',report,error:null});return report;
  }catch(e){if(!this.disposed&&generation===this.generation)this.publish({phase:'error',report:null,error:e instanceof Error?e.message:'The support report could not be prepared.'});return null;}finally{if(timer)clearTimeout(timer);if(generation===this.generation){this.busy=false;this.controller=undefined;}}
 }
 async download():Promise<{filename:string;content:string}|null>{const report=await this.prepare();if(!report||this.disposed||this.state.report!==report)return null;const content=JSON.stringify(report,null,2)+'\n';if(new TextEncoder().encode(content).length>maxBytes){this.publish({phase:'error',report:null,error:'The support report exceeded the allowed size.'});return null;}return {filename:supportFilename,content};}
}
