// Package mediaartifact owns closed generated bytes. A content identity is not
// a publication record, a source version, or authority to access media.
package mediaartifact

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"hash"
	"io"
	"os"
	"path/filepath"
	"portico.local/server/internal/artifactlease"
	"strings"
	"sync"
)

var (
	ErrIdentity = errors.New("closed artifact identity mismatch")
	ErrState    = errors.New("artifact writer or store is closed")
	ErrLimit    = errors.New("artifact output exceeded its physical byte limit")
	ErrLeased   = errors.New("closed artifact has active read leases")
	ErrPrivate  = errors.New("artifact cache requires private canonical directories")
)

// Object identifies closed output bytes only. Source provenance, presentation
// mapping and retention belong to the authoritative publication repository.
type Object struct {
	Digest string
	Size   int64
}

func validObject(o Object) bool {
	if o.Size <= 0 || len(o.Digest) != 64 || strings.ToLower(o.Digest) != o.Digest {
		return false
	}
	_, err := hex.DecodeString(o.Digest)
	return err == nil
}

type Store struct {
	mu                     sync.Mutex
	root, staging, objects string
	readers                map[string]int
	writers                map[*Writer]bool
	closed                 bool
}

func New(root string) (*Store, error) { return newStore(root, syncDirectory) }

// Root is the directory this store owns. A producer asks so it can check that
// the volume it is about to write gigabytes onto has room for them — the volume
// that, on a single-disk home server, also holds server.sqlite.
func (s *Store) Root() string { return s.root }

func newStore(root string, syncDir func(string) error) (*Store, error) {
	if !filepath.IsAbs(root) {
		return nil, ErrPrivate
	}
	root = filepath.Clean(root)
	if err := os.MkdirAll(root, 0700); err != nil {
		return nil, err
	}
	canonical, err := filepath.EvalSymlinks(root)
	if err != nil || canonical != root {
		return nil, ErrPrivate
	}
	for _, path := range []string{root, filepath.Join(root, "staging"), filepath.Join(root, "objects")} {
		if err = os.MkdirAll(path, 0700); err != nil {
			return nil, err
		}
		info, e := os.Lstat(path)
		if e != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return nil, ErrPrivate
		}
	}
	// Every owned directory and its parent entry must be durable before callers
	// can rely on a later sealed object. Sync ancestry on retries too: a failed
	// prior creation may have left existing but not durably linked ancestors.
	for _, path := range []string{filepath.Join(root, "staging"), filepath.Join(root, "objects")} {
		if err = syncDir(path); err != nil {
			return nil, err
		}
	}
	for path := root; ; path = filepath.Dir(path) {
		if err = syncDir(path); err != nil {
			return nil, err
		}
		if filepath.Dir(path) == path {
			break
		}
	}
	return &Store{root: root, staging: filepath.Join(root, "staging"), objects: filepath.Join(root, "objects"), readers: map[string]int{}, writers: map[*Writer]bool{}}, nil
}
func (s *Store) Begin(maxBytes int64) (*Writer, error) {
	if maxBytes <= 0 {
		return nil, ErrLimit
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return nil, ErrState
	}
	file, err := os.CreateTemp(s.staging, "output-")
	if err != nil {
		return nil, err
	}
	writer := &Writer{store: s, file: file, path: file.Name(), hash: sha256.New(), limit: maxBytes}
	s.writers[writer] = true
	return writer, nil
}

type Writer struct {
	mu          sync.Mutex
	store       *Store
	file        *os.File
	path        string
	hash        hash.Hash
	size, limit int64
	retained    bool
	ended       bool
	failure     error
}

func (w *Writer) Write(data []byte) (int, error) {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.ended {
		return 0, ErrState
	}
	if w.failure != nil {
		return 0, w.failure
	}
	if int64(len(data)) > w.limit-w.size {
		w.failure = ErrLimit
		return 0, ErrLimit
	}
	n, err := w.file.Write(data)
	w.hash.Write(data[:n])
	w.size += int64(n)
	if err == nil && n != len(data) {
		err = io.ErrShortWrite
	}
	if err != nil {
		w.failure = err
	}
	return n, err
}
func (w *Writer) abortLocked() error {
	if w.ended {
		return nil
	}
	w.ended = true
	err := w.file.Close()
	remove := os.Remove(w.path)
	w.store.mu.Lock()
	delete(w.store.writers, w)
	w.store.mu.Unlock()
	return errors.Join(err, remove)
}
func (w *Writer) Abort() error { w.mu.Lock(); defer w.mu.Unlock(); return w.abortLocked() }

// Seal is called only after the actual producer exits successfully and its
// source evidence is revalidated. It does not authorize/publish the result.
func (w *Writer) Seal(ctx context.Context) (Object, error) {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.retained {
		return w.sealRetainedLocked(ctx)
	}
	if w.ended {
		return Object{}, ErrState
	}
	if err := ctx.Err(); err != nil {
		w.abortLocked()
		return Object{}, err
	}
	if w.failure != nil || w.size == 0 {
		err := w.failure
		if err == nil {
			err = ErrIdentity
		}
		w.abortLocked()
		return Object{}, err
	}
	object := Object{Digest: hex.EncodeToString(w.hash.Sum(nil)), Size: w.size}
	err := w.file.Chmod(0400)
	if err == nil {
		err = w.file.Sync()
	}
	closeErr := w.file.Close()
	w.ended = true
	defer os.Remove(w.path)
	s := w.store
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.writers, w)
	if err != nil || closeErr != nil {
		return Object{}, errors.Join(err, closeErr)
	}
	if s.closed {
		return Object{}, ErrState
	}
	if err = ctx.Err(); err != nil {
		return Object{}, err
	}
	target := filepath.Join(s.objects, object.Digest)
	created := false
	if err = os.Link(w.path, target); err == nil {
		created = true
	} else if !errors.Is(err, os.ErrExist) {
		return Object{}, err
	}
	if !created {
		file, e := openVerified(ctx, target, object)
		if e != nil {
			return Object{}, e
		}
		if e = file.Close(); e != nil {
			return Object{}, e
		}
	}
	if err = syncDirectory(s.objects); err != nil {
		return Object{}, err
	}
	if err = ctx.Err(); err != nil {
		return Object{}, err
	}
	return object, nil
}
func syncDirectory(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	return errors.Join(file.Sync(), file.Close())
}
func openVerified(ctx context.Context, path string, object Object) (*os.File, error) {
	if !validObject(object) {
		return nil, ErrIdentity
	}
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0222 != 0 {
		return nil, ErrIdentity
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	fail := func(e error) (*os.File, error) { file.Close(); return nil, e }
	if err = artifactlease.Shared(file); err != nil {
		return fail(err)
	}
	current, err := os.Lstat(path)
	if err != nil || !os.SameFile(info, current) {
		return fail(ErrIdentity)
	}
	actual, err := file.Stat()
	if err != nil {
		return fail(err)
	}
	if !actual.Mode().IsRegular() || !os.SameFile(info, actual) || actual.Size() != object.Size {
		return fail(ErrIdentity)
	}
	digest := sha256.New()
	buffer := make([]byte, 64<<10)
	for {
		if err = ctx.Err(); err != nil {
			return fail(err)
		}
		n, e := file.Read(buffer)
		if n > 0 {
			digest.Write(buffer[:n])
		}
		if e == io.EOF {
			break
		}
		if e != nil {
			return fail(e)
		}
	}
	if hex.EncodeToString(digest.Sum(nil)) != object.Digest {
		return fail(ErrIdentity)
	}
	if _, err = file.Seek(0, io.SeekStart); err != nil {
		return fail(err)
	}
	if err = ctx.Err(); err != nil {
		return fail(err)
	}
	return file, nil
}

// Open verifies closed bytes and retains an independent descriptor. The caller
// must first resolve an authorized committed publication record to this Object.
func (s *Store) Open(ctx context.Context, object Object) (*Reader, error) {
	if !validObject(object) {
		return nil, ErrIdentity
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return nil, ErrState
	}
	file, err := openVerified(ctx, filepath.Join(s.objects, object.Digest), object)
	if err != nil {
		return nil, err
	}
	s.readers[object.Digest]++
	return &Reader{file: file, store: s, digest: object.Digest}, nil
}

type Reader struct {
	file   *os.File
	store  *Store
	digest string
	once   sync.Once
	err    error
}

func (r *Reader) Read(data []byte) (int, error)                 { return r.file.Read(data) }
func (r *Reader) ReadAt(data []byte, offset int64) (int, error) { return r.file.ReadAt(data, offset) }
func (r *Reader) Close() error {
	r.once.Do(func() {
		r.err = r.file.Close()
		r.store.mu.Lock()
		r.store.readers[r.digest]--
		if r.store.readers[r.digest] == 0 {
			delete(r.store.readers, r.digest)
		}
		r.store.mu.Unlock()
	})
	return r.err
}

// Remove is called only after durable publication/retention checks. A read lease
// cannot be interrupted by collection, even if its original viewer disconnects.
func (s *Store) Remove(object Object) error {
	if !validObject(object) {
		return ErrIdentity
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return ErrState
	}
	if s.readers[object.Digest] > 0 {
		return ErrLeased
	}
	path := filepath.Join(s.objects, object.Digest)
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Mode().Perm()&0222 != 0 || info.Size() != object.Size {
		return ErrIdentity
	}
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()
	if err = artifactlease.Exclusive(file); err != nil {
		if errors.Is(err, artifactlease.ErrBusy) {
			return ErrLeased
		}
		return err
	}
	actual, err := file.Stat()
	if err != nil {
		return err
	}
	current, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if !os.SameFile(actual, current) || !os.SameFile(info, current) {
		return ErrIdentity
	}
	err = os.Remove(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	return syncDirectory(s.objects)
}
func (s *Store) Close() error {
	s.mu.Lock()
	s.closed = true
	writers := make([]*Writer, 0, len(s.writers))
	for writer := range s.writers {
		writers = append(writers, writer)
	}
	s.mu.Unlock()
	var result error
	for _, writer := range writers {
		if writer.retained {
			result = errors.Join(result, writer.Retain())
		} else {
			result = errors.Join(result, writer.Abort())
		}
	}
	return result
}
