// Generated by scripts/icons/generate.mjs. Do not edit.
export type PorticoIconId =
  | "accessibility.audio-description"
  | "accessibility.captions"
  | "accessibility.universal"
  | "account.edit-profile"
  | "account.profile"
  | "account.profiles"
  | "account.security"
  | "account.sign-in"
  | "account.sign-out"
  | "account.user"
  | "account.verified"
  | "account.visibility.hide"
  | "account.visibility.show"
  | "account.watch-together"
  | "action.add"
  | "action.add-to-list"
  | "action.archive"
  | "action.cancel"
  | "action.clear"
  | "action.close"
  | "action.confirm"
  | "action.customize"
  | "action.delete"
  | "action.dislike"
  | "action.dismiss"
  | "action.download"
  | "action.edit"
  | "action.favorite"
  | "action.feedback"
  | "action.filter"
  | "action.fullscreen-enter"
  | "action.fullscreen-exit"
  | "action.like"
  | "action.mark-read"
  | "action.mark-unread"
  | "action.mark-watched"
  | "action.more"
  | "action.open-external"
  | "action.optimize"
  | "action.pin"
  | "action.prepare-download"
  | "action.rate"
  | "action.reaction"
  | "action.refresh"
  | "action.remove"
  | "action.report"
  | "action.reset"
  | "action.resolve"
  | "action.retry"
  | "action.send"
  | "action.sort"
  | "action.sort-ascending"
  | "action.sort-descending"
  | "action.switch-server"
  | "action.undo"
  | "action.unpin"
  | "action.watchlist"
  | "appearance.dark-mode"
  | "communication.inbox"
  | "communication.message"
  | "communication.microphone"
  | "communication.notifications"
  | "communication.report"
  | "device.client"
  | "device.display"
  | "device.nearby"
  | "device.network"
  | "device.offline"
  | "device.server"
  | "device.storage"
  | "device.tv"
  | "device.wifi"
  | "library.archive"
  | "library.collection"
  | "library.saved"
  | "library.storage"
  | "media.audiobook"
  | "media.calendar"
  | "media.collection"
  | "media.live-tv"
  | "media.movie"
  | "media.music"
  | "media.photo"
  | "media.playlist"
  | "media.video"
  | "metadata.info"
  | "metadata.time"
  | "navigation.back"
  | "navigation.channels"
  | "navigation.collapse"
  | "navigation.disclosure"
  | "navigation.expand"
  | "navigation.forward"
  | "navigation.home"
  | "navigation.library"
  | "navigation.move-down"
  | "navigation.move-up"
  | "navigation.next"
  | "navigation.previous"
  | "navigation.saved"
  | "navigation.search"
  | "navigation.settings"
  | "playback.audio"
  | "playback.autoplay"
  | "playback.captions"
  | "playback.chapters"
  | "playback.language"
  | "playback.lyrics"
  | "playback.mute"
  | "playback.next"
  | "playback.pause"
  | "playback.picture-in-picture"
  | "playback.play"
  | "playback.previous"
  | "playback.quality"
  | "playback.queue"
  | "playback.record"
  | "playback.repeat"
  | "playback.repeat-one"
  | "playback.replay"
  | "playback.restart"
  | "playback.route.airplay"
  | "playback.route.cast"
  | "playback.seek-back"
  | "playback.seek-forward"
  | "playback.shuffle"
  | "playback.speed"
  | "playback.subtitles"
  | "playback.technical-stats"
  | "playback.unmute"
  | "playback.up-next"
  | "playback.volume"
  | "preference.downloads"
  | "preference.language"
  | "preference.notifications"
  | "preference.playback"
  | "preference.quality"
  | "preference.seek-interval"
  | "preference.storage"
  | "status.active"
  | "status.artwork-unavailable"
  | "status.downloaded"
  | "status.downloading"
  | "status.empty"
  | "status.error"
  | "status.icon-mapping-missing"
  | "status.info"
  | "status.live"
  | "status.loading"
  | "status.locked"
  | "status.notification"
  | "status.offline"
  | "status.online"
  | "status.rate-limited"
  | "status.secure"
  | "status.selected"
  | "status.success"
  | "status.warning"
  | "view.calendar"
  | "view.details"
  | "view.grid"
  | "view.list";

export const ICON_REGISTRY_VERSION = "1.0.0" as const;
export const semanticToMaster: Record<PorticoIconId, string> = {
  "accessibility.audio-description": "ear",
  "accessibility.captions": "captions",
  "accessibility.universal": "accessibility",
  "account.edit-profile": "pencil",
  "account.profile": "circle-user-round",
  "account.profiles": "users",
  "account.security": "key-round",
  "account.sign-in": "log-in",
  "account.sign-out": "log-out",
  "account.user": "user-round",
  "account.verified": "shield-check",
  "account.visibility.hide": "eye-off",
  "account.visibility.show": "eye",
  "account.watch-together": "users",
  "action.add": "plus",
  "action.add-to-list": "list-plus",
  "action.archive": "archive",
  "action.cancel": "x",
  "action.clear": "x",
  "action.close": "x",
  "action.confirm": "check",
  "action.customize": "sliders-horizontal",
  "action.delete": "trash-2",
  "action.dislike": "thumbs-down",
  "action.dismiss": "check",
  "action.download": "download",
  "action.edit": "pencil",
  "action.favorite": "heart",
  "action.feedback": "message-square",
  "action.filter": "sliders-horizontal",
  "action.fullscreen-enter": "maximize-2",
  "action.fullscreen-exit": "minimize-2",
  "action.like": "thumbs-up",
  "action.mark-read": "check",
  "action.mark-unread": "mail",
  "action.mark-watched": "check",
  "action.more": "ellipsis",
  "action.open-external": "external-link",
  "action.optimize": "gauge",
  "action.pin": "pin",
  "action.prepare-download": "download-cloud",
  "action.rate": "star",
  "action.reaction": "thumbs-up",
  "action.refresh": "refresh-cw",
  "action.remove": "x",
  "action.report": "message-square-warning",
  "action.reset": "rotate-ccw",
  "action.resolve": "circle-check",
  "action.retry": "refresh-cw",
  "action.send": "send",
  "action.sort": "arrow-down-a-z",
  "action.sort-ascending": "arrow-up-a-z",
  "action.sort-descending": "arrow-down-z-a",
  "action.switch-server": "server",
  "action.undo": "rotate-ccw",
  "action.unpin": "pin-off",
  "action.watchlist": "bookmark",
  "appearance.dark-mode": "moon",
  "communication.inbox": "inbox",
  "communication.message": "message-square",
  "communication.microphone": "mic-2",
  "communication.notifications": "bell",
  "communication.report": "message-square-warning",
  "device.client": "monitor-smartphone",
  "device.display": "monitor",
  "device.nearby": "radar",
  "device.network": "network",
  "device.offline": "wifi-off",
  "device.server": "server",
  "device.storage": "hard-drive",
  "device.tv": "tv",
  "device.wifi": "wifi",
  "library.archive": "archive",
  "library.collection": "library",
  "library.saved": "folder-heart",
  "library.storage": "hard-drive",
  "media.audiobook": "headphones",
  "media.calendar": "calendar-days",
  "media.collection": "grid-3x3",
  "media.live-tv": "tv",
  "media.movie": "film",
  "media.music": "music-2",
  "media.photo": "camera",
  "media.playlist": "list-music",
  "media.video": "video",
  "metadata.info": "info",
  "metadata.time": "clock-3",
  "navigation.back": "arrow-left",
  "navigation.channels": "radio",
  "navigation.collapse": "chevron-up",
  "navigation.disclosure": "chevron-right",
  "navigation.expand": "chevron-down",
  "navigation.forward": "arrow-right",
  "navigation.home": "home",
  "navigation.library": "library",
  "navigation.move-down": "chevron-down",
  "navigation.move-up": "chevron-up",
  "navigation.next": "chevron-right",
  "navigation.previous": "chevron-left",
  "navigation.saved": "folder-heart",
  "navigation.search": "search",
  "navigation.settings": "settings",
  "playback.audio": "headphones",
  "playback.autoplay": "play-circle",
  "playback.captions": "captions",
  "playback.chapters": "list",
  "playback.language": "languages",
  "playback.lyrics": "mic-2",
  "playback.mute": "volume-x",
  "playback.next": "skip-forward",
  "playback.pause": "pause",
  "playback.picture-in-picture": "picture-in-picture-2",
  "playback.play": "play",
  "playback.previous": "skip-back",
  "playback.quality": "gauge",
  "playback.queue": "list-video",
  "playback.record": "circle",
  "playback.repeat": "repeat",
  "playback.repeat-one": "repeat-1",
  "playback.replay": "rotate-ccw",
  "playback.restart": "rotate-ccw",
  "playback.route.airplay": "airplay",
  "playback.route.cast": "cast",
  "playback.seek-back": "rotate-ccw",
  "playback.seek-forward": "rotate-cw",
  "playback.shuffle": "shuffle",
  "playback.speed": "gauge",
  "playback.subtitles": "subtitles",
  "playback.technical-stats": "activity",
  "playback.unmute": "volume-2",
  "playback.up-next": "list-video",
  "playback.volume": "volume-2",
  "preference.downloads": "download",
  "preference.language": "languages",
  "preference.notifications": "bell",
  "preference.playback": "sliders-horizontal",
  "preference.quality": "gauge",
  "preference.seek-interval": "rotate-cw",
  "preference.storage": "hard-drive",
  "status.active": "circle",
  "status.artwork-unavailable": "image-off",
  "status.downloaded": "circle-check",
  "status.downloading": "download",
  "status.empty": "inbox",
  "status.error": "circle-x",
  "status.icon-mapping-missing": "triangle-alert",
  "status.info": "info",
  "status.live": "radio",
  "status.loading": "loader-circle",
  "status.locked": "lock-keyhole",
  "status.notification": "bell",
  "status.offline": "wifi-off",
  "status.online": "wifi",
  "status.rate-limited": "clock-3",
  "status.secure": "shield-check",
  "status.selected": "check",
  "status.success": "circle-check",
  "status.warning": "triangle-alert",
  "view.calendar": "calendar-days",
  "view.details": "info",
  "view.grid": "grid-3x3",
  "view.list": "list"
};
export const iconNodes: Record<string, ReadonlyArray<readonly [string, Readonly<Record<string, string | number>>]>> = {
  "accessibility": [
    [
      "circle",
      {
        "cx": "16",
        "cy": "4",
        "r": "1"
      }
    ],
    [
      "path",
      {
        "d": "m18 19 1-7-6 1"
      }
    ],
    [
      "path",
      {
        "d": "m5 8 3-3 5.5 3-2.36 3.5"
      }
    ],
    [
      "path",
      {
        "d": "M4.24 14.5a5 5 0 0 0 6.88 6"
      }
    ],
    [
      "path",
      {
        "d": "M13.76 17.5a5 5 0 0 0-6.88-6"
      }
    ]
  ],
  "activity": [
    [
      "path",
      {
        "d": "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2"
      }
    ]
  ],
  "airplay": [
    [
      "path",
      {
        "d": "M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"
      }
    ],
    [
      "path",
      {
        "d": "m12 15 5 6H7Z"
      }
    ]
  ],
  "archive": [
    [
      "rect",
      {
        "width": "20",
        "height": "5",
        "x": "2",
        "y": "3",
        "rx": "1"
      }
    ],
    [
      "path",
      {
        "d": "M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"
      }
    ],
    [
      "path",
      {
        "d": "M10 12h4"
      }
    ]
  ],
  "arrow-down-a-z": [
    [
      "path",
      {
        "d": "m3 16 4 4 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M7 20V4"
      }
    ],
    [
      "path",
      {
        "d": "M20 8h-5"
      }
    ],
    [
      "path",
      {
        "d": "M15 10V6.5a2.5 2.5 0 0 1 5 0V10"
      }
    ],
    [
      "path",
      {
        "d": "M15 14h5l-5 6h5"
      }
    ]
  ],
  "arrow-down-z-a": [
    [
      "path",
      {
        "d": "m3 16 4 4 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M7 4v16"
      }
    ],
    [
      "path",
      {
        "d": "M15 4h5l-5 6h5"
      }
    ],
    [
      "path",
      {
        "d": "M15 20v-3.5a2.5 2.5 0 0 1 5 0V20"
      }
    ],
    [
      "path",
      {
        "d": "M20 18h-5"
      }
    ]
  ],
  "arrow-left": [
    [
      "path",
      {
        "d": "m12 19-7-7 7-7"
      }
    ],
    [
      "path",
      {
        "d": "M19 12H5"
      }
    ]
  ],
  "arrow-right": [
    [
      "path",
      {
        "d": "M5 12h14"
      }
    ],
    [
      "path",
      {
        "d": "m12 5 7 7-7 7"
      }
    ]
  ],
  "arrow-up-a-z": [
    [
      "path",
      {
        "d": "m3 8 4-4 4 4"
      }
    ],
    [
      "path",
      {
        "d": "M7 4v16"
      }
    ],
    [
      "path",
      {
        "d": "M20 8h-5"
      }
    ],
    [
      "path",
      {
        "d": "M15 10V6.5a2.5 2.5 0 0 1 5 0V10"
      }
    ],
    [
      "path",
      {
        "d": "M15 14h5l-5 6h5"
      }
    ]
  ],
  "bell": [
    [
      "path",
      {
        "d": "M10.268 21a2 2 0 0 0 3.464 0"
      }
    ],
    [
      "path",
      {
        "d": "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"
      }
    ]
  ],
  "bookmark": [
    [
      "path",
      {
        "d": "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"
      }
    ]
  ],
  "calendar-days": [
    [
      "path",
      {
        "d": "M8 2v4"
      }
    ],
    [
      "path",
      {
        "d": "M16 2v4"
      }
    ],
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "4",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "M3 10h18"
      }
    ],
    [
      "path",
      {
        "d": "M8 14h.01"
      }
    ],
    [
      "path",
      {
        "d": "M12 14h.01"
      }
    ],
    [
      "path",
      {
        "d": "M16 14h.01"
      }
    ],
    [
      "path",
      {
        "d": "M8 18h.01"
      }
    ],
    [
      "path",
      {
        "d": "M12 18h.01"
      }
    ],
    [
      "path",
      {
        "d": "M16 18h.01"
      }
    ]
  ],
  "camera": [
    [
      "path",
      {
        "d": "M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "13",
        "r": "3"
      }
    ]
  ],
  "captions": [
    [
      "rect",
      {
        "width": "18",
        "height": "14",
        "x": "3",
        "y": "5",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "path",
      {
        "d": "M7 15h4M15 15h2M7 11h2M13 11h4"
      }
    ]
  ],
  "cast": [
    [
      "path",
      {
        "d": "M2 8V6a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2h-6"
      }
    ],
    [
      "path",
      {
        "d": "M2 12a9 9 0 0 1 8 8"
      }
    ],
    [
      "path",
      {
        "d": "M2 16a5 5 0 0 1 4 4"
      }
    ],
    [
      "line",
      {
        "x1": "2",
        "x2": "2.01",
        "y1": "20",
        "y2": "20"
      }
    ]
  ],
  "check": [
    [
      "path",
      {
        "d": "M20 6 9 17l-5-5"
      }
    ]
  ],
  "chevron-down": [
    [
      "path",
      {
        "d": "m6 9 6 6 6-6"
      }
    ]
  ],
  "chevron-left": [
    [
      "path",
      {
        "d": "m15 18-6-6 6-6"
      }
    ]
  ],
  "chevron-right": [
    [
      "path",
      {
        "d": "m9 18 6-6-6-6"
      }
    ]
  ],
  "chevron-up": [
    [
      "path",
      {
        "d": "m18 15-6-6-6 6"
      }
    ]
  ],
  "circle": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ]
  ],
  "circle-check": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ],
    [
      "path",
      {
        "d": "m9 12 2 2 4-4"
      }
    ]
  ],
  "circle-user-round": [
    [
      "path",
      {
        "d": "M17.925 20.056a6 6 0 0 0-11.851.001"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "11",
        "r": "4"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ]
  ],
  "circle-x": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ],
    [
      "path",
      {
        "d": "m15 9-6 6"
      }
    ],
    [
      "path",
      {
        "d": "m9 9 6 6"
      }
    ]
  ],
  "clock-3": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ],
    [
      "path",
      {
        "d": "M12 6v6h4"
      }
    ]
  ],
  "download": [
    [
      "path",
      {
        "d": "M12 15V3"
      }
    ],
    [
      "path",
      {
        "d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
      }
    ],
    [
      "path",
      {
        "d": "m7 10 5 5 5-5"
      }
    ]
  ],
  "download-cloud": [
    [
      "path",
      {
        "d": "M12 13v8l-4-4"
      }
    ],
    [
      "path",
      {
        "d": "m12 21 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M4.393 15.269A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.436 8.284"
      }
    ]
  ],
  "ear": [
    [
      "path",
      {
        "d": "M6 8.5a6.5 6.5 0 1 1 13 0c0 6-6 6-6 10a3.5 3.5 0 1 1-7 0"
      }
    ],
    [
      "path",
      {
        "d": "M15 8.5a2.5 2.5 0 0 0-5 0v1a2 2 0 1 1 0 4"
      }
    ]
  ],
  "ellipsis": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "1"
      }
    ],
    [
      "circle",
      {
        "cx": "19",
        "cy": "12",
        "r": "1"
      }
    ],
    [
      "circle",
      {
        "cx": "5",
        "cy": "12",
        "r": "1"
      }
    ]
  ],
  "external-link": [
    [
      "path",
      {
        "d": "M15 3h6v6"
      }
    ],
    [
      "path",
      {
        "d": "M10 14 21 3"
      }
    ],
    [
      "path",
      {
        "d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"
      }
    ]
  ],
  "eye": [
    [
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3"
      }
    ]
  ],
  "eye-off": [
    [
      "path",
      {
        "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"
      }
    ],
    [
      "path",
      {
        "d": "M14.084 14.158a3 3 0 0 1-4.242-4.242"
      }
    ],
    [
      "path",
      {
        "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"
      }
    ],
    [
      "path",
      {
        "d": "m2 2 20 20"
      }
    ]
  ],
  "film": [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "M7 3v18"
      }
    ],
    [
      "path",
      {
        "d": "M3 7.5h4"
      }
    ],
    [
      "path",
      {
        "d": "M3 12h18"
      }
    ],
    [
      "path",
      {
        "d": "M3 16.5h4"
      }
    ],
    [
      "path",
      {
        "d": "M17 3v18"
      }
    ],
    [
      "path",
      {
        "d": "M17 7.5h4"
      }
    ],
    [
      "path",
      {
        "d": "M17 16.5h4"
      }
    ]
  ],
  "folder-heart": [
    [
      "path",
      {
        "d": "M10.638 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v3.417"
      }
    ],
    [
      "path",
      {
        "d": "M14.62 18.8A2.25 2.25 0 1 1 18 15.836a2.25 2.25 0 1 1 3.38 2.966l-2.626 2.856a.998.998 0 0 1-1.507 0z"
      }
    ]
  ],
  "gauge": [
    [
      "path",
      {
        "d": "m12 14 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M3.34 19a10 10 0 1 1 17.32 0"
      }
    ]
  ],
  "grid-3x3": [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "M3 9h18"
      }
    ],
    [
      "path",
      {
        "d": "M3 15h18"
      }
    ],
    [
      "path",
      {
        "d": "M9 3v18"
      }
    ],
    [
      "path",
      {
        "d": "M15 3v18"
      }
    ]
  ],
  "hard-drive": [
    [
      "path",
      {
        "d": "M10 16h.01"
      }
    ],
    [
      "path",
      {
        "d": "M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"
      }
    ],
    [
      "path",
      {
        "d": "M21.946 12.013H2.054"
      }
    ],
    [
      "path",
      {
        "d": "M6 16h.01"
      }
    ]
  ],
  "headphones": [
    [
      "path",
      {
        "d": "M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3"
      }
    ]
  ],
  "heart": [
    [
      "path",
      {
        "d": "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"
      }
    ]
  ],
  "home": [
    [
      "path",
      {
        "d": "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"
      }
    ],
    [
      "path",
      {
        "d": "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
      }
    ]
  ],
  "image-off": [
    [
      "line",
      {
        "x1": "2",
        "x2": "22",
        "y1": "2",
        "y2": "22"
      }
    ],
    [
      "path",
      {
        "d": "M10.41 10.41a2 2 0 1 1-2.83-2.83"
      }
    ],
    [
      "line",
      {
        "x1": "13.5",
        "x2": "6",
        "y1": "13.5",
        "y2": "21"
      }
    ],
    [
      "line",
      {
        "x1": "18",
        "x2": "21",
        "y1": "12",
        "y2": "15"
      }
    ],
    [
      "path",
      {
        "d": "M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"
      }
    ],
    [
      "path",
      {
        "d": "M21 15V5a2 2 0 0 0-2-2H9"
      }
    ]
  ],
  "inbox": [
    [
      "polyline",
      {
        "points": "22 12 16 12 14 15 10 15 8 12 2 12"
      }
    ],
    [
      "path",
      {
        "d": "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"
      }
    ]
  ],
  "info": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ],
    [
      "path",
      {
        "d": "M12 16v-4"
      }
    ],
    [
      "path",
      {
        "d": "M12 8h.01"
      }
    ]
  ],
  "key-round": [
    [
      "path",
      {
        "d": "M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z"
      }
    ],
    [
      "circle",
      {
        "cx": "16.5",
        "cy": "7.5",
        "r": ".5",
        "fill": "currentColor"
      }
    ]
  ],
  "languages": [
    [
      "path",
      {
        "d": "m5 8 6 6"
      }
    ],
    [
      "path",
      {
        "d": "m4 14 6-6 2-3"
      }
    ],
    [
      "path",
      {
        "d": "M2 5h12"
      }
    ],
    [
      "path",
      {
        "d": "M7 2h1"
      }
    ],
    [
      "path",
      {
        "d": "m22 22-5-10-5 10"
      }
    ],
    [
      "path",
      {
        "d": "M14 18h6"
      }
    ]
  ],
  "library": [
    [
      "path",
      {
        "d": "m16 6 4 14"
      }
    ],
    [
      "path",
      {
        "d": "M12 6v14"
      }
    ],
    [
      "path",
      {
        "d": "M8 8v12"
      }
    ],
    [
      "path",
      {
        "d": "M4 4v16"
      }
    ]
  ],
  "list": [
    [
      "path",
      {
        "d": "M3 5h.01"
      }
    ],
    [
      "path",
      {
        "d": "M3 12h.01"
      }
    ],
    [
      "path",
      {
        "d": "M3 19h.01"
      }
    ],
    [
      "path",
      {
        "d": "M8 5h13"
      }
    ],
    [
      "path",
      {
        "d": "M8 12h13"
      }
    ],
    [
      "path",
      {
        "d": "M8 19h13"
      }
    ]
  ],
  "list-music": [
    [
      "path",
      {
        "d": "M16 5H3"
      }
    ],
    [
      "path",
      {
        "d": "M11 12H3"
      }
    ],
    [
      "path",
      {
        "d": "M11 19H3"
      }
    ],
    [
      "path",
      {
        "d": "M21 16V5"
      }
    ],
    [
      "circle",
      {
        "cx": "18",
        "cy": "16",
        "r": "3"
      }
    ]
  ],
  "list-plus": [
    [
      "path",
      {
        "d": "M16 5H3"
      }
    ],
    [
      "path",
      {
        "d": "M11 12H3"
      }
    ],
    [
      "path",
      {
        "d": "M16 19H3"
      }
    ],
    [
      "path",
      {
        "d": "M18 9v6"
      }
    ],
    [
      "path",
      {
        "d": "M21 12h-6"
      }
    ]
  ],
  "list-video": [
    [
      "path",
      {
        "d": "M21 5H3"
      }
    ],
    [
      "path",
      {
        "d": "M10 12H3"
      }
    ],
    [
      "path",
      {
        "d": "M10 19H3"
      }
    ],
    [
      "path",
      {
        "d": "M15 12.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997a1 1 0 0 1-1.517-.86z"
      }
    ]
  ],
  "loader-circle": [
    [
      "path",
      {
        "d": "M21 12a9 9 0 1 1-6.219-8.56"
      }
    ]
  ],
  "lock-keyhole": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "16",
        "r": "1"
      }
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "10",
        "width": "18",
        "height": "12",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "M7 10V7a5 5 0 0 1 10 0v3"
      }
    ]
  ],
  "log-in": [
    [
      "path",
      {
        "d": "m10 17 5-5-5-5"
      }
    ],
    [
      "path",
      {
        "d": "M15 12H3"
      }
    ],
    [
      "path",
      {
        "d": "M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"
      }
    ]
  ],
  "log-out": [
    [
      "path",
      {
        "d": "m16 17 5-5-5-5"
      }
    ],
    [
      "path",
      {
        "d": "M21 12H9"
      }
    ],
    [
      "path",
      {
        "d": "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"
      }
    ]
  ],
  "mail": [
    [
      "path",
      {
        "d": "m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"
      }
    ],
    [
      "rect",
      {
        "x": "2",
        "y": "4",
        "width": "20",
        "height": "16",
        "rx": "2"
      }
    ]
  ],
  "maximize-2": [
    [
      "path",
      {
        "d": "M15 3h6v6"
      }
    ],
    [
      "path",
      {
        "d": "m21 3-7 7"
      }
    ],
    [
      "path",
      {
        "d": "m3 21 7-7"
      }
    ],
    [
      "path",
      {
        "d": "M9 21H3v-6"
      }
    ]
  ],
  "message-square": [
    [
      "path",
      {
        "d": "M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"
      }
    ]
  ],
  "message-square-warning": [
    [
      "path",
      {
        "d": "M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"
      }
    ],
    [
      "path",
      {
        "d": "M12 15h.01"
      }
    ],
    [
      "path",
      {
        "d": "M12 7v4"
      }
    ]
  ],
  "mic-2": [
    [
      "path",
      {
        "d": "m11 7.601-5.994 8.19a1 1 0 0 0 .1 1.298l.817.818a1 1 0 0 0 1.314.087L15.09 12"
      }
    ],
    [
      "path",
      {
        "d": "M16.5 21.174C15.5 20.5 14.372 20 13 20c-2.058 0-3.928 2.356-6 2-2.072-.356-2.775-3.369-1.5-4.5"
      }
    ],
    [
      "circle",
      {
        "cx": "16",
        "cy": "7",
        "r": "5"
      }
    ]
  ],
  "minimize-2": [
    [
      "path",
      {
        "d": "m14 10 7-7"
      }
    ],
    [
      "path",
      {
        "d": "M20 10h-6V4"
      }
    ],
    [
      "path",
      {
        "d": "m3 21 7-7"
      }
    ],
    [
      "path",
      {
        "d": "M4 14h6v6"
      }
    ]
  ],
  "monitor": [
    [
      "rect",
      {
        "width": "20",
        "height": "14",
        "x": "2",
        "y": "3",
        "rx": "2"
      }
    ],
    [
      "line",
      {
        "x1": "8",
        "x2": "16",
        "y1": "21",
        "y2": "21"
      }
    ],
    [
      "line",
      {
        "x1": "12",
        "x2": "12",
        "y1": "17",
        "y2": "21"
      }
    ]
  ],
  "monitor-smartphone": [
    [
      "path",
      {
        "d": "M18 8V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h8"
      }
    ],
    [
      "path",
      {
        "d": "M10 19v-3.96 3.15"
      }
    ],
    [
      "path",
      {
        "d": "M7 19h5"
      }
    ],
    [
      "rect",
      {
        "width": "6",
        "height": "10",
        "x": "16",
        "y": "12",
        "rx": "2"
      }
    ]
  ],
  "moon": [
    [
      "path",
      {
        "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"
      }
    ]
  ],
  "music-2": [
    [
      "circle",
      {
        "cx": "8",
        "cy": "18",
        "r": "4"
      }
    ],
    [
      "path",
      {
        "d": "M12 18V2l7 4"
      }
    ]
  ],
  "network": [
    [
      "rect",
      {
        "x": "16",
        "y": "16",
        "width": "6",
        "height": "6",
        "rx": "1"
      }
    ],
    [
      "rect",
      {
        "x": "2",
        "y": "16",
        "width": "6",
        "height": "6",
        "rx": "1"
      }
    ],
    [
      "rect",
      {
        "x": "9",
        "y": "2",
        "width": "6",
        "height": "6",
        "rx": "1"
      }
    ],
    [
      "path",
      {
        "d": "M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"
      }
    ],
    [
      "path",
      {
        "d": "M12 12V8"
      }
    ]
  ],
  "pause": [
    [
      "rect",
      {
        "x": "14",
        "y": "3",
        "width": "5",
        "height": "18",
        "rx": "1"
      }
    ],
    [
      "rect",
      {
        "x": "5",
        "y": "3",
        "width": "5",
        "height": "18",
        "rx": "1"
      }
    ]
  ],
  "pencil": [
    [
      "path",
      {
        "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"
      }
    ],
    [
      "path",
      {
        "d": "m15 5 4 4"
      }
    ]
  ],
  "picture-in-picture-2": [
    [
      "path",
      {
        "d": "M21 9V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v10c0 1.1.9 2 2 2h4"
      }
    ],
    [
      "rect",
      {
        "width": "10",
        "height": "7",
        "x": "12",
        "y": "13",
        "rx": "2"
      }
    ]
  ],
  "pin": [
    [
      "path",
      {
        "d": "M12 17v5"
      }
    ],
    [
      "path",
      {
        "d": "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z"
      }
    ]
  ],
  "pin-off": [
    [
      "path",
      {
        "d": "M12 17v5"
      }
    ],
    [
      "path",
      {
        "d": "M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89"
      }
    ],
    [
      "path",
      {
        "d": "m2 2 20 20"
      }
    ],
    [
      "path",
      {
        "d": "M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11"
      }
    ]
  ],
  "play": [
    [
      "path",
      {
        "d": "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"
      }
    ]
  ],
  "play-circle": [
    [
      "path",
      {
        "d": "M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "10"
      }
    ]
  ],
  "plus": [
    [
      "path",
      {
        "d": "M5 12h14"
      }
    ],
    [
      "path",
      {
        "d": "M12 5v14"
      }
    ]
  ],
  "radar": [
    [
      "path",
      {
        "d": "M19.07 4.93A10 10 0 0 0 6.99 3.34"
      }
    ],
    [
      "path",
      {
        "d": "M4 6h.01"
      }
    ],
    [
      "path",
      {
        "d": "M2.29 9.62A10 10 0 1 0 21.31 8.35"
      }
    ],
    [
      "path",
      {
        "d": "M16.24 7.76A6 6 0 1 0 8.23 16.67"
      }
    ],
    [
      "path",
      {
        "d": "M12 18h.01"
      }
    ],
    [
      "path",
      {
        "d": "M17.99 11.66A6 6 0 0 1 15.77 16.67"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "2"
      }
    ],
    [
      "path",
      {
        "d": "m13.41 10.59 5.66-5.66"
      }
    ]
  ],
  "radio": [
    [
      "path",
      {
        "d": "M16.247 7.761a6 6 0 0 1 0 8.478"
      }
    ],
    [
      "path",
      {
        "d": "M19.075 4.933a10 10 0 0 1 0 14.134"
      }
    ],
    [
      "path",
      {
        "d": "M4.925 19.067a10 10 0 0 1 0-14.134"
      }
    ],
    [
      "path",
      {
        "d": "M7.753 16.239a6 6 0 0 1 0-8.478"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "2"
      }
    ]
  ],
  "refresh-cw": [
    [
      "path",
      {
        "d": "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"
      }
    ],
    [
      "path",
      {
        "d": "M21 3v5h-5"
      }
    ],
    [
      "path",
      {
        "d": "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"
      }
    ],
    [
      "path",
      {
        "d": "M8 16H3v5"
      }
    ]
  ],
  "repeat": [
    [
      "path",
      {
        "d": "m17 2 4 4-4 4"
      }
    ],
    [
      "path",
      {
        "d": "M3 11v-1a4 4 0 0 1 4-4h14"
      }
    ],
    [
      "path",
      {
        "d": "m7 22-4-4 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M21 13v1a4 4 0 0 1-4 4H3"
      }
    ]
  ],
  "repeat-1": [
    [
      "path",
      {
        "d": "m17 2 4 4-4 4"
      }
    ],
    [
      "path",
      {
        "d": "M3 11v-1a4 4 0 0 1 4-4h14"
      }
    ],
    [
      "path",
      {
        "d": "m7 22-4-4 4-4"
      }
    ],
    [
      "path",
      {
        "d": "M21 13v1a4 4 0 0 1-4 4H3"
      }
    ],
    [
      "path",
      {
        "d": "M11 10h1v4"
      }
    ]
  ],
  "rotate-ccw": [
    [
      "path",
      {
        "d": "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"
      }
    ],
    [
      "path",
      {
        "d": "M3 3v5h5"
      }
    ]
  ],
  "rotate-cw": [
    [
      "path",
      {
        "d": "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"
      }
    ],
    [
      "path",
      {
        "d": "M21 3v5h-5"
      }
    ]
  ],
  "search": [
    [
      "path",
      {
        "d": "m21 21-4.34-4.34"
      }
    ],
    [
      "circle",
      {
        "cx": "11",
        "cy": "11",
        "r": "8"
      }
    ]
  ],
  "send": [
    [
      "path",
      {
        "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"
      }
    ],
    [
      "path",
      {
        "d": "m21.854 2.147-10.94 10.939"
      }
    ]
  ],
  "server": [
    [
      "rect",
      {
        "width": "20",
        "height": "8",
        "x": "2",
        "y": "2",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "rect",
      {
        "width": "20",
        "height": "8",
        "x": "2",
        "y": "14",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "line",
      {
        "x1": "6",
        "x2": "6.01",
        "y1": "6",
        "y2": "6"
      }
    ],
    [
      "line",
      {
        "x1": "6",
        "x2": "6.01",
        "y1": "18",
        "y2": "18"
      }
    ]
  ],
  "settings": [
    [
      "path",
      {
        "d": "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915"
      }
    ],
    [
      "circle",
      {
        "cx": "12",
        "cy": "12",
        "r": "3"
      }
    ]
  ],
  "shield-check": [
    [
      "path",
      {
        "d": "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"
      }
    ],
    [
      "path",
      {
        "d": "m9 12 2 2 4-4"
      }
    ]
  ],
  "shuffle": [
    [
      "path",
      {
        "d": "m18 14 4 4-4 4"
      }
    ],
    [
      "path",
      {
        "d": "m18 2 4 4-4 4"
      }
    ],
    [
      "path",
      {
        "d": "M2 18h1.973a4 4 0 0 0 3.3-1.7l5.454-8.6a4 4 0 0 1 3.3-1.7H22"
      }
    ],
    [
      "path",
      {
        "d": "M2 6h1.972a4 4 0 0 1 3.6 2.2"
      }
    ],
    [
      "path",
      {
        "d": "M22 18h-6.041a4 4 0 0 1-3.3-1.8l-.359-.45"
      }
    ]
  ],
  "skip-back": [
    [
      "path",
      {
        "d": "M17.971 4.285A2 2 0 0 1 21 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432z"
      }
    ],
    [
      "path",
      {
        "d": "M3 20V4"
      }
    ]
  ],
  "skip-forward": [
    [
      "path",
      {
        "d": "M21 4v16"
      }
    ],
    [
      "path",
      {
        "d": "M6.029 4.285A2 2 0 0 0 3 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432z"
      }
    ]
  ],
  "sliders-horizontal": [
    [
      "path",
      {
        "d": "M10 5H3"
      }
    ],
    [
      "path",
      {
        "d": "M12 19H3"
      }
    ],
    [
      "path",
      {
        "d": "M14 3v4"
      }
    ],
    [
      "path",
      {
        "d": "M16 17v4"
      }
    ],
    [
      "path",
      {
        "d": "M21 12h-9"
      }
    ],
    [
      "path",
      {
        "d": "M21 19h-5"
      }
    ],
    [
      "path",
      {
        "d": "M21 5h-7"
      }
    ],
    [
      "path",
      {
        "d": "M8 10v4"
      }
    ],
    [
      "path",
      {
        "d": "M8 12H3"
      }
    ]
  ],
  "star": [
    [
      "path",
      {
        "d": "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
      }
    ]
  ],
  "subtitles": [
    [
      "rect",
      {
        "width": "18",
        "height": "14",
        "x": "3",
        "y": "5",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "path",
      {
        "d": "M7 15h4M15 15h2M7 11h2M13 11h4"
      }
    ]
  ],
  "thumbs-down": [
    [
      "path",
      {
        "d": "M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z"
      }
    ],
    [
      "path",
      {
        "d": "M17 14V2"
      }
    ]
  ],
  "thumbs-up": [
    [
      "path",
      {
        "d": "M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"
      }
    ],
    [
      "path",
      {
        "d": "M7 10v12"
      }
    ]
  ],
  "trash-2": [
    [
      "path",
      {
        "d": "M10 11v6"
      }
    ],
    [
      "path",
      {
        "d": "M14 11v6"
      }
    ],
    [
      "path",
      {
        "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"
      }
    ],
    [
      "path",
      {
        "d": "M3 6h18"
      }
    ],
    [
      "path",
      {
        "d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
      }
    ]
  ],
  "triangle-alert": [
    [
      "path",
      {
        "d": "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"
      }
    ],
    [
      "path",
      {
        "d": "M12 9v4"
      }
    ],
    [
      "path",
      {
        "d": "M12 17h.01"
      }
    ]
  ],
  "tv": [
    [
      "path",
      {
        "d": "m17 2-5 5-5-5"
      }
    ],
    [
      "rect",
      {
        "width": "20",
        "height": "15",
        "x": "2",
        "y": "7",
        "rx": "2"
      }
    ]
  ],
  "user-round": [
    [
      "circle",
      {
        "cx": "12",
        "cy": "8",
        "r": "5"
      }
    ],
    [
      "path",
      {
        "d": "M20 21a8 8 0 0 0-16 0"
      }
    ]
  ],
  "users": [
    [
      "path",
      {
        "d": "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"
      }
    ],
    [
      "path",
      {
        "d": "M16 3.128a4 4 0 0 1 0 7.744"
      }
    ],
    [
      "path",
      {
        "d": "M22 21v-2a4 4 0 0 0-3-3.87"
      }
    ],
    [
      "circle",
      {
        "cx": "9",
        "cy": "7",
        "r": "4"
      }
    ]
  ],
  "video": [
    [
      "path",
      {
        "d": "m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"
      }
    ],
    [
      "rect",
      {
        "x": "2",
        "y": "6",
        "width": "14",
        "height": "12",
        "rx": "2"
      }
    ]
  ],
  "volume-2": [
    [
      "path",
      {
        "d": "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z"
      }
    ],
    [
      "path",
      {
        "d": "M16 9a5 5 0 0 1 0 6"
      }
    ],
    [
      "path",
      {
        "d": "M19.364 18.364a9 9 0 0 0 0-12.728"
      }
    ]
  ],
  "volume-x": [
    [
      "path",
      {
        "d": "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z"
      }
    ],
    [
      "line",
      {
        "x1": "22",
        "x2": "16",
        "y1": "9",
        "y2": "15"
      }
    ],
    [
      "line",
      {
        "x1": "16",
        "x2": "22",
        "y1": "9",
        "y2": "15"
      }
    ]
  ],
  "wifi": [
    [
      "path",
      {
        "d": "M12 20h.01"
      }
    ],
    [
      "path",
      {
        "d": "M2 8.82a15 15 0 0 1 20 0"
      }
    ],
    [
      "path",
      {
        "d": "M5 12.859a10 10 0 0 1 14 0"
      }
    ],
    [
      "path",
      {
        "d": "M8.5 16.429a5 5 0 0 1 7 0"
      }
    ]
  ],
  "wifi-off": [
    [
      "path",
      {
        "d": "M12 20h.01"
      }
    ],
    [
      "path",
      {
        "d": "M8.5 16.429a5 5 0 0 1 7 0"
      }
    ],
    [
      "path",
      {
        "d": "M5 12.859a10 10 0 0 1 5.17-2.69"
      }
    ],
    [
      "path",
      {
        "d": "M19 12.859a10 10 0 0 0-2.007-1.523"
      }
    ],
    [
      "path",
      {
        "d": "M2 8.82a15 15 0 0 1 4.177-2.643"
      }
    ],
    [
      "path",
      {
        "d": "M22 8.82a15 15 0 0 0-11.288-3.764"
      }
    ],
    [
      "path",
      {
        "d": "m2 2 20 20"
      }
    ]
  ],
  "x": [
    [
      "path",
      {
        "d": "M18 6 6 18"
      }
    ],
    [
      "path",
      {
        "d": "m6 6 12 12"
      }
    ]
  ]
};
