// Generated by Product Contracts/scripts/compile-contracts.rb; DO NOT EDIT.
export type RecoveryAction = 'retry' | 'retry_after' | 'refresh_route' | 'refresh_credentials' | 'reselect_profile' | 'sign_in' | 'upgrade_client' | 'upgrade_server' | 'contact_owner' | 'contact_support' | 'terminal';
export type ExternalAction = 'open_home' | 'open_library' | 'open_media' | 'open_profile' | 'open_settings' | 'open_downloads' | 'play_media' | 'resume_media' | 'accept_invitation' | 'reset_password';
export const foundationContract = {
  "$schema": "portico.foundation.generated.v2",
  "build": {
    "buildNumber": "0",
    "channel": "development",
    "commit": "UNSTAMPED_DEVELOPMENT",
    "timestamp": null,
    "version": "0.0.0-development"
  },
  "compatibility": {
    "apiContract": {
      "digest": "36f41124c30a4e846e8e562d0bc090e55beb21d573b65f51463d1056392f66c4",
      "digestAlgorithm": "sha256",
      "identity": "portico-internal/hosted-services/api/openapi/portico-hosted.openapi.json+portico-server/api/openapi/openapi.yaml+portico-server/api/openapi/portico-server.openapi.json"
    },
    "envelopeRevision": 2,
    "requiredSemantics": [
      "externalAction",
      "paginationCursor",
      "playback",
      "problemRecoveryAction",
      "product",
      "viewerProfileAuthority"
    ],
    "semanticRevisions": {
      "externalAction": 1,
      "paginationCursor": 1,
      "playback": 1,
      "problemRecoveryAction": 1,
      "product": 2,
      "viewerProfileAuthority": 1
    },
    "supportedClientProtocol": {
      "maximum": 1,
      "minimum": 1
    }
  },
  "environments": [
    "development",
    "test",
    "staging",
    "production"
  ],
  "externalActions": [
    "open_home",
    "open_library",
    "open_media",
    "open_profile",
    "open_settings",
    "open_downloads",
    "play_media",
    "resume_media",
    "accept_invitation",
    "reset_password"
  ],
  "forwardCompatibility": {
    "apiContractDigestMismatch": "allow_semantic_overlap",
    "authorizationOnPartialUpgrade": "never_broaden",
    "unknownOptionalCapabilities": "ignore_and_preserve",
    "unknownRequiredSemantics": "reject_actionably"
  },
  "permissions": [
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "playMedia",
      "presentation": {
        "description": "Play available library media.",
        "label": "Play media"
      },
      "scopes": [
        "server",
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "downloadMedia",
      "presentation": {
        "description": "Download available media for offline playback.",
        "label": "Download media"
      },
      "scopes": [
        "server",
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "editMetadata",
      "presentation": {
        "description": "Edit titles, descriptions, artwork, and other media details.",
        "label": "Edit metadata"
      },
      "scopes": [
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "manageLyrics",
      "presentation": {
        "description": "Add, edit, and remove lyrics.",
        "label": "Manage lyrics"
      },
      "scopes": [
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "manageSubtitles",
      "presentation": {
        "description": "Add, edit, and remove subtitle tracks.",
        "label": "Manage subtitles"
      },
      "scopes": [
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "watchWithFriends",
      "presentation": {
        "description": "Create and join synchronized watch sessions.",
        "label": "Use Watch With Friends"
      },
      "scopes": [
        "server",
        "group"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "viewLiveTV",
      "presentation": {
        "description": "Browse channels and the program guide.",
        "label": "View Live TV"
      },
      "scopes": [
        "server",
        "channel"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "playLiveTV",
      "presentation": {
        "description": "Watch available live channels.",
        "label": "Play Live TV"
      },
      "scopes": [
        "server",
        "channel"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "viewDVR",
      "presentation": {
        "description": "Browse recordings and recording schedules.",
        "label": "View DVR"
      },
      "scopes": [
        "server",
        "recording",
        "recording-rule"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "scheduleDVR",
      "presentation": {
        "description": "Create and update recording schedules.",
        "label": "Schedule DVR recordings"
      },
      "scopes": [
        "server",
        "channel",
        "recording-rule"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "manageDVR",
      "presentation": {
        "description": "Manage DVR sources, schedules, and recording policy.",
        "label": "Manage DVR"
      },
      "scopes": [
        "server",
        "live-source",
        "recording",
        "recording-rule"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "deleteDVRRecordings",
      "presentation": {
        "description": "Permanently remove recorded programs.",
        "label": "Delete DVR recordings"
      },
      "scopes": [
        "server",
        "recording"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "deleteMedia",
      "presentation": {
        "description": "Permanently remove media from an authorized library.",
        "label": "Delete media"
      },
      "scopes": [
        "library",
        "media"
      ]
    },
    {
      "delegable": true,
      "grantAuthority": "server",
      "id": "transcode",
      "presentation": {
        "description": "Convert media when direct playback is unavailable.",
        "label": "Transcode media"
      },
      "scopes": [
        "server",
        "library",
        "media"
      ]
    },
    {
      "delegable": false,
      "grantAuthority": "server-owner",
      "id": "manageLibraries",
      "presentation": {
        "description": "Add, edit, scan, and remove libraries.",
        "label": "Manage libraries"
      },
      "scopes": [
        "server",
        "library"
      ]
    },
    {
      "delegable": false,
      "grantAuthority": "server-owner",
      "id": "manageUsers",
      "presentation": {
        "description": "Create, update, and remove server members.",
        "label": "Manage people"
      },
      "scopes": [
        "server",
        "membership"
      ]
    },
    {
      "delegable": false,
      "grantAuthority": "server-owner",
      "id": "manageServer",
      "presentation": {
        "description": "Change server-wide settings and operations.",
        "label": "Manage server"
      },
      "scopes": [
        "server"
      ]
    }
  ],
  "platform": {
    "availabilityStates": [
      "available",
      "temporarily_unavailable",
      "not_configured",
      "not_implemented"
    ],
    "capabilityStates": [
      "supported",
      "unsupported",
      "unavailable",
      "degraded"
    ],
    "formFactors": [
      "mobile",
      "television",
      "browser"
    ],
    "runtimeIdentities": [
      "ios",
      "tvos",
      "android",
      "android_tv",
      "fire_tv",
      "roku",
      "web"
    ]
  },
  "recoveryActions": [
    "retry",
    "retry_after",
    "refresh_route",
    "refresh_credentials",
    "reselect_profile",
    "sign_in",
    "upgrade_client",
    "upgrade_server",
    "contact_owner",
    "contact_support",
    "terminal"
  ],
  "schemaRevision": 2,
  "workClasses": [
    {
      "id": "security-fence",
      "priority": 1,
      "purpose": "Revocation, authorization revision, session and grant invalidation, and emergency stop."
    },
    {
      "id": "protected-capture",
      "priority": 2,
      "purpose": "Committed DVR writes and durability work that prevents recording loss."
    },
    {
      "id": "established-playback",
      "priority": 3,
      "purpose": "Playback bytes, ready segments, grant extension, and active seek continuity."
    },
    {
      "id": "playback-start",
      "priority": 4,
      "purpose": "Admission, initial or seek generation, and explicit player commands."
    },
    {
      "id": "interactive",
      "priority": 5,
      "purpose": "Browse, search, settings reads, and ordinary mutations."
    },
    {
      "id": "foreground-transfer",
      "priority": 6,
      "purpose": "User-requested download preparation and transfer."
    },
    {
      "id": "background-media",
      "priority": 7,
      "purpose": "Inventory, metadata, artwork, analysis, and optimization."
    },
    {
      "id": "maintenance",
      "priority": 8,
      "purpose": "Backup, vacuum, cleanup, retention, and non-urgent repair."
    }
  ]
} as const;
