// Generated by tools/foundation/generate.py; DO NOT EDIT.
export type RecoveryAction = 'retry' | 'retry_after' | 'refresh_route' | 'refresh_credentials' | 'reselect_profile' | 'sign_in' | 'upgrade_client' | 'upgrade_server' | 'contact_owner' | 'contact_support' | 'terminal';
export type ExternalAction = 'open_home' | 'open_library' | 'open_media' | 'open_profile' | 'open_settings' | 'open_downloads' | 'play_media' | 'resume_media' | 'accept_invitation' | 'reset_password';
export const foundationContract = {
  "$schema": "./portico-foundation.schema.json",
  "build": {
    "buildNumber": "0",
    "channel": "development",
    "commit": "UNSTAMPED_DEVELOPMENT",
    "timestamp": null,
    "version": "0.0.0-development"
  },
  "compatibility": {
    "apiContract": {
      "identity": "apps/portico-cloud/api/openapi/portico-hosted.openapi.json+apps/portico-server/api/openapi/openapi.yaml+apps/portico-server/api/openapi/portico-server.openapi.json",
      "digestAlgorithm": "sha256",
      "digest": "33e17683ba7d56442d93f58766834ae624ccac6f525e89bc68548729e7137bcd"
    },
    "envelopeRevision": 1,
    "semanticRevisions": {
      "externalAction": 1,
      "paginationCursor": 1,
      "playback": 1,
      "problemRecoveryAction": 1,
      "product": 1,
      "viewerProfileAuthority": 1
    },
    "supportedClientProtocol": {
      "maximum": 1,
      "minimum": 1
    }
  },
  "environments": [
    "development",
    "test",
    "staging",
    "production"
  ],
  "externalActions": [
    "open_home",
    "open_library",
    "open_media",
    "open_profile",
    "open_settings",
    "open_downloads",
    "play_media",
    "resume_media",
    "accept_invitation",
    "reset_password"
  ],
  "forwardCompatibility": {
    "authorizationOnPartialUpgrade": "never_broaden",
    "apiContractDigestMismatch": "allow_semantic_overlap",
    "unknownOptionalCapabilities": "ignore_and_preserve",
    "unknownRequiredSemantics": "reject_actionably"
  },
  "platform": {
    "availabilityStates": [
      "available",
      "temporarily_unavailable",
      "not_configured",
      "not_implemented"
    ],
    "capabilityStates": [
      "supported",
      "unsupported",
      "unavailable",
      "degraded"
    ],
    "formFactors": [
      "mobile",
      "television",
      "browser"
    ],
    "runtimeIdentities": [
      "ios",
      "tvos",
      "android",
      "android_tv",
      "fire_tv",
      "roku",
      "web"
    ]
  },
  "recoveryActions": [
    "retry",
    "retry_after",
    "refresh_route",
    "refresh_credentials",
    "reselect_profile",
    "sign_in",
    "upgrade_client",
    "upgrade_server",
    "contact_owner",
    "contact_support",
    "terminal"
  ],
  "schemaRevision": 1
} as const;
