// Generated by cmd/genopenapi. Do not edit.
export const liveDvrLibraryOperationContract = [
  {
    "audience": "management",
    "clientCoreMethod": "adminDvrOperationalStatus",
    "method": "GET",
    "operationId": "getAdminDVRStatus",
    "path": "/admin/dvr/status",
    "responseSchema": "DVROperationalStatus"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLibraryChannels",
    "method": "GET",
    "operationId": "listAdminLibraryChannels",
    "path": "/admin/library-channels",
    "responseSchema": "AdminLibraryChannelListResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "createAdminLibraryChannel",
    "method": "POST",
    "operationId": "createLibraryChannel",
    "path": "/admin/library-channels",
    "responseSchema": "LibraryChannelAggregate"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLibraryChannelHealth",
    "method": "GET",
    "operationId": "getLibraryChannelHealth",
    "path": "/admin/library-channels/health",
    "responseSchema": "LibraryChannelHealthResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "uploadAdminLibraryChannelLogo",
    "method": "POST",
    "operationId": "uploadLibraryChannelLogo",
    "path": "/admin/library-channels/logos",
    "responseSchema": "LibraryChannelLogoAsset"
  },
  {
    "audience": "management",
    "clientCoreMethod": "deleteAdminLibraryChannelLogo",
    "method": "DELETE",
    "operationId": "deleteLibraryChannelLogo",
    "path": "/admin/library-channels/logos/{assetId}",
    "responseSchema": "SuccessResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "reorderAdminLibraryChannels",
    "method": "POST",
    "operationId": "reorderLibraryChannels",
    "path": "/admin/library-channels/reorder",
    "responseSchema": "AdminLibraryChannelListResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "restoreAdminLibraryChannelDefaults",
    "method": "POST",
    "operationId": "restoreLibraryChannelDefaults",
    "path": "/admin/library-channels/restore-defaults",
    "responseSchema": "LibraryChannelRestoreDefaultsResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLibraryChannelTemplates",
    "method": "GET",
    "operationId": "listLibraryChannelTemplates",
    "path": "/admin/library-channels/templates",
    "responseSchema": "LibraryChannelTemplatesResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLibraryChannelTemplateApplicability",
    "method": "GET",
    "operationId": "evaluateLibraryChannelTemplateApplicability",
    "path": "/admin/library-channels/templates/applicability",
    "responseSchema": "LibraryChannelApplicabilityResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLibraryChannel",
    "method": "GET",
    "operationId": "getAdminLibraryChannel",
    "path": "/admin/library-channels/{channelId}",
    "responseSchema": "LibraryChannelAggregate"
  },
  {
    "audience": "management",
    "clientCoreMethod": "replaceAdminLibraryChannel",
    "method": "PUT",
    "operationId": "replaceLibraryChannel",
    "path": "/admin/library-channels/{channelId}",
    "responseSchema": "LibraryChannelAggregate"
  },
  {
    "audience": "management",
    "clientCoreMethod": "deleteAdminLibraryChannel",
    "method": "DELETE",
    "operationId": "deleteLibraryChannel",
    "path": "/admin/library-channels/{channelId}",
    "responseSchema": "SuccessResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "regenerateAdminLibraryChannel",
    "method": "POST",
    "operationId": "regenerateLibraryChannel",
    "path": "/admin/library-channels/{channelId}/regenerate",
    "responseSchema": "LibraryChannelGeneration"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRecordingGroups",
    "method": "GET",
    "operationId": "getDvrRecordingGroups",
    "path": "/dvr/recording-groups",
    "responseSchema": "GetDvrRecordingGroupsResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRecordings",
    "method": "GET",
    "operationId": "getDvrRecordings",
    "path": "/dvr/recordings",
    "responseSchema": "GetDvrRecordingsResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "createDvrRecording",
    "method": "POST",
    "operationId": "postDvrRecordings",
    "path": "/dvr/recordings",
    "responseSchema": "DVRRecording"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRecording",
    "method": "GET",
    "operationId": "getDvrRecordingsId",
    "path": "/dvr/recordings/{id}",
    "responseSchema": "DVRRecording"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "updateDvrRecording",
    "method": "PATCH",
    "operationId": "patchDvrRecordingsId",
    "path": "/dvr/recordings/{id}",
    "responseSchema": "DVRRecording"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "deleteDvrRecording",
    "method": "DELETE",
    "operationId": "deleteDvrRecordingsId",
    "path": "/dvr/recordings/{id}",
    "responseSchema": "DeleteDvrRecordingsIdResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRecordingHlsUrl",
    "method": "GET",
    "operationId": "getDvrRecordingsIdHlsResource",
    "path": "/dvr/recordings/{id}/hls/{resource}",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "inspectDvrRecordingHlsUrl",
    "method": "HEAD",
    "operationId": "headDvrRecordingsIdHlsResource",
    "path": "/dvr/recordings/{id}/hls/{resource}",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "playDvrRecording",
    "method": "POST",
    "operationId": "postDvrRecordingsIdPlayback",
    "path": "/dvr/recordings/{id}/playback",
    "responseSchema": "PlaybackResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRecordingStreamUrl",
    "method": "GET",
    "operationId": "getDvrRecordingsIdStream",
    "path": "/dvr/recordings/{id}/stream",
    "responseSchema": "GetDvrRecordingsIdStreamResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "inspectDvrRecordingStreamUrl",
    "method": "HEAD",
    "operationId": "headDvrRecordingsIdStream",
    "path": "/dvr/recordings/{id}/stream",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRules",
    "method": "GET",
    "operationId": "getDvrRules",
    "path": "/dvr/rules",
    "responseSchema": "GetDvrRulesResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "createDvrRule",
    "method": "POST",
    "operationId": "postDvrRules",
    "path": "/dvr/rules",
    "responseSchema": "DVRRecordingRule"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrRule",
    "method": "GET",
    "operationId": "getDvrRulesId",
    "path": "/dvr/rules/{id}",
    "responseSchema": "DVRRecordingRule"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "updateDvrRule",
    "method": "PATCH",
    "operationId": "patchDvrRulesId",
    "path": "/dvr/rules/{id}",
    "responseSchema": "DVRRecordingRule"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "deleteDvrRule",
    "method": "DELETE",
    "operationId": "deleteDvrRulesId",
    "path": "/dvr/rules/{id}",
    "responseSchema": "DeleteDvrRulesIdResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrSchedule",
    "method": "GET",
    "operationId": "getDvrSchedule",
    "path": "/dvr/schedule",
    "responseSchema": "GetDvrScheduleResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "dvrStatus",
    "method": "GET",
    "operationId": "getDVRStatus",
    "path": "/dvr/status",
    "responseSchema": "DVRConsumerStatus"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "libraryChannels",
    "method": "GET",
    "operationId": "listLibraryChannels",
    "path": "/library-channels",
    "responseSchema": "LibraryChannelListResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "libraryChannelsGuide",
    "method": "GET",
    "operationId": "getLibraryChannelsGuide",
    "path": "/library-channels/guide",
    "responseSchema": "LibraryChannelsGuide"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "libraryChannelLogoUrl",
    "method": "GET",
    "operationId": "getLibraryChannelLogo",
    "path": "/library-channels/logos/{assetId}",
    "responseSchema": "GetLibraryChannelLogoResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "libraryChannelGuide",
    "method": "GET",
    "operationId": "getLibraryChannelGuide",
    "path": "/library-channels/{channelId}/guide",
    "responseSchema": "LibraryChannelGuide"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "libraryChannelHlsUrl",
    "method": "GET",
    "operationId": "getLibraryChannelHLSResource",
    "path": "/library-channels/{channelId}/hls/{resource}",
    "responseSchema": "GetLibraryChannelHLSResourceResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "inspectLibraryChannelHlsUrl",
    "method": "HEAD",
    "operationId": "inspectLibraryChannelHLSResource",
    "path": "/library-channels/{channelId}/hls/{resource}",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "tuneLibraryChannel",
    "method": "POST",
    "operationId": "tuneLibraryChannel",
    "path": "/library-channels/{channelId}/tune",
    "responseSchema": "LibraryChannelTuneResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTv",
    "method": "GET",
    "operationId": "getLiveTv",
    "path": "/live-tv",
    "responseSchema": "LiveTVSourceSummaryListResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvChannel",
    "method": "GET",
    "operationId": "getLiveTvChannelsChannelId",
    "path": "/live-tv/channels/{channelId}",
    "responseSchema": "LiveTVChannel"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "updateLiveTvChannel",
    "method": "PATCH",
    "operationId": "patchLiveTvChannelsChannelId",
    "path": "/live-tv/channels/{channelId}",
    "responseSchema": "LiveTVChannel"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvHlsItemUrl",
    "method": "GET",
    "operationId": "getLiveTvHlsChannelIdItem",
    "path": "/live-tv/hls/{channelId}/item",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvHlsPlaylistUrl",
    "method": "GET",
    "operationId": "getLiveTvHlsChannelIdPlaylistM3u8",
    "path": "/live-tv/hls/{channelId}/playlist.m3u8",
    "responseSchema": "TextPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvHlsSegmentUrl",
    "method": "GET",
    "operationId": "getLiveTvHlsChannelIdSegment",
    "path": "/live-tv/hls/{channelId}/segment",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvLogoUrl",
    "method": "GET",
    "operationId": "getLiveTvLogosChannelId",
    "path": "/live-tv/logos/{channelId}",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "startLiveTvPlayback",
    "method": "POST",
    "operationId": "postLiveTvPlay",
    "path": "/live-tv/play",
    "responseSchema": "PlaybackResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLiveTvSources",
    "method": "GET",
    "operationId": "getLiveTvSources",
    "path": "/live-tv/sources",
    "responseSchema": "LiveTVSourceListResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "createLiveTvSource",
    "method": "POST",
    "operationId": "postLiveTvSources",
    "path": "/live-tv/sources",
    "responseSchema": "LiveTVSource"
  },
  {
    "audience": "management",
    "clientCoreMethod": "discoverHDHomeRunSources",
    "method": "POST",
    "operationId": "postLiveTvSourcesHdhomerunDiscover",
    "path": "/live-tv/sources/hdhomerun/discover",
    "responseSchema": "PostLiveTvSourcesHdhomerunDiscoverResponse"
  },
  {
    "audience": "management",
    "clientCoreMethod": "testAddLiveTvSource",
    "method": "POST",
    "operationId": "postLiveTvSourcesTestAdd",
    "path": "/live-tv/sources/test-add",
    "responseSchema": "LiveTVSource"
  },
  {
    "audience": "management",
    "clientCoreMethod": "adminLiveTvSource",
    "method": "GET",
    "operationId": "getLiveTvSourcesSourceId",
    "path": "/live-tv/sources/{sourceId}",
    "responseSchema": "LiveTVSource"
  },
  {
    "audience": "management",
    "clientCoreMethod": "updateLiveTvSource",
    "method": "PATCH",
    "operationId": "patchLiveTvSourcesSourceId",
    "path": "/live-tv/sources/{sourceId}",
    "responseSchema": "LiveTVSource"
  },
  {
    "audience": "management",
    "clientCoreMethod": "deleteLiveTvSource",
    "method": "DELETE",
    "operationId": "deleteLiveTvSourcesSourceId",
    "path": "/live-tv/sources/{sourceId}",
    "responseSchema": "SuccessResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvChannels",
    "method": "GET",
    "operationId": "getLiveTvSourcesSourceIdChannels",
    "path": "/live-tv/sources/{sourceId}/channels",
    "responseSchema": "LiveTVChannelListResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvGuide",
    "method": "GET",
    "operationId": "getLiveTvSourcesSourceIdGuide",
    "path": "/live-tv/sources/{sourceId}/guide",
    "responseSchema": "LiveTVGuide"
  },
  {
    "audience": "management",
    "clientCoreMethod": "refreshLiveTvSource",
    "method": "POST",
    "operationId": "postLiveTvSourcesSourceIdRefresh",
    "path": "/live-tv/sources/{sourceId}/refresh",
    "responseSchema": "LiveTVSource"
  },
  {
    "audience": "management",
    "clientCoreMethod": "liveTvStreams",
    "method": "GET",
    "operationId": "getLiveTvStreams",
    "path": "/live-tv/streams",
    "responseSchema": "GetLiveTvStreamsResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "liveTvStreamUrl",
    "method": "GET",
    "operationId": "getLiveTvStreamsChannelId",
    "path": "/live-tv/streams/{channelId}",
    "responseSchema": "BinaryPayload"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "closeLiveTvStream",
    "method": "POST",
    "operationId": "postLiveTvStreamsChannelIdClose",
    "path": "/live-tv/streams/{channelId}/close",
    "responseSchema": "PlaybackSessionTerminalAcknowledgement"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "openLiveTvStream",
    "method": "POST",
    "operationId": "postLiveTvStreamsChannelIdOpen",
    "path": "/live-tv/streams/{channelId}/open",
    "responseSchema": "PlaybackResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "renegotiatePlayback",
    "method": "POST",
    "operationId": "renegotiatePlaybackSession",
    "path": "/playback-sessions/{sessionId}/renegotiate",
    "responseSchema": "PlaybackResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "createCastBootstrap",
    "method": "POST",
    "operationId": "postPlaybackCastBootstrap",
    "path": "/playback/cast/bootstrap",
    "responseSchema": "CastBootstrapResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "reconnectCast",
    "method": "POST",
    "operationId": "postPlaybackCastReconnect",
    "path": "/playback/cast/reconnect",
    "responseSchema": "CastReceiverSessionState"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "redeemCastBootstrap",
    "method": "POST",
    "operationId": "postPlaybackCastRedeem",
    "path": "/playback/cast/redeem",
    "responseSchema": "CastReceiverSessionResponse"
  },
  {
    "audience": "viewer",
    "clientCoreMethod": "castTransferStatus",
    "method": "POST",
    "operationId": "postPlaybackCastTransferStatus",
    "path": "/playback/cast/transfer-status",
    "responseSchema": "CastTransferStatusResponse"
  }
] as const;

export type LiveDvrLibraryOperation = (typeof liveDvrLibraryOperationContract)[number];
