import { semanticIcon, type SemanticIconId } from '@porticomediaserver/client-core';
import {
  PlaybackTechnicalStatsIcon,
  NavigationLibraryIcon,
  PlaybackCaptionsIcon,
  NavigationExpandIcon,
  NavigationCollapseIcon,
  StatusWarningIcon,
  PlaybackAutoplayIcon,
  StatusErrorIcon,
  ActionDownloadIcon,
  ActionPrepareDownloadIcon,
  PlaybackSeekForwardIcon,
  DeviceStorageIcon,
  MediaPlaylistIcon,
  StatusLoadingIcon,
  ActionFullscreenEnterIcon,
  CommunicationMicrophoneIcon,
  ActionFullscreenExitIcon,
  MediaMusicIcon,
  PlaybackPauseIcon,
  PlaybackPlayIcon,
  PlaybackRepeatIcon,
  PlaybackRepeatOneIcon,
  ActionRefreshIcon,
  PlaybackSeekBackIcon,
  ActionResetIcon,
  PreferencePlaybackIcon,
  PlaybackShuffleIcon,
  PlaybackPreviousIcon,
  PlaybackNextIcon,
  ActionDeleteIcon,
  PlaybackVolumeIcon,
  PlaybackMuteIcon,
  ActionCustomizeIcon,
  DeviceOfflineIcon,
  ActionCloseIcon,
  type PorticoSemanticIconComponent,
} from '#portico-icons';

const productGlyphs: Readonly<Record<string, PorticoSemanticIconComponent>> = {
  "Activity": PlaybackTechnicalStatsIcon,
  "BookOpen": NavigationLibraryIcon,
  "Captions": PlaybackCaptionsIcon,
  "ChevronDown": NavigationExpandIcon,
  "ChevronUp": NavigationCollapseIcon,
  "CirclePlay": PlaybackAutoplayIcon,
  "CircleX": StatusErrorIcon,
  "Download": ActionDownloadIcon,
  "DownloadCloud": ActionPrepareDownloadIcon,
  "FastForward": PlaybackSeekForwardIcon,
  "HardDrive": DeviceStorageIcon,
  "ListMusic": MediaPlaylistIcon,
  "LoaderCircle": StatusLoadingIcon,
  "Maximize2": ActionFullscreenEnterIcon,
  "Mic2": CommunicationMicrophoneIcon,
  "Minimize2": ActionFullscreenExitIcon,
  "Music2": MediaMusicIcon,
  "Pause": PlaybackPauseIcon,
  "Play": PlaybackPlayIcon,
  "Repeat": PlaybackRepeatIcon,
  "Repeat1": PlaybackRepeatOneIcon,
  "RefreshCw": ActionRefreshIcon,
  "Rewind": PlaybackSeekBackIcon,
  "RotateCcw": ActionResetIcon,
  "RotateCw": PlaybackSeekForwardIcon,
  "Settings2": PreferencePlaybackIcon,
  "Shuffle": PlaybackShuffleIcon,
  "SkipBack": PlaybackPreviousIcon,
  "SkipForward": PlaybackNextIcon,
  "Trash2": ActionDeleteIcon,
  "TriangleAlert": StatusWarningIcon,
  "Volume2": PlaybackVolumeIcon,
  "VolumeX": PlaybackMuteIcon,
  "WandSparkles": ActionCustomizeIcon,
  "WifiOff": DeviceOfflineIcon,
  "X": ActionCloseIcon,
};

export function ProductLanguageIcon({ id, className, filled = false }: { id: SemanticIconId; className?: string; filled?: boolean }) {
  const definition = semanticIcon(id);
  const Icon = productGlyphs[definition.glyph] ?? StatusWarningIcon;
  return <Icon className={className} fill={filled ? 'currentColor' : 'none'} aria-hidden="true" focusable="false" />;
}
