import { semanticIcon, type SemanticIconId } from '@portico/client-core';
import {
  Activity,
  BookOpen,
  Captions,
  ChevronDown,
  ChevronUp,
  CircleAlert,
  CirclePlay,
  CircleX,
  Download,
  DownloadCloud,
  FastForward,
  HardDrive,
  ListMusic,
  LoaderCircle,
  Maximize2,
  Mic2,
  Minimize2,
  Music2,
  Pause,
  Play,
  Repeat,
  Repeat1,
  RefreshCw,
  Rewind,
  RotateCcw,
  RotateCw,
  Settings2,
  Shuffle,
  SkipBack,
  SkipForward,
  Trash2,
  TriangleAlert,
  Volume2,
  VolumeX,
  WandSparkles,
  WifiOff,
  X,
  type LucideIcon,
} from '#portico-icons';

const productGlyphs: Readonly<Record<string, LucideIcon>> = {
  Activity,
  BookOpen,
  Captions,
  ChevronDown,
  ChevronUp,
  CirclePlay,
  CircleX,
  Download,
  DownloadCloud,
  FastForward,
  HardDrive,
  ListMusic,
  LoaderCircle,
  Maximize2,
  Mic2,
  Minimize2,
  Music2,
  Pause,
  Play,
  Repeat,
  Repeat1,
  RefreshCw,
  Rewind,
  RotateCcw,
  RotateCw,
  Settings2,
  Shuffle,
  SkipBack,
  SkipForward,
  Trash2,
  TriangleAlert,
  Volume2,
  VolumeX,
  WandSparkles,
  WifiOff,
  X,
};

export function ProductLanguageIcon({ id, className, filled = false }: { id: SemanticIconId; className?: string; filled?: boolean }) {
  const definition = semanticIcon(id);
  const Icon = productGlyphs[definition.glyph] ?? CircleAlert;
  return <Icon className={className} fill={filled ? 'currentColor' : 'none'} aria-hidden="true" focusable="false" />;
}
