import test from 'node:test';
import assert from 'node:assert/strict';
import {WorkspaceApi} from '../src/bridge/workspace-api.ts';
import {liveSourceDraft,clearLiveSourceDraft} from '@core/live-source-draft.ts';
function apiFor(base:string,token:string,scope:string,fetcher?:typeof fetch){const api=new WorkspaceApi(base,token,scope,fetcher);api.activateSourceAuthority();return api;}
const response=(status:number)=>new Response(JSON.stringify({error:{code:'request_failed',message:'Unavailable'}}),{status,headers:{'Content-Type':'application/json'}});
test('both transports clear matching authority on denial and preserve temporary errors',async()=>{for(const status of [401,403,503])for(const bounded of [false,true]){const api=apiFor('http://127.0.0.1:19518','synthetic','viewer',async()=>response(status));liveSourceDraft('viewer').update({playlist:'private provider input'});await assert.rejects(bounded?api.requestBounded('/v1/admin/live-sources',1024,new AbortController().signal):api.request('/v1/guide'));assert.equal(liveSourceDraft('viewer').getSnapshot().playlist,status===503?'private provider input':'');api.disposeSourceAuthority();}clearLiveSourceDraft();});
test('old workspace denial and cleanup cannot clear a newly authenticated workspace, including same scope',async()=>{for(const scope of ['new','old']){let resolve!:(r:Response)=>void;const old=apiFor('http://127.0.0.1:19518','old-token','old',()=>new Promise(r=>resolve=r));liveSourceDraft('old').update({playlist:'old secret'});const pending=old.request('/v1/guide');const current=apiFor('http://127.0.0.1:19518','new-token',scope);liveSourceDraft(scope).update({playlist:'new secret'});resolve(response(401));await assert.rejects(pending);old.disposeSourceAuthority();assert.equal(liveSourceDraft(scope).getSnapshot().playlist,'new secret');current.disposeSourceAuthority();}clearLiveSourceDraft();});
test('same-authority edits or a draft first created during request are cleared on actual401',async()=>{for(const hadDraft of [true,false]){let resolve!:(r:Response)=>void;const api=apiFor('http://127.0.0.1:19518','current','viewer',()=>new Promise(r=>resolve=r));if(hadDraft)liveSourceDraft('viewer').update({playlist:'initial'});const pending=api.request('/v1/libraries');liveSourceDraft('viewer').update({playlist:'edited while pending'});resolve(response(401));await assert.rejects(pending);assert.equal(liveSourceDraft('viewer').getSnapshot().playlist,'');api.disposeSourceAuthority();}});
test('unrelated resource forbidden does not erase source draft',async()=>{const api=apiFor('http://127.0.0.1:19518','synthetic','viewer',async()=>response(403));liveSourceDraft('viewer').update({name:'Unsaved source'});await assert.rejects(api.request('/v1/items/restricted'));await assert.rejects(api.requestBounded('/v1/admin/support-report',1024,new AbortController().signal));assert.equal(liveSourceDraft('viewer').getSnapshot().name,'Unsaved source');api.disposeSourceAuthority();});

test('effect replay reactivates same API and old lease callbacks cannot clear replayed authority',async()=>{const pending:Array<(v:Response)=>void>=[];const api=new WorkspaceApi('http://127.0.0.1:19518','current','viewer',()=>new Promise(r=>pending.push(r)));const old=api.activateSourceAuthority();const first=api.request('/v1/guide');api.disposeSourceAuthority(old);const current=api.activateSourceAuthority();liveSourceDraft('viewer').update({playlist:'current secret'});pending[0](response(401));await assert.rejects(first);api.disposeSourceAuthority(old);assert.equal(liveSourceDraft('viewer').getSnapshot().playlist,'current secret');const second=api.request('/v1/guide');pending[1](response(401));await assert.rejects(second);assert.equal(liveSourceDraft('viewer').getSnapshot().playlist,'');api.disposeSourceAuthority(current);});
