allowBuilds:
  '@biomejs/cli-darwin-x64': set this to true or false
  '@biomejs/cli-linux-arm64': set this to true or false
  '@biomejs/cli-linux-arm64-musl': set this to true or false
  '@biomejs/cli-linux-x64': set this to true or false
  '@biomejs/cli-linux-x64-musl': set this to true or false
  '@biomejs/cli-win32-arm64': set this to true or false
  '@biomejs/cli-win32-x64': set this to true or false
  '@esbuild/aix-ppc64': set this to true or false
  '@esbuild/android-arm': set this to true or false
  '@esbuild/android-arm64': set this to true or false
  '@esbuild/android-x64': set this to true or false
  '@esbuild/darwin-x64': set this to true or false
  '@esbuild/freebsd-arm64': set this to true or false
  '@esbuild/freebsd-x64': set this to true or false
  '@esbuild/linux-arm': set this to true or false
  '@esbuild/linux-arm64': set this to true or false
  '@esbuild/linux-ia32': set this to true or false
  '@esbuild/linux-loong64': set this to true or false
  '@esbuild/linux-mips64el': set this to true or false
  '@esbuild/linux-ppc64': set this to true or false
  '@esbuild/linux-riscv64': set this to true or false
  '@esbuild/linux-s390x': set this to true or false
  '@esbuild/linux-x64': set this to true or false
  '@esbuild/netbsd-arm64': set this to true or false
  '@esbuild/netbsd-x64': set this to true or false
  '@esbuild/openbsd-arm64': set this to true or false
  '@esbuild/openbsd-x64': set this to true or false
  '@esbuild/openharmony-arm64': set this to true or false
  '@esbuild/sunos-x64': set this to true or false
  '@esbuild/win32-arm64': set this to true or false
  '@esbuild/win32-ia32': set this to true or false
  '@esbuild/win32-x64': set this to true or false
  '@napi-rs/lzma-linux-x64-gnu': set this to true or false
  '@rollup/rollup-android-arm-eabi': set this to true or false
  '@rollup/rollup-android-arm64': set this to true or false
  '@rollup/rollup-darwin-x64': set this to true or false
  '@rollup/rollup-freebsd-arm64': set this to true or false
  '@rollup/rollup-freebsd-x64': set this to true or false
  '@rollup/rollup-linux-arm-gnueabihf': set this to true or false
  '@rollup/rollup-linux-arm-musleabihf': set this to true or false
  '@rollup/rollup-linux-arm64-gnu': set this to true or false
  '@rollup/rollup-linux-arm64-musl': set this to true or false
  '@rollup/rollup-linux-loong64-gnu': set this to true or false
  '@rollup/rollup-linux-loong64-musl': set this to true or false
  '@rollup/rollup-linux-ppc64-gnu': set this to true or false
  '@rollup/rollup-linux-ppc64-musl': set this to true or false
  '@rollup/rollup-linux-riscv64-gnu': set this to true or false
  '@rollup/rollup-linux-riscv64-musl': set this to true or false
  '@rollup/rollup-linux-s390x-gnu': set this to true or false
  '@rollup/rollup-linux-x64-gnu': set this to true or false
  '@rollup/rollup-linux-x64-musl': set this to true or false
  '@rollup/rollup-openbsd-x64': set this to true or false
  '@rollup/rollup-openharmony-arm64': set this to true or false
  '@rollup/rollup-win32-arm64-msvc': set this to true or false
  '@rollup/rollup-win32-ia32-msvc': set this to true or false
  '@rollup/rollup-win32-x64-gnu': set this to true or false
  '@rollup/rollup-win32-x64-msvc': set this to true or false
  esbuild: set this to true or false
